### PR TITLE
fix: Ensure the processclient have a correct timeout / fix flacky test

### LINKED ISSUE #4400: Unit Test Flake: TestProcessorClient_Allocate
* https://github.com/googleforgames/agones/pull/4399#issuecomment-3694109127
* https://console.cloud.google.com/cloud-build/builds/48359fc9-574f-43ba-a29c-541461d6652e;step=19?invt=AcFVzA&project=agones-images

```
time="2025-12-27T17:22:10Z" level=error msg="Timeout waiting for processor response" requestID=8b5a5058-05fb-4bb8-b019-cf3e31c770b1
--- FAIL: TestProcessorClient_Allocate (0.25s)
    --- FAIL: TestProcessorClient_Allocate/successful_allocation_with_batchSize_3 (0.09s)
        client_test.go:216: expected no error for request 0, got rpc error: code = DeadlineExceeded desc = allocation timeout after 50ms
        client_test.go:219: expected response for request 0, got nil
time="2025-12-27T17:22:11Z" level=info msg="Pull request handler stopping"
FAIL
FAIL	agones.dev/agones/pkg/processor	0.459s
?   	agones.dev/agones/pkg/sdk	[no test files]
```

### PR DESCRIPTION
**Pull request by lacroixthomas**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
/kind bug

**What this PR does / Why we need it**:

Fix flacky test around processor client and a 50ms allocation timeout 

**Which issue(s) this PR fixes**:

Closes #4400 

**Special notes for your reviewer**:

I've been running this test 500 time with parallel and with many scenarios, but sadly I had the same result with the fix and without it, wasn't able to reproduce it, but I'm pretty confident it's coming from that

### CODE REVIEW

**Comment by lacroixthomas** [comment]
I wasn't able to reproduce it locally, but been doing quite a lot of test with it, I'm pretty sure this fix the issue 😄

**Comment by lacroixthomas** [comment]
TestControllerGameServersNodeState already an issue open for that

/gcbrun

File: pkg/processor/client_test.go [hunk 1]
```diff
@@ -192,20 +192,36 @@ func TestProcessorClient_Allocate(t *testing.T) {
...
 			}
 
-			// Wait for requests to be added
-			time.Sleep(5 * time.Millisecond)
-			p.batchMutex.RLock()
-			for i := 0; i < tc.batchSize && i < len(p.hotBatch.Requests); i++ {
-				reqIDs[i] = p.hotBatch.Requests[i].RequestId
+			// Wait until hotBatch has the expected number of requests
+			// to ensure all the allocate calls have been processed and batched
+			timeout := time.After(500 * time.Millisecond)
```
Comment (lacroixthomas) [inline pkg/processor/client_test.go]: Will check if I can use the assert.Eventually on this one, will come back to it *
