### PR TITLE
APIService: Updates to handlers for 1.27.x

### LINKED ISSUE #3172: Stale GroupVersion discovery: allocation.agones.dev/v1 (Namespace deletion)
**What happened**:
Any namespace deletion is stuck in `Terminating` even though Agones is still installed and the `allocation.agones.dev/v1` API is available. The namespaces are stuck in this state indefinitely and can only be deleted by removing the `NamespaceDeletionDiscoveryFailure` finalizer. This is because the finalizer fails:

```yaml
status:
  phase: Terminating
  conditions:
    - type: NamespaceDeletionDiscoveryFailure
      status: 'True'
      lastTransitionTime: '2023-05-19T18:41:31Z'
      reason: DiscoveryFailed
      message: >-
        Discovery failed for some groups, 1 failing: unable to retrieve the
        complete list of server APIs: allocation.agones.dev/v1: stale
        GroupVersion discovery: allocation.agones.dev/v1
```

The apiserver log reports `DiscoveryManager: Failed to download discovery for agones-system/agones-controller-service:443: 404 404 page not found`.

I've looked in the Kubernetes implementation and this error is thrown [here](https://github.com/kubernetes/kubernetes/blob/589d6f388680b29f7f7961bda4f4262733b54210/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go#L268). Any error returned by this method leads to the error in the `NamespaceDeletionDiscoveryFailure`, reporting stale GroupVersion discovery.

And while looking into the `webhooks` port of the `agones-controller-service`, indeed `404` is returned for `/apis`.

**What you expected to happen**:
I'd expect namespaces to delete normally, even with Agones installed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install the Helm Chart with the values provided below
2. Create a new namespace
3. Try to delete this new namespace
4. Observe it being stuck in Terminating

**Anything else we need to know?**:

Helm-Values:
```yaml
agones:
  allocator:
    install: false
  controller:
    healthCheck:
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 1
    persistentLogs: false
  featureGates: PlayerTracking=true&SDKGracefulTermination=true&StateAllocationFilter=true
  metrics:
    serviceMonitor:
      enabled: true
  ping:
    install: false
gameservers:
  namespaces:
  - minecraft
```

**Environment**:
- Agones version: 1.31.0
- Kubernetes version (use `kubectl version`): 1.26.5
- Cloud provider or hardware configuration: Hetzner Cloud (Talos Linux)
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): Embedded into the descriptions

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

This includes a bug fix for the issue outlined in
https://github.com/kubernetes/kubernetes/issues/119662, specifically returning HTTP 406 for root /apis for all requests.

Also included an empty OpenAPI v3 discovery document to `/openapi/v3` to stop the regular requests from the K8s control plane, while also bringing the implementation for `/openapi/v2` to be consistent with the new one.

**Which issue(s) this PR fixes**:

Closes #3172

**Special notes for your reviewer**:

Snuck in a linter fix as well.

### CODE REVIEW

File: pkg/gameservers/controller_test.go [hunk 1]
```diff
@@ -233,7 +233,6 @@ func TestControllerSyncGameServerWithDevIP(t *testing.T) {
 		gsFixture.ApplyDefaults()
 		gsFixture.Status.State = agonesv1.GameServerStateRequestReady
 
-
```
Comment (markmandel) [inline pkg/gameservers/controller_test.go:236]: My local linter complained about this. Maybe a newer version?

**Review by zmerlynn — APPROVED** [review]

**Review by gongmax — APPROVED** [review]

**Review by roberthbailey — COMMENTED** [review]
Should https://github.com/googleforgames/agones/blob/main/pkg/util/apiserver/apiserver_test.go be updated to test the new endpoints?

**Comment by markmandel** [comment]
> Should https://github.com/googleforgames/agones/blob/main/pkg/util/apiserver/apiserver_test.go be updated to test the new endpoints?

Sure, why not. They were really doing a whole lot, but more tests betterer.

**Comment by markmandel** [comment]
Unit tests added!

**Review by roberthbailey — APPROVED** [review]
