### PR TITLE
Fix update counter to return correct values

### LINKED ISSUE #4220: Rest UpdateCounter not returning correct values
**What happened**:
api is returning wrong data for UpdateCounter

**What you expected to happen**:
Get current count and capacity
but got:
```
{"name":"","count":"0","capacity":"0"}
```

**How to reproduce it (as minimally and precisely as possible)**:
```
curl -sSd '{"count": "5'", "capacity": "64"}' -H "Content-Type: application/json" -X PATCH http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/counters/players
```

**Anything else we need to know?**:
both return the right data:
```
curl http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/counters/players
```
->
```
{"name":"players","count":"39","capacity":"64"}
```

```
curl http://localhost:${AGONES_SDK_HTTP_PORT}/gameserver
```
->
```
    "ports": [
      {
        "name": "test",
        "port": 13743
      }
    ],
    "players": null,
    "counters": {
      "players": {
        "count": "58",
        "capacity": "64"
      }
    },
    "lists": {}

```

**Environment**:
- Agones version: 1.49.0

### PR DESCRIPTION
**Pull request by indurireddy-TF**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #4220

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aditya-shantanu** [comment]
Add a test that validates this change ?

**Comment by indurireddy-TF** [comment]
> Add a test that validates this change ?

Hi @aditya-shantanu I added a new test case to verify the changes.

File: pkg/sdkserver/sdkserver_test.go [hunk 1]
```diff
@@ -1270,6 +1271,18 @@ func TestSDKServerUpdateCounter(t *testing.T) {
...
 		},
+		"projected state returned": {
+			counterName: "starfish",
+			requests: []*beta.UpdateCounterRequest{
+				{CounterUpdateRequest: &beta.CounterUpdateRequest{
+					Name:      "starfish",
+					CountDiff: 15,
+				}},
+			},
+			want:       agonesv1.CounterStatus{Count: int64(25), Capacity: int64(100)},
```
Comment (aditya-shantanu) [inline pkg/sdkserver/sdkserver_test.go]: nit: Change this to something other than the value before it so you are sure it got updated.

**Review by aditya-shantanu — APPROVED** [review]

File: pkg/sdkserver/sdkserver_test.go (hunk 1 above)
Comment (indurireddy-TF) [reply pkg/sdkserver/sdkserver_test.go]: Updated CountDiff to 7. The initial counter value remains 10, consistent with existing test cases.

**Comment by markmandel** [comment]
Thanks for this! I would like to take this for a spin when integrated with our simple gameserver container we use for e2e testing. 

We don't have a great way of automating testing this, so it may need to be manual 🙃

File: pkg/sdkserver/sdkserver_test.go [hunk 2]
```diff
@@ -1328,11 +1341,15 @@ func TestSDKServerUpdateCounter(t *testing.T) {
 
 			// Update the Counter
 			for i, req := range testCase.requests {
-				_, err = sc.UpdateCounter(context.Background(), req)
+				resp, err := sc.UpdateCounter(context.Background(), req)
 				if testCase.updateErrs[i] {
 					assert.Error(t, err)
 				} else {
 					assert.NoError(t, err)
+					if test == "projected state returned" {
```
Comment (markmandel) [inline pkg/sdkserver/sdkserver_test.go]: 🤔 any reason to only do this for this test? Could we not do this for every test for extra test coverage?

Comment (indurireddy-TF) [reply pkg/sdkserver/sdkserver_test.go]: Thanks, Mark. I see your point completely on expanding the coverage.

I initially limited the assertion to a new, dedicated test case to ensure we validated the new return behavior without altering the legacy state assumptions of the older tests.

However, I absolutely agree that extending the assertion offers better coverage. I can proceed with refactoring to assert the full result object in every successful test case.

Comment (markmandel) [reply pkg/sdkserver/sdkserver_test.go]: Awesome, once that change comes in - then I think we are good to merge!

File: pkg/sdkserver/sdkserver.go [hunk 3]
```diff
@@ -945,7 +945,25 @@ func (s *SDKServer) UpdateCounter(_ context.Context, in *beta.UpdateCounterReque
...
+func projectCounterState(name string, batchCounter counterUpdateRequest) *beta.Counter {
+	currentCapacity := batchCounter.counter.Capacity
+	if batchCounter.capacitySet != nil {
+		currentCapacity = *batchCounter.capacitySet
+	}
+	currentCount := batchCounter.counter.Count
+	if batchCounter.countSet != nil {
+		currentCount = *batchCounter.countSet
+	}
+	currentCount += batchCounter.diff
```
Comment (igooch) [inline pkg/sdkserver/sdkserver.go:961]: +1 to the bot's comment. The `CapacitySet` doesn't validate the count diff, so it's possible the `currentCount` could be outside the range [0,Capacity].

**Comment by markmandel** [comment]
I think this is good to go. @igooch did you want to do another review?

**Review by igooch — APPROVED** [review]
LGTM, good work.
