### PR TITLE
GameServer container restart before Ready, move to Unhealthy state After (v2)

### LINKED ISSUE #956: Game server container crash before Ready, should restart, not move to Unhealthy
**What happened**:

If the game server container crashes at any stage, the GameServer moved to Unhealthy straight away.

**What you expected to happen**:

According to: https://agones.dev/site/docs/guides/health-checking/

> If any of the GameServer container fails health checking, or exits before the GameServer moves to Ready then, it is restart as per the restartPolicy (which defaults to “Always”)

**How to reproduce it (as minimally and precisely as possible)**:

We will need a e2e test that has a CRASH command on udp-simple that does a `sdk.Exit(1)` and then test what happens when a crash occurs before `Ready` and after `Ready`.

**Anything else we need to know?**:

Logic can be found here:
https://github.com/googleforgames/agones/blob/master/pkg/gameservers/health.go#L87

**Environment**:
- Agones version: development
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): N/A
- Others:

### PR DESCRIPTION
**Pull request by markmandel**
This brings our implementation inline with what our health checking documentation states that we do.

This is done by implementing extra checks in the HealthController to determine if it's appropriate to move to Unhealthy rather than allow a restart to occur.

Replaced PR #1069

Closes #956

### CODE REVIEW

**Comment by markmandel** [comment]
/hold

e2e test found a bug in my implementation. Need to fix!

**Comment by roberthbailey** [comment]
I'm waiting for @markmandel to remove the hold before I review.

**Comment by markmandel** [comment]
/hold cancel 

While I think this should stay in feature freeze, as I would like to go through a development cycle for extra confidence, it is ready for review again now.

**Comment by markmandel** [comment]
OMG! We can finally get this reviewed an in a release! :dancer: I feel like I've been working on this bug forever :smile:

**Comment by roberthbailey** [comment]
Now that the release is out this is the next review up on my list.

File: test/e2e/gameserver_test.go [hunk 1]
```diff
@@ -213,6 +213,113 @@ func TestGameServerUnhealthyAfterDeletingPod(t *testing.T) {
...
+		// create a connection each time, as weird stuff happens if the receiver isn't up and running.
+		conn, err := net.Dial("udp", address)
+		assert.NoError(t, err)
+		defer conn.Close() // nolint: errcheck
+		// doing this last, so that there is a short delay between the message being sent, and the check.
+		_, err = conn.Write([]byte("READY"))
+		logger.WithError(err).WithField("gs", newGs.ObjectMeta.Name).WithField("state", newGs.Status.State).Info("no ready, trying again")
+		return false, nil
+	})
+	if !assert.NoError(t, err) {
```
Comment (roberthbailey) [inline test/e2e/gameserver_test.go]: elsewhere I just see `assert.NoError()` but this one wraps that and calls `FailNow`. Is that to short circuit running the remainder of the test? If so, would it be simpler to just write

```go
if err != nil {
    assert.FailNow(t, ...)
}
```

I find the statements that check the boolean result of the assert to be hard to read, and they are basically just checking if err is or isn't nil and calling another assert, which can be done more simply.

File: test/e2e/gameserver_test.go [hunk 2]
```diff
@@ -213,6 +213,113 @@ func TestGameServerUnhealthyAfterDeletingPod(t *testing.T) {
...
+
+		// create a connection each time, as weird stuff happens if the receiver isn't up and running.
+		conn, err := net.Dial("udp", address)
+		assert.NoError(t, err)
+		defer conn.Close() // nolint: errcheck
+		// doing this last, so that there is a short delay between the message being sent, and the check.
+		// also gives the process a chance to come back up
+		_, err = conn.Write([]byte("CRASH"))
+		logger.WithError(err).Info("no crash, trying again")
+		return false, nil
```
Comment (roberthbailey) [inline test/e2e/gameserver_test.go]: should this return `false, err` instead of nil? Or will returning an error short circuit the polling function? It seems weird that the error writing the udp packet is logged but otherwise ignored.

File: test/e2e/gameserver_test.go [hunk 3]
```diff
@@ -213,6 +213,113 @@ func TestGameServerUnhealthyAfterDeletingPod(t *testing.T) {
...
+	err = wait.Poll(time.Second, 3*time.Minute, func() (bool, error) {
+		conn, err := net.Dial("udp", address)
+		assert.NoError(t, err)
+		defer conn.Close() // nolint: errcheck
+		_, err = conn.Write([]byte("CRASH"))
+		if err != nil {
+			logger.WithError(err).Warn("could not send CRASH udp packet")
+			return false, nil
+		}
+		return true, nil
```
Comment (roberthbailey) [inline test/e2e/gameserver_test.go]: Why is successfully sending the packet sufficient to break the loop? Shouldn't we verify that the pod actually exited (e.g. the game server received the packet)?

File: test/e2e/gameserver_test.go [hunk 4]
```diff
@@ -213,6 +213,113 @@ func TestGameServerUnhealthyAfterDeletingPod(t *testing.T) {
...
+		logger.WithError(err).WithField("gs", newGs.ObjectMeta.Name).WithField("state", newGs.Status.State).Info("no ready, trying again")
+		return false, nil
+	})
+	if !assert.NoError(t, err) {
+		assert.FailNow(t, "Could not make GameServer Ready")
+	}
+	// now crash, should be unhealthy, since it's after being Ready
+	logger.Info("crashing again, should be unhealthy")
+	// retry on crash, as with the restarts, sometimes Go takes a moment to send this through.
+	err = wait.Poll(time.Second, 3*time.Minute, func() (bool, error) {
```
Comment (roberthbailey) [inline test/e2e/gameserver_test.go]: All three of these udp sending loops are very similar in structure (write a packet, check for state, try again). Have you considered moving them into a helper function?

File: pkg/gameservers/health.go [hunk 5]
```diff
@@ -190,15 +190,61 @@ func (hc *HealthController) syncGameServer(key string) error {
...
-
-	if _, err := hc.gameServerGetter.GameServers(gs.ObjectMeta.Namespace).Update(gsCopy); err != nil {
-		return errors.Wrapf(err, "error updating GameServer %s to unhealthy", gs.ObjectMeta.Name)
+	skip, err := hc.skipUnhealthy(gs)
+	if err != nil {
+		return err
 	}
 
-	hc.recorder.Event(gs, corev1.EventTypeWarning, string(gsCopy.Status.State), "Issue with Gameserver pod")
+	if !skip {
```
Comment (roberthbailey) [inline pkg/gameservers/health.go]: This should be inverted. 

```
if skip {
  // The game server hasn't been marked ready, so it doesn't transition to unhealthy. 
  return nil
}
```

To leave the other code with one less level of indentation.

File: pkg/gameservers/health.go [hunk 6]
```diff
@@ -190,15 +190,61 @@ func (hc *HealthController) syncGameServer(key string) error {
...
+			return errors.Wrapf(err, "error updating GameServer %s to unhealthy", gs.ObjectMeta.Name)
+		}
+
+		hc.recorder.Event(gs, corev1.EventTypeWarning, string(gsCopy.Status.State), "Issue with Gameserver pod")
+	}
 
 	return nil
 }
+
+// skipUnhealthy checks the GameServer is Ready or after Ready, and what the container crash state
```
Comment (roberthbailey) [inline pkg/gameservers/health.go]: This comment is really hard to read. I tried taking a stab at rewriting it but didn't have any particularly great ways to phrase it. If you can think of a way to say it more clearly that'd be awesome.

File: pkg/gameservers/health_test.go [hunk 7]
```diff
@@ -79,15 +79,114 @@ func TestHealthUnschedulableWithNoFreePorts(t *testing.T) {
...
+			hc := NewHealthController(healthcheck.NewHandler(), m.KubeClient, m.AgonesClient, m.KubeInformerFactory, m.AgonesInformerFactory)
+			gs := &agonesv1.GameServer{ObjectMeta: metav1.ObjectMeta{Name: "test", Namespace: defaultNs}, Spec: newSingleContainerSpec()}
+			gs.ApplyDefaults()
+			pod, err := gs.Pod()
+			assert.NoError(t, err)
+
+			v.setup(gs, pod)
+
+			m.KubeClient.AddReactor("list", "pods", func(action k8stesting.Action) (bool, runtime.Object, error) {
+				return true, &corev1.PodList{Items: []corev1.Pod{*pod}}, nil
```
Comment (roberthbailey) [inline pkg/gameservers/health_test.go]: It looks like this doesn't cover the branches where pod doesn't exist or k8s returns an error to put the request back into the queue.

File: pkg/gameservers/health_test.go [hunk 8]
```diff
@@ -79,15 +79,114 @@ func TestHealthUnschedulableWithNoFreePorts(t *testing.T) {
...
+		expected bool
+	}{
+		"scheduled and terminated container": {
+			setup: func(gs *agonesv1.GameServer, pod *corev1.Pod) {
+				gs.Status.State = agonesv1.GameServerStateScheduled
+				pod.Status.ContainerStatuses = []corev1.ContainerStatus{{
+					Name:  gs.Spec.Container,
+					State: corev1.ContainerState{Terminated: &corev1.ContainerStateTerminated{}},
+				}}
+			}, expected: true},
```
Comment (roberthbailey) [inline pkg/gameservers/health_test.go]: please put expected on a new line

File: pkg/gameservers/health_test.go [hunk 9]
```diff
@@ -79,15 +79,114 @@ func TestHealthUnschedulableWithNoFreePorts(t *testing.T) {
...
+				pod.Status.ContainerStatuses = []corev1.ContainerStatus{{
+					Name:  gs.Spec.Container,
+					State: corev1.ContainerState{Terminated: &corev1.ContainerStateTerminated{}},
+				}}
+			},
+			expected: false,
+		},
+		"before ready, with no terminated container": {
+			setup: func(gs *agonesv1.GameServer, pod *corev1.Pod) {
+				gs.Status.State = agonesv1.GameServerStateScheduled
```
Comment (roberthbailey) [inline pkg/gameservers/health_test.go]: the before ready states are all the same, given the other test coverage it may not matter but you could vary which state is set to one of the other 4 states that are before ready.

File: pkg/apis/agones/v1/gameserver.go [hunk 10]
```diff
@@ -91,6 +91,10 @@ const (
 	// DevAddressAnnotation is an annotation to indicate that a GameServer hosted outside of Agones.
 	// A locally hosted GameServer is not managed by Agones it is just simply registered.
 	DevAddressAnnotation = "agones.dev/dev-address"
```
[the remark this answers is not in the document]
Comment (markmandel) [reply pkg/apis/agones/v1/gameserver.go]: Good catch, we should fix this.

File: test/e2e/gameserver_test.go (hunk 2 above)
Comment (markmandel) [reply test/e2e/gameserver_test.go]: You are indeed correct - returning the error will short circuit the poll. It may return an error as the receiver may not be up and running yet, so it's useful for debugging purposes, but otherwise it is expected.

File: test/e2e/gameserver_test.go (hunk 4 above)
Comment (markmandel) [reply test/e2e/gameserver_test.go]: Nice. Done!

File: test/e2e/gameserver_test.go (hunk 3 above)
Comment (markmandel) [reply test/e2e/gameserver_test.go]: Fixed, now we have a helper method.

File: pkg/gameservers/health.go (hunk 5 above)
Comment (markmandel) [reply pkg/gameservers/health.go]: Ah excellent suggestion!

File: pkg/gameservers/health.go (hunk 6 above)
Comment (markmandel) [reply pkg/gameservers/health.go]: Took a stab. PTAL when I push my changes up. I think it's better though.

**Comment by markmandel** [comment]
@roberthbailey this should be good to review again :+1:

**Comment by markmandel** [comment]
dancing!
