### PR TITLE
Flaky: TestGameServerReserve

### LINKED ISSUE #1543: Flaky: TestGameServerReserve
TestGameServerReserve has reared it's ugly head again as being flaky!

Here are the most up to date test logs. You can see it never gets to the part where it outputs the events, since it [never finds the Reserved and Ready state in the event log](https://github.com/googleforgames/agones/blob/master/test/e2e/gameserver_test.go#L614).

```
time="2020-05-13 19:31:59.201" level=info msg="sending RESERVE command" test=TestGameServerReserve
time="2020-05-13 19:31:59.264" level=info msg="Received response" test=TestGameServerReserve
time="2020-05-13 19:31:59.264" level=info msg="Waiting for 10 seconds" test=TestGameServerReserve
time="2020-05-13 19:32:09.264" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:12.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:18.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:24.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:29.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:33.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:39.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:45.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:49.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:53.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:32:56.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:00.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:04.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:08.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:12.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:15.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:18.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:22.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:25.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:28.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:30.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:32.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:34.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:37.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:39.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:41.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:43.569" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:43.570" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:43.570" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:43.570" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:43.570" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:43.570" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:43.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:44.742" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:44.743" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:44.743" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:44.743" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:44.743" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:44.743" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:44.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:46.512" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:46.512" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:46.512" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:46.512" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:46.513" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:46.513" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:46.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:48.678" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:48.678" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:48.679" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:48.679" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:48.679" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:48.679" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:48.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:49.732" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:49.732" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:49.732" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:49.732" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:49.732" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:49.733" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:49.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:51.888" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:51.888" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:51.888" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:51.888" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:51.889" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:51.889" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:51.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:52.829" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:52.829" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:52.829" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:52.830" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:52.830" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:52.830" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:52.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:54.546" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:54.546" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:54.546" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:54.546" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:54.546" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:54.547" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:54.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:55.948" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:55.949" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:55.949" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:55.949" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:55.949" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:55.949" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:56.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:57.886" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:57.886" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:57.886" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:57.886" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:57.886" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:57.886" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:57.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:33:59.626" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:33:59.626" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:33:59.626" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:33:59.626" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:33:59.626" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:33:59.626" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:33:59.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:01.139" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:01.139" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:01.139" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:01.139" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:01.139" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:01.139" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:01.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:02.709" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:02.710" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:02.710" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:02.710" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:02.710" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:02.710" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:02.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:03.360" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:03.361" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:03.361" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:03.361" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:03.361" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:03.361" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:03.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:04.886" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:04.886" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:04.887" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:04.887" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:04.887" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:04.887" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:04.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:05.955" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:05.955" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:05.955" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:05.955" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:05.956" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:05.956" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:06.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:07.512" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:07.512" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:07.512" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:07.512" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:07.513" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:07.513" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:07.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:08.860" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:08.861" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:08.861" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:08.861" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:08.861" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:08.861" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:08.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:09.427" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:09.427" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:09.427" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:09.427" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:09.427" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:09.427" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:09.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:11.225" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:11.225" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:11.226" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:11.226" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:11.226" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:11.226" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:11.913" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:12.365" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:12.365" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:12.365" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:12.365" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:12.365" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:12.365" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
time="2020-05-13 19:34:12.366" level=info msg="checking gameserver events" test=TestGameServerReserve
time="2020-05-13 19:34:13.160" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:55 +0000 UTC" last-time="2020-05-13 19:30:55 +0000 UTC" message="Port allocated" name=udp-serverthm7g.160ead4ac6760ff7 reason=PortAllocation test=TestGameServerReserve
time="2020-05-13 19:34:13.160" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:57 +0000 UTC" last-time="2020-05-13 19:30:57 +0000 UTC" message="Pod udp-serverthm7g created" name=udp-serverthm7g.160ead4b3c8641cd reason=Creating test=TestGameServerReserve
time="2020-05-13 19:34:13.160" level=info msg="gs event details" count=1 first-time="2020-05-13 19:30:58 +0000 UTC" last-time="2020-05-13 19:30:58 +0000 UTC" message="Address and port populated" name=udp-serverthm7g.160ead4ba45d1031 reason=Scheduled test=TestGameServerReserve
time="2020-05-13 19:34:13.160" level=info msg="gs event details" count=2 first-time="2020-05-13 19:31:24 +0000 UTC" last-time="2020-05-13 19:32:10 +0000 UTC" message="SDK state change" name=udp-serverthm7g.160ead51b5db289f reason=RequestReady test=TestGameServerReserve
time="2020-05-13 19:34:13.160" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:49 +0000 UTC" last-time="2020-05-13 19:31:49 +0000 UTC" message="SDK.Ready() complete" name=udp-serverthm7g.160ead57792eeee0 reason=Ready test=TestGameServerReserve
time="2020-05-13 19:34:13.160" level=info msg="gs event details" count=1 first-time="2020-05-13 19:31:59 +0000 UTC" last-time="2020-05-13 19:31:59 +0000 UTC" message="SDK state change, for 10s" name=udp-serverthm7g.160ead59b21725c7 reason=Reserved test=TestGameServerReserve
--- FAIL: TestGameServerReserve (203.30s)
    gameserver_test.go:632:
        	Error Trace:	gameserver_test.go:632
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestGameServerReserve
```

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
Trying to test transitive state while it is actively changing is fraught with peril. Tests flake, hair is pulled, and screams echo throughout the lands.

This PR allows one to send a duration to the RESERVE command to udp-simple, as well as update TestGameServerReserve to only confirm concrete states, which therefore can't flake.

**Which issue(s) this PR fixes**:

Closes #1543

**Special notes for your reviewer**:

Tests will fail, as image does not yet exist. Once initial reviews are complete, I'll push up the new udp-simple image.

### CODE REVIEW

File: examples/simple-udp/main.go [hunk 1]
```diff
@@ -144,7 +144,17 @@ func readWriteLoop(conn net.PacketConn, stop chan struct{}, s *sdk.SDK) {
 			allocate(s)
 
 		case "RESERVE":
-			reserve(s)
+			if len(parts) == 2 {
+				if dur, err := time.ParseDuration(parts[1]); err != nil {
+					respond(conn, sender, err.Error()+"\n")
```
Comment (roberthbailey) [inline examples/simple-udp/main.go:149]: Should this response also be prefixed with "ERROR:"?

Comment (markmandel) [reply examples/simple-udp/main.go:149]: Yes, yes it should! 

(And this is why I ask for review before pushing images :smile:)

Let me know if there is anything else, and I'll push the image so the e2e tests can run.

**Comment by markmandel** [comment]
Image has been pushed up. This was making me climb up the walls with frustration. Feels like it's failing on just about every run.

File: examples/simple-udp/main.go [hunk 2]
```diff
@@ -144,7 +145,17 @@ func readWriteLoop(conn net.PacketConn, stop chan struct{}, s *sdk.SDK) {
 			allocate(s)
 
 		case "RESERVE":
-			reserve(s)
+			if len(parts) == 2 {
```
Comment (roberthbailey) [inline examples/simple-udp/main.go:148]: Sorry I didn't catch this last time, but it would be a bit more idiomatic to do:

```
if len(parts) != 2 {
  respond()
  continue
}
if dur, err := ... ; err != nil {
  respond()
  continue
}
reserve(s, dur)
```

so that the non-error flow isn't indented quite so much.

Comment (markmandel) [reply examples/simple-udp/main.go:148]: Ah that is nicer. I'll make that change.

**Comment by markmandel** [comment]
Would help if I _actually_ pushed the right image.

File: test/e2e/fleetautoscaler_test.go [hunk 3]
```diff
@@ -456,72 +456,81 @@ func TestAutoscalerWebhook(t *testing.T) {
 	assert.True(t, found, "Expected error was not received")
 }
 
+// Instructions: https://agones.dev/site/docs/getting-started/create-webhook-fleetautoscaler/#chapter-2-configuring-https-fleetautoscaler-webhook-with-ca-bundle
```
Comment (markmandel) [inline test/e2e/fleetautoscaler_test.go:459]: fyi @aLekSer , I updated the certs here, and added a comment on how to update and when expiry should happen.
