### PR TITLE
Flaky: TestGameServerRestartBeforeReadyCrash

### LINKED ISSUE #1173: Flaky: TestGameServerRestartBeforeReadyCrash
**What happened**:

Occasionally we're seeing the TestGameServerRestartBeforeReadyCrash e2e test fail. Not 100% sure if it's a flaky test, or a bug in code (possible it could be a bug).

**What you expected to happen**:

It passes every time.

**How to reproduce it (as minimally and precisely as possible)**:

Hard to repro, only happens sometimes.

**Anything else we need to know?**:

<details>
<summary>e2e test log:</summary>
<code>
Step #21: time="2019-11-05 14:34:18.378" level=info msg="Waiting for us to have an address to send things to" test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:34:28.776" level=info msg="GameServer created" gs=udp-serverc77fb test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:34:28.777" level=info msg="Dialing UDP message to address" address="35.203.183.113:7847" test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:34:28.777" level=info msg="crashing, and waiting to see restart" test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:34:37.885" level=info msg="sending message" fields.msg=CRASH gs=udp-serverc77fb state=Scheduled test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:34:50.147" level=info msg="sending message" fields.msg=CRASH gs=udp-serverc77fb state=Scheduled test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:35:01.498" level=info msg="sending message" fields.msg=CRASH gs=udp-serverc77fb state=Scheduled test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:35:09.559" level=info msg="sending message" fields.msg=CRASH gs=udp-serverc77fb state=Scheduled test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:35:16.957" level=info msg="sending message" fields.msg=CRASH gs=udp-serverc77fb state=Scheduled test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:35:26.471" level=info msg="successfully crashed. Moving on!" test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:35:43.585" level=info msg="marking GameServer as ready" test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:35:47.960" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Scheduled test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:35:55.283" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:00.523" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:05.746" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:08.464" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:10.194" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:13.725" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:16.508" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:19.695" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:22.501" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:25.894" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:28.909" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:30.894" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:33.693" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:36.530" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:38.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:42.094" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:44.999" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:48.113" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:51.035" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:53.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:56.972" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:36:59.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:02.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:05.972" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:08.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:11.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:14.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:17.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:20.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:23.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:26.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:29.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:32.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:35.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:38.972" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:41.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:44.971" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:47.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:50.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:53.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:56.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:37:59.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:02.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:05.980" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:08.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:11.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:14.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:17.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:20.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:23.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:26.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:29.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:32.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:35.969" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:38.971" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:41.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:44.971" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:47.970" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: time="2019-11-05 14:38:47.979" level=info msg="sending message" fields.msg=READY gs=udp-serverc77fb state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: --- FAIL: TestGameServerRestartBeforeReadyCrash (271.91s)
Step #21:         	Test:       	TestGameServerRestartBeforeReadyCrash
</code>
</details>

Looks to be moving to `Unhealthy` before it should. Need to determine reason.

**Environment**:
- Agones version: 1.2.0-development
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:50:59Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.15", GitCommit:"7b5157a7c600aa8ee6e2b36b56c478e030d5bfe2", GitTreeState:"clean", BuildDate:"2019-10-07T20:39:12Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
  Will go looking to see if we can pull up the sidecar and/or controller logs as well, to see what is forcing the health failure.

- Others: N/A

### PR DESCRIPTION
**Pull request by markmandel**
There was a race condition in which if a game server container crashes,
and then restarts and moves to ready, the crashed game server
container id could be the recorded container that was added as an
Annotation to the GameServer, which would is incorrect.

This fix has a check in place to ensure the game server container id
that is being added as the Annotation value, is from an actual running
container.

Closes #1173

### CODE REVIEW

**Comment by markmandel** [comment]
Looking good maybe. Don't want to get too ahead of myself though.

File: test/e2e/gameserver_test.go [hunk 1]
```diff
@@ -301,7 +301,7 @@ func TestGameServerRestartBeforeReadyCrash(t *testing.T) {
 		return false
 	})
 	if err != nil {
-		assert.FailNowf(t, "Could not make GameServer Ready: %v", err.Error())
+		assert.FailNowf(t, "Could not make GameServer Ready", "reason: %v", err.Error())
```
Comment (roberthbailey) [inline test/e2e/gameserver_test.go]: should there be extra quotes around the comma?

**Comment by roberthbailey** [comment]
Just a few nits (unrelated to actually fixing the flaky test, but you touched the other files too).

File: test/e2e/gameserver_test.go (hunk 1 above)
Comment (markmandel) [reply test/e2e/gameserver_test.go]: @aLekSer pointed this out to me on a previous PR, because the error string wasn't coming through very well. The signature for FailNowf is:

`func FailNowf(t TestingT, failureMessage string, msg string, args ...interface{}) bool`

So the `failureMessage` won't parse any `Sprintf` style injection, only the `msg` argument will.

Comment (roberthbailey) [reply test/e2e/gameserver_test.go]: Weird, that's not what I expected based on X...f functions in other packages.
