### PR TITLE
Flakiness: TestGameServerAllocationDeletionOnUnAllocate

### LINKED ISSUE #1326: Flaky: TestGameServerAllocationDeletionOnUnAllocate
This one seems odd to me, and only happens sometimes.

```
--- FAIL: TestGameServerAllocationDeletionOnUnAllocate (0.18s)
    gameserverallocation_test.go:388: 
        	Error Trace:	gameserverallocation_test.go:388
        	Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:""}, Status:"Failure", Message:"the server is currently unable to handle the request (post gameserverallocations.allocation.agones.dev)", Reason:"ServiceUnavailable", Details:(*v1.StatusDetails)(0xc0000e41e0), Code:503}}
        	Test:       	TestGameServerAllocationDeletionOnUnAllocate
```

More context: 
https://console.cloud.google.com/gcr/builds/1c60176f-02b8-421d-8218-451a3e566cd6?project=258182270954

### PR DESCRIPTION
**Pull request by markmandel**
Realised that Go test will compile and run tests in parallel per file,
which means we could shutdown the controller while an allocation is in
process - which means, it will fail completely, as the Kubernetes API
cannot reach the controller's http endpoint for allocation.

Split the controller tests into a separate package which could be run
with -parallel=1 so that there can be no race condition.

Also did some grouping of e2e test functionality to reduce code
repetition.

Closes #1326

### CODE REVIEW

**Comment by markmandel** [comment]
Got bit by different flaky bug #1276 - running again.

**Comment by markmandel** [comment]
Running a bunch of tests to make sure it's working, and if that passes, will cleanup and submit.

File: test/e2e/controller/missing_test.go [hunk 1]
```diff
@@ -12,7 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-package e2e
+package controller
```
Comment (pooneh-m) [inline test/e2e/controller/missing_test.go]: Can we rename the file name to something else? missing_test.go sounds like it includes the tests that were missing from test coverage :D

File: test/e2e/controller/missing_test.go [hunk 2]
```diff
@@ -75,8 +75,67 @@ func deleteAgonesControllerPods() error {
...
+	})
+}
+
 // getAgonesControllerPods returns all the Agones controller pods
 func getAgonesControllerPods() (*corev1.PodList, error) {
 	opts := metav1.ListOptions{LabelSelector: labels.Set{"agones.dev/role": "controller"}.String()}
 	return framework.KubeClient.CoreV1().Pods("agones-system").List(opts)
 }
+
+func defaultGameServer(namespace string) *agonesv1.GameServer {
```
Comment (pooneh-m) [inline test/e2e/controller/missing_test.go]: Can we refactor [this](https://github.com/googleforgames/agones/blob/master/test/e2e/gameserver_test.go#L577) instead?

Comment (markmandel) [reply test/e2e/controller/missing_test.go]: Yeah I thought about centralising that too - moving it into framework maybe. Wasn't sure if 2 duplication was enough to warrant it. If you think so, I'm happy to do it.

I assume that is what you mean here?

File: test/e2e/controller/missing_test.go (hunk 1 above)
Comment (markmandel) [reply test/e2e/controller/missing_test.go]: `crash_test.go` ? That better?

Tests where the controller crashes for whatever reason? That sound better?

Comment (pooneh-m) [reply test/e2e/controller/missing_test.go]: Thanks, much better!

File: test/e2e/controller/missing_test.go (hunk 2 above)
Comment (pooneh-m) [reply test/e2e/controller/missing_test.go]: Correct, thanks for the clarification. framework.go should be a good place or you can add a new file such as testhelper and centralize the common helper methods there?

File: test/e2e/controller/missing_test.go (hunk 1 above)
Comment (markmandel) [reply test/e2e/controller/missing_test.go]: SGTM! Will make the change.

File: test/e2e/controller/missing_test.go (hunk 2 above)
Comment (markmandel) [reply test/e2e/controller/missing_test.go]: Sounds good - I like the idea of testhelper.go or similar (I think we have a previous pattern for this somewhere, maybe, I can copy).
