### PR TITLE
Fix tests timeout, WatchGameServer recent feature

### LINKED ISSUE #1672: Go unit test timeout after 10m
**What happened**:

Test times out after 10m. Looks like some kind of deadlock.

**What you expected to happen**:

Test to pass.

**How to reproduce it (as minimally and precisely as possible)**:

Currently only happening occasionally in CI. Trying to work out how to reproduce it locally.

**Anything else we need to know?**:

I wonder if having `SDKWatchSendOnExecute` feature flag enabled will cause one of the previous either local or sdkserver tests to hang. That's my current theory. Seems to be focused on tests of either of those areas fro the stacktrackes though.

**Environment**:
- Agones version: Development
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):

Instances in tests:
https://github.com/googleforgames/agones/pull/1663#issuecomment-652153122
https://github.com/googleforgames/agones/pull/1662#issuecomment-652041201

Another grep of Test from a failed test:

```
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerCapacity
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerCapacity.func1(0xc0008e6410, 0xc0000d4040, 0xc0004b8c60)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc0003c9860, 0xc0000100f0, 0xc0003ee7e0)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc0003eb790, 0xc0000100c0, 0xc0006df320)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc0003ebd40, 0xc0000100d8, 0xc0006dfb00)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc00097c680, 0xc00018e098, 0xc0001d0b40)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc000120b60, 0xc000010070, 0xc000470000)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc000367520, 0xc000302028, 0xc000410000)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerWatchGameServer
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerWatchGameServer.func1(0xc0000c2000, 0xc0004b4700, 0xc0000d40c0, 0xc0004b8b40)
agones.dev/agones/pkg/sdkserver.TestSDKServerUpdateEventHandler(0xc000460360)
agones.dev/agones/pkg/sdkserver.TestSDKServerWatchGameServer(0xc000460000)
```

```
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:264 +0x2c6
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:265 +0x5d
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:308 +0x334
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:309 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:658 +0x278
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:779 +0x59e
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1251 +0x86
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1251 +0x86
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1252 +0x78
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1252 +0x78
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1259 +0x6b
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1259 +0x6b
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1260 +0x93
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1260 +0x93
```

- Others: None

### PR DESCRIPTION
**Pull request by aLekSer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature

/kind hotfix

**What this PR does / Why we need it**:

Move GetGameServer() call out of streamMutex lock.
Add previously written tests to run without this feature, as they
timeouts.

**Which issue(s) this PR fixes**:

Closes #1672 

**Special notes for your reviewer**:
A way to check that test do not freeze now:
```
cd ./pkg/sdkserver
go test -run SDKServer
```

### CODE REVIEW

File: pkg/sdkserver/sdkserver.go [hunk 1]
```diff
@@ -511,6 +510,7 @@ func (s *SDKServer) WatchGameServer(_ *sdk.Empty, stream sdk.SDK_WatchGameServer
 		}
 	}
 
+	s.streamMutex.Lock()
```
Comment (markmandel) [inline pkg/sdkserver/sdkserver.go:513]: Excellent catch!

File: pkg/sdkserver/sdkserver_test.go [hunk 2]
```diff
@@ -745,6 +753,14 @@ func TestSDKServerWatchGameServerFeatureSDKWatchSendOnExecute(t *testing.T) {
 
 func TestSDKServerSendGameServerUpdate(t *testing.T) {
 	t.Parallel()
+
+	agruntime.FeatureTestMutex.Lock()
```
Comment (markmandel) [inline pkg/sdkserver/sdkserver_test.go:757]: Happy to push this through to remove the flakiness, but curious why we need these here for these tests?

I couldn't see anything specific in here that required the lock?

Would be good to have a note somewhere indicating where the deadlock was generated, so we can avoid it in future tests.

File: pkg/sdkserver/sdkserver_test.go [hunk 3]
```diff
@@ -745,6 +753,14 @@ func TestSDKServerWatchGameServerFeatureSDKWatchSendOnExecute(t *testing.T) {
...
+	defer agruntime.FeatureTestMutex.Unlock()
+	err := agruntime.ParseFeatures(string(agruntime.FeatureSDKWatchSendOnExecute) + "=false")
+	if !assert.NoError(t, err) {
```
Comment (markmandel) [inline pkg/sdkserver/sdkserver_test.go:760]: We should probably stick to:
```
	if err != nil {
		assert.FailNow(t, err.Error())
	}
```
Pattern, as per #1659 

Or if we want to bring in the `require` package, happy to see that as well.

**Comment by markmandel** [comment]
@aLekSer do we want to wait on this to be fixed up before release today? Would be nice to have the locking fix in place before a stable cut.

File: pkg/sdkserver/sdkserver_test.go (hunk 2 above)
Comment (aLekSer) [reply pkg/sdkserver/sdkserver_test.go:757]: Down the lines we are setting FeatureSDKWatchSendOnExecute to false. Without this lock some other test could set it back to true while this test got executed.
I can check this by setting next to true:
```
err := agruntime.ParseFeatures(string(agruntime.FeatureSDKWatchSendOnExecute) + "=false")
```

Comment (markmandel) [reply pkg/sdkserver/sdkserver_test.go:757]: I guess my point was, if it did flip to true, does the test actually fail?

For the sake of expediency, happy for it to stay for now - I was just wondering.

Comment (aLekSer) [reply pkg/sdkserver/sdkserver_test.go:757]: If I set "=true" here (or some other parallel test would do that) then test would fail:
```
--- FAIL: TestSDKServerUpdateEventHandler (19.22s)
    sdkserver_test.go:1299:
                Error Trace:    sdkserver_test.go:1299
                                                        asm_amd64.s:1357
                Error:          Expected nil, but got: could not retrieve GameServer default/test: gameserver.agones.dev "test" not found
                Test:           TestSDKServerUpdateEventHandler
    sdkserver_test.go:817:
                Error Trace:    sdkserver_test.go:817
                Error:          Expected nil, but got: &errors.errorString{s:"timed out waiting for
the condition"}
```

Comment (markmandel) [reply pkg/sdkserver/sdkserver_test.go:757]: Got it! Thanks! Then yes, let's definitely keep the lock there! :+1:

**Comment by aLekSer** [comment]
Mark, I will give you more details on deadlock source. I suppose the only reason is the test nature, start from this function:
https://github.com/googleforgames/agones/blob/3f608ded646517d701389a116a8da8f37d77f42b/pkg/sdkserver/sdkserver_test.go#L1298
```
func asyncWatchGameServer(t *testing.T, sc *SDKServer, stream sdk.SDK_WatchGameServerServer) {
	go func() {
		err := sc.WatchGameServer(&sdk.Empty{}, stream)
		assert.Nil(t, err)
	}()
}
```

**Comment by markmandel** [comment]
Do we want to put a comment in the code somewhere talking about the lock, just so it doesn't accidentally become an issue again somehow?

**Comment by aLekSer** [comment]
Well, taking closer look.
`getGameServer()` function would not return if `gsWaitForSync` is not `Done()`.
```
	// we haven't synced yet
	s.gsWaitForSync.Add(1)
	s.workerqueue = workerqueue.NewWorkerQueue(
		s.syncGameServer,
		s.logger,
		logfields.GameServerKey,
		strings.Join([]string{agones.GroupName, s.namespace, s.gameServerName}, "."))

	s.logger.Info("Created GameServer sidecar")
```
That was the reason why tests timed out I assume.

**Comment by aLekSer** [comment]
`make run-sdk-conformance-test-go` has failed:
```
{"message":"shutting down sdk server","severity":"info","source":"main","time":"2020-07-07T17:58:17.187393909Z"}
{"message":"Could not find a request which was expected","request":"ready","sdkName":"go","severity":"error","source":"*sdkserver.LocalSDKServer","time":"2020-07-07T17:58:17.187592429Z"}
{"expected":["ready","allocate","setlabel","setannotation","gameserver","health","shutdown","watch","reserve"],"message":"Testing Failed","received":[],"sdkName":"go","severity":"info","source":"*sdkserver.LocalSDKServer","time":"2020-07-07T17:58:17.187693398Z"}
includes/sdk.mk:145: recipe for target 'run-sdk-conformance-no-build' failed
make[2]: *** [run-sdk-conformance-no-build] Error 1
includes/sdk.mk:152: recipe for target 'run-sdk-conformance-test' failed
make[1]: *** [run-sdk-conformance-test] Error 2
includes/sdk.mk:162: recipe for target 'run-sdk-conformance-test-go' failed
make: *** [run-sdk-conformance-test-go] Error 2
make: *** Waiting for unfinished jobs....
sdk-client-test.go:39: Client is starting
sdk-client-test.go:40: Feature Flags: ContainerPortAllocation=true&Example=true&PlayerTracking=false&SDKWatchSendOnExecute=false
{"message":"shutting down sdk server","severity":"info","source":"main","time":"2020-07-07T17:58:34.030045889Z"}
{"message":"Received requests match expected list. Test run was successful","sdkName":"node","severity":"info","source":"*sdkserver.LocalSDKServer","time":"2020-07-07T17:58:34.030251503Z"}
{"error":"http: Server closed","message":"http server closed","severity":"info","source":"main","time":"2020-07-07T17:58:34.030616387Z"}
sdk-client-test.go:44: Could not connect to sdk: could not connect to localhost:9001: context deadline exceeded
exit status 1
make[3]: *** [run-sdk-command] Error 1
``
