### PR TITLE
Flaky Test: TestGameServerAllocationReturnLabels

### LINKED ISSUE #4431: Flaky Test: TestGameServerAllocationReturnLabels
## Description

`TestGameServerAllocationReturnLabels` is flaky and fails intermittently in e2e tests on GKE Autopilot with a nil pointer dereference panic.

## Environment

- Cluster: `gke-autopilot-1.34`
- Test step: `e2e-stable`
- Build: https://console.cloud.google.com/cloud-build/builds/91967d42-0fee-4ba1-bafc-f4d80eae18f1;step=2?project=agones-images

## Error

```
--- FAIL: TestGameServerAllocationReturnLabels (112.92s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered, repanicked]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c336c3]

goroutine 643 [running]:
testing.tRunner.func1.2({0x2f40480, 0x4948e50})
	/usr/local/go/src/testing/testing.go:1872 +0x419
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1875 +0x683
panic({0x2f40480?, 0x4948e50?})
	/usr/local/go/src/runtime/panic.go:783 +0x132
agones.dev/agones/test/e2e.TestGameServerAllocationReturnLabels(0xc00055cc40)
	/go/src/agones.dev/agones/test/e2e/gameserverallocation_test.go:1368 +0x983
testing.tRunner(0xc00055cc40, 0x33b6ed8)
	/usr/local/go/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1997 +0x9d3
```

## Root Cause Analysis

The panic occurs at `test/e2e/gameserverallocation_test.go:1368`:
```go
assert.Equal(t, t.Name(), gsa.Status.Metadata.Labels[role])
```

The test creates a Fleet with 1 replica and waits for it to become Ready via `AssertFleetCondition`. However, on GKE Autopilot, node provisioning can be slow due to scale-from-zero behavior. From the logs, the Fleet spent approximately **110 seconds** (from 19:50:41 to 19:52:30) waiting for `ReadyReplicas` to go from 0 to 1.

The logs show the Fleet stuck at `ReadyReplicas:0` while `Replicas:1` for an extended period:
```
time="2026-01-24 19:50:42.290" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x7qjj fleetStatus="{Replicas:1 ReadyReplicas:0 ...}"
...
time="2026-01-24 19:52:27.056" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x7qjj fleetStatus="{Replicas:1 ReadyReplicas:0 ...}"
time="2026-01-24 19:52:30.251" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x7qjj fleetStatus="{Replicas:1 ReadyReplicas:1 ...}"
```

When `AssertFleetCondition` eventually passes (or times out), if the allocation happens when no GameServers are actually Ready, the allocation returns an `UnAllocated` state. In this state, `gsa.Status.Metadata` is nil, causing the panic when the test tries to access `gsa.Status.Metadata.Labels`.

## Observations

- The same test **passed** in Step #1 (`e2e-feature-gates`) but **failed** in Step #2 (`e2e-stable`)
- This suggests timing-dependent flakiness related to cluster state and node availability
- The panic caused subsequent tests to also fail with `-1.00s` duration (test runner aborted)

## Suggested Fix

The test should verify that `gsa.Status.State == GameServerAllocationAllocated` before attempting to access `gsa.Status.Metadata`. The current code uses `assert.Equal` which doesn't prevent subsequent code from running:

```go
assert.Equal(t, allocationv1.GameServerAllocationAllocated, gsa.Status.State)  // line 1367
assert.Equal(t, t.Name(), gsa.Status.Metadata.Labels[role])  // line 1368 - panics if State != Allocated
```

Should be changed to use `require.Equal` for the state check, or add a nil check:

```go
require.Equal(t, allocationv1.GameServerAllocationAllocated, gsa.Status.State)
// Now safe to access gsa.Status.Metadata
```

Or add explicit nil check:
```go
assert.Equal(t, allocationv1.GameServerAllocationAllocated, gsa.Status.State)
require.NotNil(t, gsa.Status.Metadata, "allocation metadata should not be nil for allocated state")
assert.Equal(t, t.Name(), gsa.Status.Metadata.Labels[role])
```

### PR DESCRIPTION
**Pull request by Sivasankaran25**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #4431

**Special notes for your reviewer**:

### CODE REVIEW

File: test/e2e/gameserverallocation_test.go [hunk 1]
```diff
@@ -1363,8 +1363,8 @@ func TestGameServerAllocationReturnLabels(t *testing.T) {
 
 	gsa, err = framework.AgonesClient.AllocationV1().GameServerAllocations(framework.Namespace).Create(ctx, gsa.DeepCopy(), metav1.CreateOptions{})
 	require.NoError(t, err)
-
 	assert.Equal(t, allocationv1.GameServerAllocationAllocated, gsa.Status.State)
+	require.NotNil(t, gsa.Status.Metadata, "allocation metadata should not be nil for allocated state")
```
Comment (markmandel) [inline test/e2e/gameserverallocation_test.go]: So this stops the panic, but doesn't fix the actual flake. Take a look at the original log for more details.

File: test/e2e/gameserverallocation_test.go [hunk 2]
```diff
@@ -1348,29 +1348,47 @@ func TestGameServerAllocationReturnLabels(t *testing.T) {
 	flt.Spec.Replicas = 1
 	flt.Spec.Template.ObjectMeta.Labels = label
 	flt.Spec.Template.ObjectMeta.Annotations = annotations
+
 	flt, err := fleets.Create(ctx, flt, metav1.CreateOptions{})
-	defer fleets.Delete(ctx, flt.ObjectMeta.Name, metav1.DeleteOptions{}) // nolint:errcheck
+	defer fleets.Delete(ctx, flt.ObjectMeta.Name, metav1.DeleteOptions{}) // nolint
```
Comment (markmandel) [inline test/e2e/gameserverallocation_test.go]: PR #4435 Review: Does it fix Issue #4431?

  The Issue (Summary)

  Issue #4431 reports that TestGameServerAllocationReturnLabels is flaky on GKE Autopilot. Two distinct problems:

  1. Panic (immediate symptom): When allocation returns UnAllocated (because no GameServer is Ready), gsa.Status.Metadata is nil. The original code used assert.Equal (non-fatal) to check the allocation state at line 1367, so execution continued to line 1368 where gsa.Status.Metadata.Labels[role] caused a nil
  pointer dereference panic.
  2. Root flakiness: On GKE Autopilot, node provisioning can take 110+ seconds (scale-from-zero). Even after AssertFleetCondition passes, a race can cause the allocation to return UnAllocated if timing is tight.

  What the PR Does

  1. Changes assert.Equal → require.Equal for the allocation state check — stops execution immediately if allocation didn't succeed, preventing the panic.
  2. Adds require.NotEmpty(t, gsa.Status.GameServerName) as a guard.
  3. Removes all assertions on gsa.Status.Metadata.Labels and gsa.Status.Metadata.Annotations (the GSA response metadata).
  4. Replaces them with a require.Eventually that polls the GameServer object directly for labels/annotations.

  Assessment

  Fixes the panic: Yes. The require.Equal on the allocation state is the correct fix per the issue's own suggested fix. This prevents the nil pointer dereference.

  Fixes the underlying flake: No. The test will still fail intermittently when the allocation returns UnAllocated on slow clusters — it just fails cleanly at the require.Equal line instead of panicking. The require.Eventually block only runs after a successful allocation, so it doesn't help with the
  allocation-timing flake.

  Regresses test coverage: Yes. The test is named TestGameServerAllocationReturnLabels — its purpose is to verify that the allocation response carries back the correct labels/annotations in gsa.Status.Metadata. The PR removes those checks entirely and only verifies labels on the GameServer object itself. This is
  testing a different thing (that the GS has labels, not that the allocation response returns them).

  The require.Eventually is unnecessary for its purpose. After a successful allocation, the GameServer's ObjectMeta.Labels and Annotations were set at creation time from the Fleet template — they don't need polling. The original reviewer (@markmandel) flagged this concern in the review comment: "So this stops the
  panic, but doesn't fix the actual flake." (though that was on an earlier revision, the core issue remains).

  What a complete fix would look like

  1. Keep require.Equal for the allocation state check (as the PR does) — fixes the panic.
  2. Restore the gsa.Status.Metadata assertions (since the test's purpose is to verify returned labels), protected by the require.Equal gate which now ensures Metadata is non-nil.
  3. To fix the underlying flake, either retry the allocation itself in a require.Eventually loop, or accept that this specific timing issue on Autopilot is a known environment constraint.

  Verdict

  The PR partially fixes issue #4431. It prevents the panic (the immediate symptom) but does not fix the underlying flakiness, and it loses the original test's intended coverage of GSA response metadata.

File: test/e2e/gameserverallocation_test.go [hunk 3]
```diff
@@ -1348,29 +1348,47 @@ func TestGameServerAllocationReturnLabels(t *testing.T) {
...
-	assert.Equal(t, t.Name(), gsa.Status.Metadata.Labels[role])
-	assert.Equal(t, flt.ObjectMeta.Name, gsa.Status.Metadata.Labels[agonesv1.FleetNameLabel])
-	assert.Equal(t, annotationValue, gsa.Status.Metadata.Annotations[annotationKey])
-	gs, err := gameServers.Get(ctx, gsa.Status.GameServerName, metav1.GetOptions{})
-	require.NoError(t, err)
-	assert.Equal(t, flt.ObjectMeta.Name, gs.ObjectMeta.Labels[agonesv1.FleetNameLabel])
+	require.Equal(t, allocationv1.GameServerAllocationAllocated, gsa.Status.State)
+	require.NotEmpty(t, gsa.Status.GameServerName)
+
+	require.Eventually(t, func() bool {
```
Comment (markmandel) [inline test/e2e/gameserverallocation_test.go]: I recently found https://pkg.go.dev/github.com/stretchr/testify@v1.11.1/require#EventuallyWithT - which for more complicated test conditions is definitely a better option for sure.

Then we can maintain the checks for labels and annotations, and have them reported in a way that's easier to read.

File: test/e2e/gameserverallocation_test.go [hunk 4]
```diff
@@ -1348,29 +1348,47 @@ func TestGameServerAllocationReturnLabels(t *testing.T) {
...
 			},
-		}}
+		},
+	}
 
-	gsa, err = framework.AgonesClient.AllocationV1().GameServerAllocations(framework.Namespace).Create(ctx, gsa.DeepCopy(), metav1.CreateOptions{})
+	gsa, err = framework.AgonesClient.
+		AllocationV1().
+		GameServerAllocations(framework.Namespace).
+		Create(ctx, gsa.DeepCopy(), metav1.CreateOptions{})
```
Comment (markmandel) [inline test/e2e/gameserverallocation_test.go]: Does this fix the flake where this comes back with an Unallocated state? Should the eventually be wrapping the allocation call?

**Review by markmandel — COMMENTED** [review]
I think this is heading in the right direction, but isn't quite there yet.

File: test/e2e/gameserverallocation_test.go [hunk 5]
```diff
@@ -1348,29 +1348,49 @@ func TestGameServerAllocationReturnLabels(t *testing.T) {
...
+		},
+	}
 
-	gsa, err = framework.AgonesClient.AllocationV1().GameServerAllocations(framework.Namespace).Create(ctx, gsa.DeepCopy(), metav1.CreateOptions{})
-	require.NoError(t, err)
+	require.EventuallyWithT(t, func(c *assert.CollectT) {
+		currGsa, err := framework.AgonesClient.AllocationV1().GameServerAllocations(framework.Namespace).Create(ctx, gsa.DeepCopy(), metav1.CreateOptions{})
+		if !assert.NoError(c, err, "API call to allocate should not fail") {
+			return
+		}
```
Comment (markmandel) [inline test/e2e/gameserverallocation_test.go]:
```suggestion
		require.NoError(c, err, "API call to allocate should not fail")
```

No reason for the `if` conditional if you want to fail fast - that's what `requires` is for.

Same for all the others below.

File: test/e2e/gameserverallocation_test.go [hunk 6]
```diff
@@ -1348,29 +1348,49 @@ func TestGameServerAllocationReturnLabels(t *testing.T) {
...
+		if !assert.NotEmpty(c, currGsa.Status.GameServerName, "Allocated GS name should not be empty") {
+			return
+		}
+		gs, err := gameServers.Get(ctx, currGsa.Status.GameServerName, metav1.GetOptions{})
+		if !assert.NoError(c, err, "Should be able to get the allocated GameServer") {
+			return
+		}
 
-	assert.Equal(t, allocationv1.GameServerAllocationAllocated, gsa.Status.State)
```
Comment (markmandel) [inline test/e2e/gameserverallocation_test.go:1367]: we lost all these assertions on the GameServerAllocation -- which is the point of the test, to make sure that labels and annotations are passed back to the allocation. These should still be in there.

File: test/e2e/gameserverallocation_test.go [hunk 7]
```diff
@@ -1348,29 +1348,43 @@ func TestGameServerAllocationReturnLabels(t *testing.T) {
...
-	assert.Equal(t, t.Name(), gsa.Status.Metadata.Labels[role])
-	assert.Equal(t, flt.ObjectMeta.Name, gsa.Status.Metadata.Labels[agonesv1.FleetNameLabel])
-	assert.Equal(t, annotationValue, gsa.Status.Metadata.Annotations[annotationKey])
-	gs, err := gameServers.Get(ctx, gsa.Status.GameServerName, metav1.GetOptions{})
-	require.NoError(t, err)
-	assert.Equal(t, flt.ObjectMeta.Name, gs.ObjectMeta.Labels[agonesv1.FleetNameLabel])
+		require.NoError(c, err, "API call to allocate should not fail")
+		require.Equal(c, allocationv1.GameServerAllocationAllocated, currGsa.Status.State, "Allocation should be 'Allocated' state")
```
Comment (markmandel) [inline test/e2e/gameserverallocation_test.go:1377]: The original code asserted against gsa.Status.Metadata (the allocation's returned metadata):
```go
  assert.Equal(t, t.Name(), gsa.Status.Metadata.Labels[role])
  assert.Equal(t, flt.ObjectMeta.Name, gsa.Status.Metadata.Labels[agonesv1.FleetNameLabel])
  assert.Equal(t, annotationValue, gsa.Status.Metadata.Annotations[annotationKey])
```

  The new code instead checks gs.ObjectMeta (the underlying GameServer's own metadata):

```go
  require.Equal(c, t.Name(), gs.ObjectMeta.Labels[role], ...)
  require.Equal(c, flt.ObjectMeta.Name, gs.ObjectMeta.Labels[agonesv1.FleetNameLabel], ...)
  require.Equal(c, annotationValue, gs.ObjectMeta.Annotations[annotationKey], ...)
```

  The point of the test is to verify that labels/annotations are returned in the allocation response (Status.Metadata), not just that they exist on the GameServer itself.
  Those are subtly different things. The assertions on currGsa.Status.Metadata are still missing

**Comment by markmandel** [comment]
@Sivasankaran25 this is good to go. Can you implement DCO on your commits please?

You may want to rebase down to a single commit - but I'll let you decide. There are instructions in the DCO checker as well on how to implement DCO. (`git commit -s`)

I also fixed the conflicts 👍🏻 

Thanks!

**Comment by markmandel** [comment]
Flake in gopkg.in

**Comment by markmandel** [comment]
```
Uninstalling problematic Agones release in failed state: Release "agones" failed: resource Service/agones-system/agones-ping-udp-service not ready. status: Terminating, message: Resource scheduled for deletion
context deadline exceeded...
Error: uninstallation completed with 1 error(s): context deadline exceeded
\
	helm upgrade --install --atomic --wait --timeout 10m --namespace=agones-system \
	--create-namespace \
	--set agones.image.tag=1.57.0-dev-33f3dae,agones.image.registry="us-docker.pkg.dev/agones-images/ci" \
	--set agones.image.controller.pullPolicy="Always",agones.image.controller.pullSecret= \
	--set agones.image.extensions.pullPolicy="Always",agones.image.allocator.pullPolicy="Always" \
	--set agones.image.ping.pullPolicy="Always",agones.image.sdk.alwaysPull=true \
	--set agones.ping.http.serviceType="LoadBalancer",agones.ping.udp.serviceType="LoadBalancer" \
	--set agones.allocator.service.serviceType="LoadBalancer" \
	--set agones.controller.logLevel="debug" \
	--set agones.crds.cleanupOnDelete=true \
	--set agones.featureGates="PlayerAllocationFilter=true&FleetAutoscaleRequestMetaData=false&PlayerTracking=true&CountsAndLists=false&RollingUpdateFix=false&PortRanges=false&PortPolicyNone=false&ScheduledAutoscaler=false&GKEAutopilotExtendedDurationPods=false&SidecarContainers=false&WasmAutoscaler=true&Example=true" \
	--set agones.allocator.service.loadBalancerIP=35.240.72.5 \
	--set agones.metrics.serviceMonitor.enabled=false \
	 \
	agones /go/src/agones.dev/agones/install/helm/agones/
Release "agones" does not exist. Installing it now.
Error: release agones failed, and has been uninstalled due to atomic being set: context deadline exceeded
make: *** [Makefile:451: install] Error 1
```
Something weird happening on generic-1.34 - going to try percussive maintenance.

/gcbrun
