### PR TITLE
fix: rollout strategy issues

### LINKED ISSUE #3688: MaxSurge and MinAvailable calculated incorrectly
**What happened**:

We see a very sharp decline in `Ready` GameServers when rolling over to a new GameServerSet, leading to having no `Ready` GameServers in the pool while the new version is stuck in `Scheduled` due to the nodes downloading images.

**What you expected to happen**:

A smooth rollout with `Ready` GameServers always available.

**How to reproduce it (as minimally and precisely as possible)**:

When we investigated this, it seems there is a difference between what the docs say here: https://agones.dev/site/docs/guides/fleet-updates/#rolling-update-strategy

> By default, a Fleet will wait for new GameSevers to become Ready during a Rolling Update before continuing to shutdown additional GameServers, only counting GameServers that are Ready as being available when calculating the current maxUnavailable value which controls the rate at which GameServers are updated.

and what we see in the calculation for `MinAvailable`:

https://github.com/googleforgames/agones/blob/main/pkg/fleets/controller.go#L555

It also stands to reason the `MaxSurge` is calculated in relation to how `MinAvailable` is, and should probably not be based on `fleet.Spec.Replicas` either.

With some real world numbers from one of our clusters, we have:

Replicas: 3.46K
ReadyReplicas: 194
AllocatedReplicas: 3.22K
MaxSurge: 10%
MinAvailable: 10%

With the current calculation it is allowed to terminate 346 GameServers in the first round, but we only have 194 `Ready`, so all `Ready` GameServers are terminated. Were this based on `Ready` GameServers, it would be allowed to terminate 19, which is a rather large difference.

**Anything else we need to know?**:

Another thing that struck me as odd in the calculation is `cleanupUnhealthyReplicas`:

https://github.com/googleforgames/agones/blob/main/pkg/fleets/controller.go#L529

This seems to consider everything that is not `Ready` as unhealthy but seems to ignore `Allocated` which strikes me as wrong.

It might also be a good idea to set `Replicas` to 0 on a non-active GameServerSet when `Allocated` == `Replicas`.

**Environment**:
- Agones version: 1.37.0
- Kubernetes version (use `kubectl version`): 1.27.3-gke.100
- Cloud provider or hardware configuration: GKE n2-custom-40-163840
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

### PR DESCRIPTION
**Pull request by nrwiersma**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
/kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

This PR fixes issues with the fleet rollout strategy that have been observed in production. It seems in clusters that are massively allocation heavy, rollout does not behave as expected or as documented. These patches have been confirmed to work in out production environment, using a custom build.

Each issue is in a separate commit, to allow them to be evaluated individually.

**Which issue(s) this PR fixes**:

Closes #3688

**Special notes for your reviewer**:

Additional to the 2 bug fixes (first 2 commits), we observe that once an inactive GSS gets to the point of Allocated == Replicas, it is still possible for it to spawn GSes, if the new GS comes up fast enough and there is enough churn in the controller. Once this point is reached, there is no real reason for the GSS to have Spec Replicas, but rather it would be better for it to get its Spec Replicas set to 0 and be allowed to loose it allocations until it is cleaned up. This patch makes up the last commit.

### CODE REVIEW

File: pkg/fleets/controller.go [hunk 1]
```diff
@@ -514,19 +514,21 @@ func (c *Controller) cleanupUnhealthyReplicas(ctx context.Context, rest []*agone
 	// Safely scale down all old GameServerSets with unhealthy replicas.
 	totalScaledDown := int32(0)
 	for i, gsSet := range rest {
+		healthy := gsSet.Status.ReadyReplicas + gsSet.Status.AllocatedReplicas + gsSet.Status.ReservedReplicas
```
Comment (markmandel) [inline pkg/fleets/controller.go:517]: Thanks for digging into this so deeply!

I probably need to sit down and play with this to see it in effect, but I would definitely want this to sit behind a feature gate, so it can be widely tested without fear of breaking things.

To do that, my suggestion would be is duplicate the entirety of `cleanupUnhealthyReplicas` and `rollingUpdateRestFixedOnReady` with new names, e.g. "cleanupUnhealthyReplicasRollingUpdateFix` (or something similar).

(Maybe in a new file, if the controller is getting messy)

Then we could do something akin to the following:

```go
func (c *Controller) cleanupUnhealthyReplicas(ctx context.Context, rest []*agonesv1.GameServerSet,
	fleet *agonesv1.Fleet, maxCleanupCount int32) ([]*agonesv1.GameServerSet, int32, error) {

  if runtime.FeatureEnabled(runtime.FeatureRollingUpdateFix) {
    return cleanupUnhealthyReplicasRollingUpdateFix(ctx, rest, fleet, maxCleanupCount)
  }

// ....
}
```

And we could turn on/off feature flags and so we could have relavent unit tests as well.

How does that sound?

**Review by markmandel — COMMENTED** [review]
I have some suggestions for how to feature gate this change.

Is there a e2e type scenario (akin to what we see in #3438) you can think of that would highlight the issues you were running into - that would also mean we don't run into it again in the future.

File: pkg/fleets/controller.go (hunk 1 above)
Comment (nrwiersma) [reply pkg/fleets/controller.go:517]: Sure, as you wish.

Comment (nrwiersma) [reply pkg/fleets/controller.go]: I have managed to prove the primary tenants of the fix in unit tests, which is much simpler than e2e.

As a side note, `TestControllerRollingUpdateDeployment` seems to break the laws under with GSS Status Replicas exists, but I left the original math unchanged.

**Comment by markmandel** [comment]
Thanks for making these changes - I'm probably going to opt to let this one slide past the next release on Tuesday, and give me (someone? :smile) some time to sit down with this, and make sure everything is good (which really means running some rolling updates and watching them happen 😄 )

**Comment by nrwiersma** [comment]
We have production data of this patch if that would help.

**Comment by markmandel** [comment]
> We have production data of this patch if that would help.

TBH - totally trust that you do. I just want to know that I've spent some time with this as an extra verification step, and give it time to back between releases as well.

**Comment by markmandel** [comment]
Just a heads up - will take this for a spin this week 👍🏻

File: site/content/en/docs/Guides/feature-stages.md [hunk 2]
```diff
@@ -31,6 +31,7 @@ The current set of `alpha` and `beta` feature gates:
 | [Support for Extended Duration Pods on GKE Autopilot (*1.28+ only*)](https://github.com/googleforgames/agones/issues/3386)  | `GKEAutopilotExtendedDurationPods` | Disabled | `Alpha` | 1.37.0 |
 | [GameServer player capacity filtering on GameServerAllocations](https://github.com/googleforgames/agones/issues/1239)       | `PlayerAllocationFilter`           | Disabled | `Alpha` | 1.14.0 |
 | [Player Tracking]({{< ref "/docs/Guides/player-tracking.md" >}})                                                            | `PlayerTracking`                   | Disabled | `Alpha` | 1.6.0  |
+| [Rolling Update Fixes](https://github.com/googleforgames/agones/issues/3688)                                                | `RollingUpdateFix`                 | Disabled | `Alpha` | 1.41.0 |
```
Comment (markmandel) [inline site/content/en/docs/Guides/feature-stages.md:34]: Small thing, can you make a copy of this table, one with the new feature and one without, and use the `feature` shortcodes to keep this feature flag hidden until the next release please.

See: https://agones.dev/site/docs/contribute/#within-a-page for details

**Review by markmandel — APPROVED** [review]
Finally took this for a spin, basically just wanted to see it in action - look great, let's go ahead with it!

(Rolling update on a Fleet of 50 gameservers)
Peek 2024-05-02 09-50
