### PR TITLE
Return HTTP 201 on GameServerAllocation

### LINKED ISSUE #2108: Creating a GameServerAllocation returns a 200 Ok instead of a 201 Created
**What happened**: I use the kubernetes c# client to create a GameServerAllocation. I received an exception with the message ""Operation returned an invalid status code 'OK'". 
Using kubectl, I can see that the GameServerAllocation was indeed created. 

**What you expected to happen**: I expect the c# client not to throw an exception. 

**How to reproduce it (as minimally and precisely as possible)**: Create a GameServerAllocation with the official kubernetes c# client, use the `CreateNamespacedCustomObjectWithHttpMessagesAsync` to get the exception. Also, you can use any other client and check the http status code response. 

**Anything else we need to know?**: It seems that the c# client only accepts a `201 Created` status back from Agones, instead a `200 Ok` is sent. It seems that the go client, for instance, is more forgiving for this. 

**Environment**:
- Agones version: 1.14.0
- Kubernetes version (use `kubectl version`): 1.18.14
- Cloud provider or hardware configuration: Azure
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s):
- Others:

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

The standard for CRD creation is to return a HTTP 201 response. The Go client is more flexible and was happy with a 200 response, but the C# client will error out if anything but a 201 response.

This fixes things so we send the correct HTTP response code when creating a GameServerAllocation.

**Which issue(s) this PR fixes**:

Closes #2108

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Comment by markmandel** [comment]
Testing with `kubectl` as well:


```
$ kubectl -v 9 create -f ./examples/simple-game-server/gameserverallocation.yaml -o yaml
....
I0526 20:22:28.749263    1257 request.go:1068] Request Body: {"apiVersion":"allocation.agones.dev/v1","kind":"GameServerAllocation","metadata":{"namespace":"default"},"spec":{"required":{"matchLabels":{"agones.dev/fleet":"simple-game-server"}}}}
I0526 20:22:28.749302    1257 round_trippers.go:424] curl -k -v -XPOST  -H "Content-Type: application/json" -H "User-Agent: kubectl/v1.18.15 (linux/amd64) kubernetes/73dd5c8" -H "Accept: application/json" 'https://34.83.43.189/apis/allocation.agones.dev/v1/namespaces/default/gameserverallocations'
I0526 20:22:28.911903    1257 round_trippers.go:444] POST https://34.83.43.189/apis/allocation.agones.dev/v1/namespaces/default/gameserverallocations 201 Created in 162 milliseconds
```

You can see the 201 on the last line 🥳

File: pkg/gameserverallocations/controller.go [hunk 1]
```diff
@@ -133,11 +133,17 @@ func (c *Controller) processAllocationRequest(ctx context.Context, w http.Respon
...
-	if status, ok := result.(*metav1.Status); ok {
-		w.WriteHeader(int(status.Code))
+	var code int
+	switch obj := result.(type) {
+	case *metav1.Status:
+		code = int(obj.Code)
+	case *allocationv1.GameServerAllocation:
+		code = http.StatusCreated
+	default:
+		code = 200
```
Comment (roberthbailey) [inline pkg/gameserverallocations/controller.go:143]: It looks like the old behavior was to not set a code in the header at all unless the result was a metav1.Status whereas now we always set a code in the header. Is it better to only set the code when necessary, and not send any code at all for a successful response?

Comment (markmandel) [reply pkg/gameserverallocations/controller.go]: There are probably a few things here, which are fun ways in which golang handles headers, that I found along the way.

1. This likely solves a bug that nobody ran into. Which is, when we previously set the `WriteHeader` in the current version, since we're writing the client at this point, it kicks the encoding type to `text/plain` - even though, no matter what we want `application/json` for all things (and we set it later in the code logic, but it will be ignored). This will cause all the k8s clients and `kubectl` to just fail. I found this out the hard way when implementing this fix.
2. If you don't set a HTTP status code header - then by default, Go will make it 200 on first write to the client. So you end up in the same place as you would do normally, but in this case it's now explicit rather than implicit.

Although a good point is - I shouldn't have it as "200" - I should use `http.StatusOK`. I'll make that change now.

Comment (roberthbailey) [reply pkg/gameserverallocations/controller.go]: Thanks for the explanation.

File: pkg/gameserverallocations/controller_test.go [hunk 2]
```diff
@@ -103,6 +103,7 @@ func TestControllerAllocator(t *testing.T) {
 			rec := httptest.NewRecorder()
 			err = c.processAllocationRequest(ctx, rec, r, "default")
 			assert.NoError(t, err)
+			assert.Equal(t, http.StatusCreated, rec.Code)
```
Comment (roberthbailey) [inline pkg/gameserverallocations/controller_test.go:106]: We shouldn't block this bug fix merging, but it seems like we have a test that covers the other two case statements (using the metav1 status and returning a `http.StatusOK`).

**Review by roberthbailey — APPROVED** [review]
