### PR TITLE
Fix wrong condition check for Memory limit

### LINKED ISSUE #1419: No validation when helm parameter `agones.image.sdk.cpuRequest` set less than `cpuLimit`
Similar to what we have in #1298 if we set cpuRequest < cpuLimits then no pods for GameServers could be created.

**What happened**:
Helm allows to set `agones.image.sdk` parameters which does not correlate to each other.

**What you expected to happen**:
There should be an error on `helm install` step.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ helm install ./install/helm/agones --namespace agones-system --name agones --set agones.image.tag=1.5.0-7791336 --set agones.image.sdk.cpuRequest=64Mi --set $ agones.image.sdk.cpuLimit=62Mi
$ kubectl apply -f ./examples/simple-udp/fleet.yaml
$ kubectl get gs
NAME                     STATE            ADDRESS   PORT   NODE   AGE
simple-udp-2b5l4-48lvp   Creating                                 0s
simple-udp-2b5l4-6pwzs   PortAllocation                           0s
simple-udp-2b5l4-ltjll   Shutdown                                 0s
simple-udp-2b5l4-trdtz   Error                                    0s
simple-udp-2b5l4-wxp2w   Shutdown                                 0s 
$ kubectl describe gss
...
                                       
  Normal  SuccessfulCreate  36s (x5 over 36s)  gameserverset-controller  (combined from similar events): Created gameserver: simple-udp-2b5l4-ccpkx                                                      
  Normal  SuccessfulDelete  36s                gameserverset-controller  Deleted gameserver in state Unhealthy: simple-udp-2b5l4-hcmfw                                                                   
  Normal  SuccessfulDelete  36s                gameserverset-controller  Deleted gameserver in state Unhealthy: simple-udp-2b5l4-pqj7r                                                                   
  Normal  SuccessfulDelete  36s (x2 over 36s)  gameserverset-controller  (combined from similar events): Deleted gameserver in state Unhealthy: simple-udp-2b5l4-rj4hs    
```

**Anything else we need to know?**:
Similar issue with memoryRequest and memoryLimit parameters .

**Environment**:
- Agones version: 1.4
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

### PR DESCRIPTION
**Pull request by aLekSer**
This is needed to start writing validation for these new limits as well as CPU ones.

Closes #1419.

### CODE REVIEW

File: pkg/gameservers/controller.go [hunk 1]
```diff
@@ -646,7 +646,7 @@ func (c *Controller) sidecar(gs *agonesv1.GameServer) corev1.Container {
 	if !c.sidecarCPULimit.IsZero() {
 		limits[corev1.ResourceCPU] = c.sidecarCPULimit
 	}
-	if !c.sidecarCPULimit.IsZero() {
+	if !c.sidecarMemoryLimit.IsZero() {
 		limits[corev1.ResourceMemory] = c.sidecarMemoryLimit
```
Comment (markmandel) [inline pkg/gameservers/controller.go]: Since we're here, do we want to put in some `logrus.Warnf()` log messages for both of these -- otherwise they fail silently.

WDYT?

Comment (aLekSer) [reply pkg/gameservers/controller.go]: Will update this

Comment (aLekSer) [reply pkg/gameservers/controller.go]: What Warn message should I add?
Similar to this one:
QoS would not be assigned to "Guaranteed" unless CPU and Memory are the same in Limit and Request for the sidecar?

Comment (markmandel) [reply pkg/gameservers/controller.go]: Something like:
```
	if !c.sidecarMemoryLimit.IsZero() {
		limits[corev1.ResourceMemory] = c.sidecarMemoryLimit
       } else {
             c.logger.Warnf("Sidecar memory limit of %s is less than or equal to zero. Skipping.", c.sidecarMemoryLimit)
       }
```

I was thinking something more like that? 

I feel like if people are changing memory and cpu limits, then they know what they are doing, and it's up to them to control it as they see fit. But a 0 or negative value isn't going to work, so we should warn people that we are skipping setting the value.

Sound good?

Comment (aLekSer) [reply pkg/gameservers/controller.go]: Mark thanks for this request, I have added validation on the place where we set those parameters, not where we use them.
So we will close #1419 issue.

File: pkg/apis/agones/v1/gameserver.go [hunk 2]
```diff
@@ -456,6 +457,24 @@ func (gss *GameServerSpec) Validate(devAddress string) ([]metav1.StatusCause, bo
 	return causes, len(causes) == 0
 }
 
+// ValidateResource validates limit or Memory CPU resources used for containers in pods
+// If a GameServer is invalid there will be > 0 values in
+// the returned array
+func ValidateResource(request resource.Quantity, limit resource.Quantity, resourceName corev1.ResourceName) []error {
```
Comment (aLekSer) [inline pkg/apis/agones/v1/gameserver.go]: I have placed ValidateResource() here so we will check PodTemplate in a Fleet and GameServer using exact same function.

File: cmd/controller/main_test.go [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+	assert.Len(t, errs, 2)
+	errorsContainString(t, errs, "Resource cpu request value must be non negative")
+}
+
+func errorsContainString(t *testing.T, errs []error, expected string) {
+	s := ""
+	for _, v := range errs {
+		s += v.Error()
+	}
+	assert.Contains(t, s, expected)
```
Comment (akremsa) [inline cmd/controller/main_test.go]: Is it possible to put assert.Contains inside a for loop and exit once string match found?

**Comment by aLekSer** [comment]
Flaky #1377 .

File: cmd/controller/main.go [hunk 4]
```diff
@@ -382,14 +387,19 @@ type config struct {
 }
 
 // validate ensures the ctlConfig data is valid.
-func (c *config) validate() error {
+func (c *config) validate() []error {
+	validationErrors := make([]error, 0)
 	if c.MinPort <= 0 || c.MaxPort <= 0 {
-		return errors.New("min Port and Max Port values are required")
+		validationErrors = append(validationErrors, errors.New("min Port and Max Port values are required"))
```
Comment (markmandel) [inline cmd/controller/main.go]: Love this. :+1:

File: cmd/controller/main_test.go (hunk 3 above)
Comment (aLekSer) [reply cmd/controller/main_test.go]: Done

File: cmd/controller/main_test.go [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+	errs = c.validate()
+	assert.Len(t, errs, 2)
+	errorsContainString(t, errs, "Resource cpu request value must be non negative")
+}
+
+func errorsContainString(t *testing.T, errs []error, expected string) {
+	found := false
+	for _, v := range errs {
+		if expected == v.Error() {
+			found = true
```
Comment (akremsa) [inline cmd/controller/main_test.go]: We can safely break the loop here because there is no point to check other elements of the slice

Comment (aLekSer) [reply cmd/controller/main_test.go]: Added break
