### PR TITLE
Clone Kubernetes objects in API Server before encoding them

### LINKED ISSUE #2086: Nil Reference/massive log spam in Controller [1.13]
**What happened**:

The controller started to produce this error over and over as fast as it could log (1.64M entries in 20 minutes):

```
2021/04/30 23:46:45 http2: panic serving 172.31.39.241:52498: runtime error: invalid memory address or nil pointer dereference
goroutine 1780371 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc0007a2288, 0xc0017dbf8e, 0xc000ce7980)
        /usr/local/go/src/net/http/h2_bundle.go:5714 +0x16b
panic(0x1767040, 0x2903ca0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
strings.Count(0x0, 0x2, 0x1982a76, 0x1, 0xc000f2e6e0)
        /usr/local/go/src/strings/strings.go:84 +0xf4
k8s.io/apimachinery/pkg/runtime/schema.ParseGroupVersion(0x0, 0x2, 0x8cb061, 0x174f460, 0xc0003faae0, 0xc000f2e768, 0xc0003ce0b8, 0x1857d01)
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/runtime/schema/group_version.go:227 +0x91
k8s.io/apimachinery/pkg/runtime/schema.FromAPIVersionAndKind(0x0, 0x2, 0x1613c13, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/runtime/schema/group_version.go:310 +0x5a
k8s.io/apimachinery/pkg/apis/meta/v1.(*TypeMeta).GroupVersionKind(0xc001040af0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/meta.go:128 +0x5e
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc0017ccf00, 0x1c702c0, 0xc001040af0, 0x7f064da69478, 0xc0007a2288, 0x0, 0x0)
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:217 +0x186
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0017ccf00, 0x1c702c0, 0xc001040af0, 0x7f064da69478, 0xc0007a2288, 0xc00043f840, 0xc0000aea80)
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:184 +0x178
agones.dev/agones/pkg/util/apiserver.(*APIServer).addSerializedHandler.func1(0x1ca1d00, 0xc0007a2288, 0xc0014cf500, 0x45fea0, 0xc0007c02d0)
        /go/src/agones.dev/agones/pkg/util/apiserver/apiserver.go:171 +0x37a
agones.dev/agones/pkg/util/https.ErrorHTTPHandler.func1(0x1ca1d00, 0xc0007a2288, 0xc0014cf500)
        /go/src/agones.dev/agones/pkg/util/https/https.go:52 +0x50
net/http.HandlerFunc.ServeHTTP(0xc000e40ce0, 0x1ca1d00, 0xc0007a2288, 0xc0014cf500)
        /usr/local/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000244440, 0x1ca1d00, 0xc0007a2288, 0xc0014cf500)
        /usr/local/go/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc000372000, 0x1ca1d00, 0xc0007a2288, 0xc0014cf500)
        /usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.initALPNRequest.ServeHTTP(0x1ca5d80, 0xc000aaf8c0, 0xc000699500, 0xc000372000, 0x1ca1d00, 0xc0007a2288, 0xc0014cf500)
        /usr/local/go/src/net/http/server.go:3410 +0x8d
net/http.(*http2serverConn).runHandler(0xc000ce7980, 0xc0007a2288, 0xc0014cf500, 0xc000df4700)
        /usr/local/go/src/net/http/h2_bundle.go:5721 +0x8b
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5455 +0x4e1
```

**What you expected to happen**:

Errors to be cleanly handled or the process to just crash so it can be restarted using normal backoff/alerting of crash (Deleting the pod resolved the issue).

**How to reproduce it (as minimally and precisely as possible)**:

Unknown.

**Anything else we need to know?**: This appears to be a simple Nil check issue but it's unknown as to why it failed.

**Environment**:
- Agones version: 1.13
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: aws
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): No available log (it's in datadog) but it just started with no prior messages.
- Others:

### PR DESCRIPTION
**Pull request by highlyunavailable**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

This works around a race condition present in the encoder for Kubernetes objects, as detailed in [kubernetes #82497](https://github.com/kubernetes/kubernetes/issues/82497).

**Which issue(s) this PR fixes**:
Closes #2086 

**Special notes for your reviewer**:

An shallow copy is used here instead of a mutex since that is the suggested fix in the [Kubernetes PR](https://github.com/kubernetes/kubernetes/pull/101123/files#diff-7ac25bcc6f0498d4ade98f19cfd251d2cb4cdfbe3c21a72eb7ba8eb0b0f4fdd0R648) and I'd rather align with their fix strategy. I've checked for use of this in other places in Agones, but this is the only place we use this specific encoder.

### CODE REVIEW

**Comment by highlyunavailable** [comment]
Random suspicion: I believe this comment may have been a symptom of this bug:

 ```
// not testing for version/kind, seems not to come through. Strange.
// we're not building anything that needs this, so not our issue.
```

**Comment by highlyunavailable** [comment]
E2E test flaked here it looks like:

`time="2021-05-01 19:20:01.756" level=error msg="failed to cleanup e2e namespaces" error="namespaces \"1619896443\" not found"`

File: pkg/util/apiserver/apiserver.go [hunk 1]
```diff
@@ -180,6 +182,16 @@ func (as *APIServer) addSerializedHandler(pattern string, m k8sruntime.Object) {
 	}))
 }
 
+// Copied from https://github.com/kubernetes/kubernetes/pull/101123 until the referenced PR is merged
```
Comment (roberthbailey) [inline pkg/util/apiserver/apiserver.go:185]: nit: Can you put this at the bottom of the comment block so that the comment starts with the method name (to make generated documentation look correct)?

Comment (highlyunavailable) [reply pkg/util/apiserver/apiserver.go]: Done, thanks. Wonder why my linter didn't catch that, it usually does for method docs. Maybe because it's a private method.

Comment (roberthbailey) [reply pkg/util/apiserver/apiserver.go]: Thanks!

**Review by roberthbailey — APPROVED** [review]
