### PR TITLE
fix: delay deleting GameServers in Error state

### LINKED ISSUE #3384: ResourceQuota causes high GameServer churn rate
**What happened**:

We have a set of fleets in a namespace that is constrained by a `ResourceQuota`. The fleet tried to scale past what the `ResourceQuota` would allow. When creating new GameServers, they would go into an `Error` state as the `ResourceQuota` admission would forbid the creation of the Pod. This caused the `GameServerSet` to instantly delete the `GameServer` and create a new one, creating a very fast churn causing a lot of load on Kubernetes and etcd.

**What you expected to happen**:

When the `GameServer` hits an `Error` state, according to the state chart [for GameServers](https://agones.dev/site/docs/reference/gameserver/#gameserver-state-diagram) I would expect the GameServer not to be deleted, or for the `GameServerSet` controller to only recreate these GameServers at a fixed interval, to avoid high GameServer churn rate.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a ResourceQuota with low `Hard` CPU or Memory limit
* Create a Fleet that will exceed those limits.

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.34.0
- Kubernetes version (use `kubectl version`): v1.26.5-gke.270
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
```
{"gs":{"metadata":{"name":"nick-test-kzt87-x4mpx","generateName":"nick-test-kzt87-","namespace":"test","uid":"7a980a9b-ddcb-416a-8bae-dc48a98537c3","resourceVersion":"32720772","generation":2,"creationTimestamp":"2023-09-18T14:04:30Z","labels":{"agones.dev/fleet":"nick-test","agones.dev/gameserverset":"nick-test-kzt87"},"annotations":{"agones.dev/sdk-version":"1.34.0"},"ownerReferences":[{"apiVersion":"agones.dev/v1","kind":"GameServerSet","name":"nick-test-kzt87","uid":"0ee9e358-0bff-42d2-9af2-c5a4322b6a28","controller":true,"blockOwnerDeletion":true}],"finalizers":["agones.dev"],"managedFields":[{"manager":"controller","operation":"Update","apiVersion":"agones.dev/v1","time":"2023-09-18T14:04:30Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:agones.dev/fleet":{},"f:agones.dev/gameserverset":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"0ee9e358-0bff-42d2-9af2-c5a4322b6a28\"}":{}}},"f:spec":{".":{},"f:container":{},"f:health":{},"f:immutableReplicas":{},"f:ports":{},"f:scheduling":{},"f:sdkServer":{},"f:template":{".":{},"f:metadata":{".":{},"f:annotations":{".":{},"f:kubectl.kubernetes.io/default-container":{}},"f:creationTimestamp":{},"f:labels":{".":{},"f:agones.dev/fleet":{}}},"f:spec":{".":{},"f:affinity":{".":{},"f:nodeAffinity":{".":{},"f:requiredDuringSchedulingIgnoredDuringExecution":{}}},"f:containers":{},"f:terminationGracePeriodSeconds":{},"f:tolerations":{}}}},"f:status":{".":{},"f:address":{},"f:addresses":{},"f:immutableReplicas":{},"f:nodeName":{},"f:players":{},"f:ports":{},"f:reservedUntil":{},"f:state":{}}}}]},"spec":{"container":"default","ports":[{"name":"http","portPolicy":"Dynamic","container":"default","containerPort":8080,"hostPort":17791,"protocol":"TCP"}],"health":{"periodSeconds":5,"failureThreshold":3,"initialDelaySeconds":5},"scheduling":"Packed","sdkServer":{"logLevel":"Info","grpcPort":9357,"httpPort":9358},"template":{"metadata":{"creationTimestamp":null,"labels":{"agones.dev/fleet":"nick-test"},"annotations":{"kubectl.kubernetes.io/default-container":"default"}},"spec":{"containers":[{"name":"default","image":"europe-docker.pkg.dev/test/dev/prod/testtest@sha256:4c323ab8c951bc63649e62ea95dec08736eef36ca388b1d7e9857fe2df008072","resources":{"requests":{"cpu":"250","memory":"100Gi"}},"imagePullPolicy":"IfNotPresent"}],"terminationGracePeriodSeconds":30,"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"game-server","operator":"Exists"}]}]}}},"tolerations":[{"key":"game-server","operator":"Equal","value":"true","effect":"NoExecute"}]}},"eviction":{"safe":"Never"}},"status":{"state":"Creating","ports":null,"address":"","addresses":null,"nodeName":"","reservedUntil":null,"players":null,"eviction":{"safe":"Never"}}},"gsKey":"test/nick-test-kzt87-x4mpx","message":"Pod created is forbidden","pod":{"metadata":{"creationTimestamp":null},"spec":{"containers":null},"status":{}},"severity":"error","source":"*gameservers.Controller","time":"2023-09-18T14:04:30.434315602Z"}
{"gs":{"metadata":{"name":"nick-test-kzt87-2dzzr","generateName":"nick-test-kzt87-","namespace":"test","uid":"d660c8c1-df28-4e4b-95ab-b97e25842458","resourceVersion":"32720784","generation":2,"creationTimestamp":"2023-09-18T14:04:30Z","labels":{"agones.dev/fleet":"nick-test","agones.dev/gameserverset":"nick-test-kzt87"},"annotations":{"agones.dev/sdk-version":"1.34.0"},"ownerReferences":[{"apiVersion":"agones.dev/v1","kind":"GameServerSet","name":"nick-test-kzt87","uid":"0ee9e358-0bff-42d2-9af2-c5a4322b6a28","controller":true,"blockOwnerDeletion":true}],"finalizers":["agones.dev"],"managedFields":[{"manager":"controller","operation":"Update","apiVersion":"agones.dev/v1","time":"2023-09-18T14:04:30Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:agones.dev/fleet":{},"f:agones.dev/gameserverset":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"0ee9e358-0bff-42d2-9af2-c5a4322b6a28\"}":{}}},"f:spec":{".":{},"f:container":{},"f:health":{},"f:immutableReplicas":{},"f:ports":{},"f:scheduling":{},"f:sdkServer":{},"f:template":{".":{},"f:metadata":{".":{},"f:annotations":{".":{},"f:kubectl.kubernetes.io/default-container":{}},"f:creationTimestamp":{},"f:labels":{".":{},"f:agones.dev/fleet":{}}},"f:spec":{".":{},"f:affinity":{".":{},"f:nodeAffinity":{".":{},"f:requiredDuringSchedulingIgnoredDuringExecution":{}}},"f:containers":{},"f:terminationGracePeriodSeconds":{},"f:tolerations":{}}}},"f:status":{".":{},"f:address":{},"f:addresses":{},"f:immutableReplicas":{},"f:nodeName":{},"f:players":{},"f:ports":{},"f:reservedUntil":{},"f:state":{}}}}]},"spec":{"container":"default","ports":[{"name":"http","portPolicy":"Dynamic","container":"default","containerPort":8080,"hostPort":22653,"protocol":"TCP"}],"health":{"periodSeconds":5,"failureThreshold":3,"initialDelaySeconds":5},"scheduling":"Packed","sdkServer":{"logLevel":"Info","grpcPort":9357,"httpPort":9358},"template":{"metadata":{"creationTimestamp":null,"labels":{"agones.dev/fleet":"nick-test"},"annotations":{"kubectl.kubernetes.io/default-container":"default"}},"spec":{"containers":[{"name":"default","image":"europe-docker.pkg.dev/test/dev/prod/testtest@sha256:4c323ab8c951bc63649e62ea95dec08736eef36ca388b1d7e9857fe2df008072","resources":{"requests":{"cpu":"250","memory":"100Gi"}},"imagePullPolicy":"IfNotPresent"}],"terminationGracePeriodSeconds":30,"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"game-server","operator":"Exists"}]}]}}},"tolerations":[{"key":"game-server","operator":"Equal","value":"true","effect":"NoExecute"}]}},"eviction":{"safe":"Never"}},"status":{"state":"Creating","ports":null,"address":"","addresses":null,"nodeName":"","reservedUntil":null,"players":null,"eviction":{"safe":"Never"}}},"gsKey":"test/nick-test-kzt87-2dzzr","message":"Pod created is forbidden","pod":{"metadata":{"creationTimestamp":null},"spec":{"containers":null},"status":{}},"severity":"error","source":"*gameservers.Controller","time":"2023-09-18T14:04:30.445950984Z"}
{"gs":{"metadata":{"name":"nick-test-cpl26-vx66f","generateName":"nick-test-cpl26-","namespace":"test","uid":"9658d3fa-f2e2-4248-863a-a76e39942bd7","resourceVersion":"32720787","generation":2,"creationTimestamp":"2023-09-18T14:04:30Z","labels":{"agones.dev/fleet":"nick-test","agones.dev/gameserverset":"nick-test-cpl26"},"annotations":{"agones.dev/sdk-version":"1.34.0"},"ownerReferences":[{"apiVersion":"agones.dev/v1","kind":"GameServerSet","name":"nick-test-cpl26","uid":"4acb6550-e3dd-4178-8bfc-ce2b759780d6","controller":true,"blockOwnerDeletion":true}],"finalizers":["agones.dev"],"managedFields":[{"manager":"controller","operation":"Update","apiVersion":"agones.dev/v1","time":"2023-09-18T14:04:30Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:agones.dev/fleet":{},"f:agones.dev/gameserverset":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"4acb6550-e3dd-4178-8bfc-ce2b759780d6\"}":{}}},"f:spec":{".":{},"f:container":{},"f:health":{},"f:immutableReplicas":{},"f:ports":{},"f:scheduling":{},"f:sdkServer":{},"f:template":{".":{},"f:metadata":{".":{},"f:annotations":{".":{},"f:kubectl.kubernetes.io/default-container":{}},"f:creationTimestamp":{},"f:labels":{".":{},"f:agones.dev/fleet":{}}},"f:spec":{".":{},"f:affinity":{".":{},"f:nodeAffinity":{".":{},"f:requiredDuringSchedulingIgnoredDuringExecution":{}}},"f:containers":{},"f:terminationGracePeriodSeconds":{},"f:tolerations":{}}}},"f:status":{".":{},"f:address":{},"f:addresses":{},"f:immutableReplicas":{},"f:nodeName":{},"f:players":{},"f:ports":{},"f:reservedUntil":{},"f:state":{}}}}]},"spec":{"container":"default","ports":[{"name":"http","portPolicy":"Dynamic","container":"default","containerPort":8080,"hostPort":17731,"protocol":"TCP"}],"health":{"periodSeconds":5,"failureThreshold":3,"initialDelaySeconds":5},"scheduling":"Packed","sdkServer":{"logLevel":"Info","grpcPort":9357,"httpPort":9358},"template":{"metadata":{"creationTimestamp":null,"labels":{"agones.dev/fleet":"nick-test"},"annotations":{"kubectl.kubernetes.io/default-container":"default"}},"spec":{"containers":[{"name":"default","image":"europe-docker.pkg.dev/test/dev/prod/testtest@sha256:4c323ab8c951bc63649e62ea95dec08736eef36ca388b1d7e9857fe2df008072","resources":{"requests":{"cpu":"2","memory":"100Mi"}},"imagePullPolicy":"IfNotPresent"}],"terminationGracePeriodSeconds":30,"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"game-server","operator":"Exists"}]}]}}},"tolerations":[{"key":"game-server","operator":"Equal","value":"true","effect":"NoExecute"}]}},"eviction":{"safe":"Never"}},"status":{"state":"Creating","ports":null,"address":"","addresses":null,"nodeName":"","reservedUntil":null,"players":null,"eviction":{"safe":"Never"}}},"gsKey":"test/nick-test-cpl26-vx66f","message":"Pod created is forbidden","pod":{"metadata":{"creationTimestamp":null},"spec":{"containers":null},"status":{}},"severity":"error","source":"*gameservers.Controller","time":"2023-09-18T14:04:30.463975513Z"}
```
- Others:

### PR DESCRIPTION
**Pull request by nrwiersma**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

 /kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

This PR addresses an issue in Agones when constrained by a ResourceQuota. A Fleet, specifically the active GameServerSet will attempt to scale past the ResourceQuota causing a large amount of network traffic on the Node running the Agones controller (~50Mb/s) as well as high load on etcd. GameServers where the pod creation is disallowed move into the Error state, immediately being deleted and a new GameServer created.

This issue is addressed by setting an annotation (`agoned.dev/errored-at`) with the timestamp of when it moved it the Error state. The GameServerSet controller will delay the deletion of these GameServers for at least 10s, in this time counting the GameServer as up and pending. As the reason for a GameServer moving into the Error state are limited (Incorrect spec or not being allowed to create the Pod) the slows the creation of GameServers in this case only, without affecting other areas of scaling.

In testing it was observed that the traffic on the Node went from ~50Mb/s using Agones v1.34.0 to ~5Mb/s using this patch.
Screenshot 2023-10-12 at 13 25 03

**Which issue(s) this PR fixes**:

Closes #3384

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by nrwiersma** [comment]
We managed to do some testing on a production system, and captured the results of etcd. This was on a fresh cluster that was scaled to 200 GameServers with a ResourceQuota with a hard limit of 32 GameServers, so ~168 GameServers were in Error state. First this build was deployed at ~16:20 and back to Agones v1.34 at ~16:30.

image

File: pkg/gameserversets/controller.go [hunk 1]
```diff
@@ -66,6 +66,10 @@ const (
 
 	// maxPodPendingCount is the maximum number of pending pods per game server set
 	maxPodPendingCount = 5000
+
+	// gameServerErrorDeletionDelay is the minimum amount of time to delay the deletion
+	// of a GameServer in Error state.
+	gameServerErrorDeletionDelay = 10 * time.Second
```
Comment (markmandel) [inline pkg/gameserversets/controller.go:72]: Is 10 enough? Should it be bigger? 30?

File: pkg/gameserversets/controller_test.go [hunk 2]
```diff
@@ -622,6 +622,98 @@ func TestSyncGameServerSet(t *testing.T) {
...
+		assert.Equal(t, 6, count)
+		assert.True(t, updated, "A game servers should have been updated")
+	})
+
+	t.Run("adding and delay deleting errored gameservers", func(t *testing.T) {
+		gsSet := defaultFixture()
+		list := createGameServers(gsSet, 5)
+
+		// make some as unhealthy
+		list[0].Annotations = map[string]string{agonesv1.GameServerErroredAtAnnotation: time.Now().UTC().Format(time.RFC3339)}
```
Comment (markmandel) [inline pkg/gameserversets/controller_test.go:676]: Non blocking suggestion:

If it's useful, could create an instance of https://pkg.go.dev/k8s.io/utils/clock (we do this in a few places in the codebase), so you can fake the passage of time in testing.

For example:
https://github.com/googleforgames/agones/blob/85dd69ab8a3f26a41cfed368a4f843e1473cbb91/pkg/fleetautoscalers/controller.go#L80

If not useful, feel free to resolve and ignore.

**Review by markmandel — COMMENTED** [review]
Sorry for the delay, but looks good! Just a couple of small questions for you, but otherwise, looks good to go 👍🏻 

Nice testing btw as well!

File: pkg/gameserversets/controller.go (hunk 1 above)
Comment (nrwiersma) [reply pkg/gameserversets/controller.go:72]: 10s is the minimum time, in testing they tended to live a little longer, depending on how busy the controller was (12s-22s). Happy to increase it if you see value there, but I do think there is a balance to be struck here.

File: pkg/gameserversets/controller_test.go (hunk 2 above)
Comment (nrwiersma) [reply pkg/gameserversets/controller_test.go:676]: I dont think it is important for this change, as the time stuff is minor and easy to test, but if it got more complex, I definitely see it as a good idea.

Comment (markmandel) [reply pkg/gameserversets/controller_test.go:676]: Sounds reasonable. Resolving.

File: pkg/gameserversets/controller.go (hunk 1 above)
Comment (markmandel) [reply pkg/gameserversets/controller.go:72]: My only thought was for invalid Podspec GameServers (which is harder to do these days), 30+ seconds is a bit easier to get a `kubectl describe gameserver <name>` than 10-20.

Is there a downside to a longer time?

Comment (nrwiersma) [reply pkg/gameserversets/controller.go:72]: My thought is that as Error GameServers are considered up and pending, there is some portion of the capacity that is blocked. In the case of hitting a ResourceQuota and then going below the ResourceQuota again, it will take longer for that capacity to become available. That for me is the balance. I guess 30s would not be destructive here though, so happy with that change.

Comment (nrwiersma) [reply pkg/gameserversets/controller.go:72]:
```suggestion
	gameServerErrorDeletionDelay = 30 * time.Second
```

File: pkg/gameserversets/controller_test.go [hunk 3]
```diff
@@ -622,6 +622,98 @@ func TestSyncGameServerSet(t *testing.T) {
 		assert.True(t, updated, "A game servers should have been updated")
 	})
 
+	t.Run("adding and deleting errored gameservers", func(t *testing.T) {
+		gsSet := defaultFixture()
+		list := createGameServers(gsSet, 5)
+
+		// make some as unhealthy
+		list[0].Annotations = map[string]string{agonesv1.GameServerErroredAtAnnotation: time.Now().Add(-10 * time.Second).UTC().Format(time.RFC3339)}
```
Comment (nrwiersma) [inline pkg/gameserversets/controller_test.go:630]:
```suggestion
		list[0].Annotations = map[string]string{agonesv1.GameServerErroredAtAnnotation: time.Now().Add(-30 * time.Second).UTC().Format(time.RFC3339)}
```

**Review by markmandel — APPROVED** [review]
LGTM! Nice change!
