### PR TITLE
Fix Rolling Update with Allocated GameServers

### LINKED ISSUE #2397: Fleet RollingUpdate gets stuck when Fleet has high number of allocated GameServers
**What happened**:

Fleet rolling update gets stuck when the Fleet continuously gets new allocations and maintains a high number of Allocated GameServers. The old `GameServerSet` doesn't fully scale down and remains up with Ready replicas, such that some allocations keep going to the old GSS.

Context: made a change to the CPU request of a live Fleet (~70% Allocated GameServers) and the update got stuck at two `GameServerSet`s, each having their own buffer of Ready replicas. This also resulted in a ~2x higher buffer of Ready gameservers than specified in the `FleetAutoscaler`. The GameServerSets remained stuck in this state for at least 30-40 minutes, after which the old GSS was manually set to 0 replicas to force it to scale down.

**What you expected to happen**:

A RollingUpdate to complete on a busy Fleet.

**How to reproduce it (as minimally and precisely as possible)**:

* Create `Fleet` with 10 replicas, no `FleetAutoscaler`. 
	* Use default `RollingUpdate` values (25% surge/unavailable).

Get two `GameServerSet`s in a similar state as:

<table>
<tr>
	<td>GSS
	<td>Desired
	<td>Current
	<td>Allocated
	<td>Ready
<tr>
	<td>New (=Active)
	<td>7
	<td>7
	<td>4
	<td>3
<tr>
	<td>Old (=Rest)
	<td>4
	<td>4
	<td>3
	<td>1
</table>

GSSs are stuck in this state, the Ready replicas of the old GSS aren't shut down/replaced by the new GSS. The old GSS keeps Ready replicas up, which get Allocated, causing the GSS's to remain in this state even if gameservers get deallocated/shutdown.

The issue can also be reproduced in the following scenario:
* Again have a fleet of 10 replicas (with supertuxkart)
* Repeatedly allocate a gameserver every 3 seconds
* Shut down the allocated GS after 15s (so on avg, ~5 allocated GS will be up at any time)
* Make an update to the fleet spec to trigger a RollingUpdate
* Old GSS never shuts down, and keeps serving allocation requests

**Anything else we need to know?**:

Could reproduce in Agones 1.16 with `RollingUpdateOnReady` disabled, although needed a higher amount of Allocated GameServers to get the rolling update to get stuck.

**Environment**:
- Agones version: 1.18
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): -
- Others: -

### PR DESCRIPTION
**Pull request by WVerlaek**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

See discussion in https://github.com/googleforgames/agones/issues/2397. This PR reproduces the issue there, where a Fleet rolling update can get stuck if there's a significant percentage of GameServers in an Allocated state.

This is demonstrated by updating the existing e2e test for Fleet Rolling Update, by repeatedly allocating and shutting down GameServers in the Fleet, keeping around ~half of the Fleet in an Allocated state.

Recording of a run of the e2e test:

https://user-images.githubusercontent.com/9721064/148236988-9798c0e8-064f-4810-9a2f-14eee14a83c8.mov

First, half of the fleet gets Allocated, then the Fleet update is made which creates the second GameServerSet. These two GSSs then get stuck indefinitely, the old GSS never fully scales down.

**Which issue(s) this PR fixes**:

Closes #2397

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by WVerlaek** [comment]
The potential solution in https://github.com/googleforgames/agones/issues/2397#issuecomment-992501065 which would change

```
newGSSUnavailablePodCount := active.Spec.Replicas - active.Status.ReadyReplicas
```
to
```
newGSSUnavailablePodCount := active.Spec.Replicas - active.Status.ReadyReplicas - active.Status.AllocatedReplicas
```
(in https://github.com/googleforgames/agones/blob/main/pkg/fleets/controller.go#L532)

does scale down the old GSS, while leaving Ready replicas up:

https://user-images.githubusercontent.com/9721064/148254922-d353d41a-bee7-4be4-afe1-126282c12d2c.mov

**Comment by markmandel** [comment]
Just letting you know we haven't forgotten about this - been clearing up a bunch of flakey test issues so we're able to get better velocity overall.

File: test/e2e/fleet_test.go [hunk 1]
```diff
@@ -223,14 +223,16 @@ func TestFleetRollingUpdate(t *testing.T) {
 	t.Parallel()
 	ctx := context.Background()
 	// Use scaleFleetPatch (true) or scaleFleetSubresource (false)
-	fixtures := []bool{true, false}
-	maxSurge := []string{"25%", "10%"}
+	fixtures := []bool{true}    // , false} // TODO Enable these again
+	maxSurge := []string{"25%"} // , "10%"} // TODO
+	doCycle := true             // TODO: fixture?
```
Comment (WVerlaek) [inline test/e2e/fleet_test.go:228]: `doCycle` should be a fixture as well, but that would double the number of tests to run from 4 to 8? Doesn't seem great, especially since they're all running in parallel?

**Review by WVerlaek — COMMENTED** [review]
@markmandel updated the PR to include the proposed fix, still need to make some other changes/cleanup if this works, but will leave as is to see if the tests pass

**Comment by markmandel** [comment]
Looks like e2e-stable was not happy:

```
--- FAIL: TestFleetRollingUpdate (137.90s)
    --- FAIL: TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true (76.79s)
        fleet_test.go:299: 
            	Error Trace:	fleet_test.go:299
            	Error:      	Received unexpected error:
            	            	resource name may not be empty
            	Test:       	TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true
        fleet_test.go:311: 
            	Error Trace:	fleet_test.go:311
            	Error:      	Received unexpected error:
            	            	timed out waiting for the condition
            	Test:       	TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true
```

I'll run it one more time, see if we get consistent failures.

**Comment by markmandel** [comment]
> but this PR's test was running at the same time,

We lock on each build so only one e2e test is running at a time. I also have some dashboards to check if the cluster is full.

There is some flakiness in the e2e test suite, but this doesn't 100% look like our usual flakes.

But I would focus on the reproducible issues, and then we can dig deeper.

**Comment by WVerlaek** [comment]
Fixed an issue in the test that was causing the failure in https://github.com/googleforgames/agones/pull/2420#issuecomment-1058691851

Been able to consistently run the test locally now without failures, let's see if it passes in CI a second time 😄

File: test/e2e/fleet_test.go [hunk 2]
```diff
@@ -222,123 +222,193 @@ func TestFleetScaleUpEditAndScaleDown(t *testing.T) {
...
+		{
+			usePatch:         false,
+			maxSurge:         "10%",
+			cycleAllocations: false,
+		},
+		{
+			usePatch:         true,
+			maxSurge:         "25%",
+			cycleAllocations: true,
+		},
```
Comment (WVerlaek) [inline test/e2e/fleet_test.go:262]: the first 4 are the original fixtures, added a single 5th fixture that cycles allocations during the rolling update

File: test/e2e/fleet_test.go [hunk 3]
```diff
@@ -222,123 +222,193 @@ func TestFleetScaleUpEditAndScaleDown(t *testing.T) {
...
+				const halfScale = targetScale / 2
+				const period = 3 * time.Second
+				go framework.CycleAllocations(t, flt, period, period*halfScale, done)
+
+				// Wait for at least half of the fleet to have be cycled (either Allocated or shutting down)
+				// before updating the fleet.
+				err = framework.WaitForFleetCondition(t, flt, func(entry *logrus.Entry, fleet *agonesv1.Fleet) bool {
+					return fleet.Status.ReadyReplicas < halfScale
+				})
+			}
```
Comment (WVerlaek) [inline test/e2e/fleet_test.go:319]: new addition to this test: repeatedly allocate and shutdown gameservers (if enabled in the test case)

File: test/e2e/fleet_test.go [hunk 4]
```diff
@@ -222,123 +222,193 @@ func TestFleetScaleUpEditAndScaleDown(t *testing.T) {
...
-						return false, err
+				// Ignore any GameServers that are shutting down (resulting from Allocation cycling).
+				shuttingDown := 0
+				for _, gs := range list.Items {
+					if gs.IsBeingDeleted() {
+						shuttingDown++
 					}
-					return len(gssList.Items) == 1, nil
-				})
+				}
```
Comment (WVerlaek) [inline test/e2e/fleet_test.go:375]: added this, which ignores gameservers that are shutting down when checking if the total number of gameservers doesn't exceed the expected total. Needed when cycling allocations is enabled

**Comment by WVerlaek** [comment]
@markmandel have fixed an issue with the tests, and cleaned up the PR (enabling all test cases again). Seems to be passing consistently now both locally and on CI.

Unfortunately the diff is a bit of a mess by having to change indenting, but commented on all the changes made to the test

**Comment by markmandel** [comment]
Looks like there is a panic in `TestFleetScaleUpEditAndScaleDown`

```
E0315 17:44:32.608994   11481 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 87 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1ec9420, 0x2faef70})
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xe6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x481147})
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0xb0
panic({0x1ec9420, 0x2faef70})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
agones.dev/agones/test/e2e.TestFleetRollingUpdate.func1.4()
	/go/src/agones.dev/agones/test/e2e/fleet_test.go:356 +0x1f6
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc000549c10)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211 +0xa2
k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0x3b9aca00, 0x45d964b800)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:445 +0x36
k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x2320740, 0xc000a7c680, 0x231e260)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:441 +0x46
agones.dev/agones/test/e2e.TestFleetRollingUpdate.func1(0xc000a7c680)
	/go/src/agones.dev/agones/test/e2e/fleet_test.go:349 +0x1105
testing.tRunner(0xc000a7c680, 0xc00013c060)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727
--- FAIL: TestFleetRollingUpdate (223.70s)
    --- FAIL: TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true (116.40s)
        fleet_test.go:333: 
            	Error Trace:	fleet_test.go:333
            	Error:      	Received unexpected error:
            	            	Operation cannot be fulfilled on fleets.agones.dev "simple-fleet-6f5rn": the object has been modified; please apply your changes to the latest version and try again
            	Test:       	TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true
        fleet_test.go:345: 
            	Error Trace:	fleet_test.go:345
            	Error:      	Received unexpected error:
            	            	timed out waiting for the condition
            	Test:       	TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d017f6]
```

**Review by markmandel — COMMENTED** [review]
Overall, changes look good - just some cleanup and weirdness in some other tests.

I'm wondering if the change is highlighting some other issues in some other tests.

**Comment by markmandel** [comment]
Hmnn, I am now wondering if that is just a flake in `TestFleetRollingUpdate`. Lemme look into it.

**Comment by markmandel** [comment]
Sorry, I'm having a day - that is an error in `TestFleetRollingUpdate` - so we'll need to work that out.

File: test/e2e/fleet_test.go [hunk 5]
```diff
@@ -222,123 +222,193 @@ func TestFleetScaleUpEditAndScaleDown(t *testing.T) {
...
+				if err != nil {
+					return err
+				}
 				fltCopy := flt.DeepCopy()
 				fltCopy.Spec.Template.Spec.Ports[0].ContainerPort++
 				flt, err = client.Fleets(framework.Namespace).Update(ctx, fltCopy, metav1.UpdateOptions{})
-				assert.NoError(t, err)
+				return err
+			})
+			assert.NoError(t, err)
```
Comment (markmandel) [inline test/e2e/fleet_test.go:333]:
```suggestion
			require.NoError(t, err)
```

Since if this fails, things panic later on, and it's hard to see what is the real error.

File: test/e2e/fleet_test.go [hunk 6]
```diff
@@ -222,123 +222,193 @@ func TestFleetScaleUpEditAndScaleDown(t *testing.T) {
...
+				// Wait for at least half of the fleet to have be cycled (either Allocated or shutting down)
+				// before updating the fleet.
+				err = framework.WaitForFleetCondition(t, flt, func(entry *logrus.Entry, fleet *agonesv1.Fleet) bool {
+					return fleet.Status.ReadyReplicas < halfScale
+				})
+			}
+
+			// Change ContainerPort to trigger creating a new GSSet
+			fltName := flt.GetName()
+			err = retry.RetryOnConflict(retry.DefaultBackoff, func() error {
```
Comment (markmandel) [inline test/e2e/fleet_test.go:323]: So if I'm reading the DefaultBackoff correctly, it only retries 4 times, with only a 10ms gap-- which in a cluster under load, may very much not be enough.

My suggestion would be to either:

Create a backoff of something like:
```go
backoff := wait.Backoff {
   Duration: time.Second
   Factor: 1
   Cap: time.Minute
}
```

or it may be far simpler to use `require.Eventually(...)` with a 1 second rate, and a timeout of a minute.
https://pkg.go.dev/github.com/stretchr/testify/require#Eventually - since we end up in the same place anyway.

Comment (WVerlaek) [reply test/e2e/fleet_test.go:323]: so DefaultBackoff should have some exponential backoff (each time the delay is increased x5), if I read it correctly that will mean a max backoff of a couple of seconds. But not sure if it's catching the conflicts properly here, it's strange that it would still fail

I'll change it to `require.Eventually()` though, also to align with other tests

**Comment by WVerlaek** [comment]
https://github.com/googleforgames/agones/pull/2420#issuecomment-1069340881 was a conflict in updating the Fleet again. Should hopefully be fixed now after using `require.Eventually`

Second build failure was a lint error

**Comment by markmandel** [comment]
Something got stuck maybe?

```
goroutine 431 [select]:
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc00104b1d0, 0x0, 0xc0008fc6c0)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:539 +0x16a
k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc00081bc58, 0x1f4b6c0)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:427 +0xb0
k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0x3b9aca00, 0x45d964b800)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:452 +0x65
k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x2320a00, 0xc000a0c000, 0x0)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:441 +0x46
agones.dev/agones/test/e2e.TestFleetRollingUpdate.func1(0xc000a0c000)
	/go/src/agones.dev/agones/test/e2e/fleet_test.go:343 +0x1565
testing.tRunner(0xc000a0c000, 0xc0007b6040)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727
```

**Comment by WVerlaek** [comment]
`wait.PollImmediateUntil` is returning a timeout error when the context gets cancelled at the end of the test, updated the test to ignore a timeout err

File: test/e2e/framework/framework.go [hunk 7]
```diff
@@ -278,6 +278,33 @@ func (f *Framework) WaitForGameServerState(t *testing.T, gs *agonesv1.GameServer
 		state, gs.Namespace, gs.Name)
 }
 
+// CycleAllocations repeatedly Allocates a GameServer in the Fleet (if one is available), once every specified period.
+// Each Allocated GameServer gets deleted allocDuration after it was Allocated.
+// GameServers will continue to be Allocated until a message is passed to the done channel.
+func (f *Framework) CycleAllocations(ctx context.Context, t *testing.T, flt *agonesv1.Fleet, period time.Duration, allocDuration time.Duration) {
+	err := wait.PollImmediateUntil(period, func() (bool, error) {
```
[the remark this answers is not in the document]
Comment (WVerlaek) [reply test/e2e/framework/framework.go:285]: That would be much better, just had a look but I dont think that function is available in the current version of the library

[the remark this answers is not in the document]
Comment (markmandel) [reply test/e2e/framework/framework.go:285]: Aaaah. Shame 😞

**Review by markmandel — APPROVED** [review]
Took it for a spin! Worked!
