### PR TITLE
Fix replicas miscalculation when fleet replicas equals zero

### LINKED ISSUE #2509: Agones Controller attempts to scale to a negative integer instead of zero
**What happened**:
When attempting to scale down a fleet to zero (--replicas=0) with allocated servers (still using a prior version of the fleet config), the controller attempts to scale to a negative value, which is equal to the number of still-allocated gameservers (in my repro case this was 2 gameservers, so -2). As a result the scale down command does nothing and the fleet stays at its prior configured number of replicas (in the repro case this is 5). 

**What you expected to happen**:

The fleet should scale down to 0 as normal, not use an invalid spec with a negative integer

**How to reproduce it**:

All of the below was run in powershell, because I am using [this repo](https://github.com/comerford/minikube-agones-cluster) to replicate the issue, hence some of the odd escaping.

Note: per [this default value](https://github.com/comerford/minikube-agones-cluster/blob/main/tf-agones/variables.tf#L9) the PlayerTracking feature gate is enabled.

To reproduce, clone the repo, then run powershell as admin, start the cluster:

```pwsh
./deploy.ps1 apply

# scale the fleet to 5

kubectl -n gameservers scale fleet local-fleet --replicas 5

# allocate 2 servers

curl -d '{\"apiVersion\": \"allocation.agones.dev/v1\",\"kind\": \"GameServerAllocation\",\"spec\": {\"selectors\": [{\"matchLabels\": {\"agones.dev/fleet\": \"local-fleet\"}}]}}' -H "Content-Type: application/json" -X POST http://localhost:8001/apis/allocation.agones.dev/v1/namespaces/gameservers/gameserverallocations
curl -d '{\"apiVersion\": \"allocation.agones.dev/v1\",\"kind\": \"GameServerAllocation\",\"spec\": {\"selectors\": [{\"matchLabels\": {\"agones.dev/fleet\": \"local-fleet\"}}]}}' -H "Content-Type: application/json" -X POST http://localhost:8001/apis/allocation.agones.dev/v1/namespaces/gameservers/gameserverallocations
```
Now edit the fleet config, specifically I added an initial player capacity
```yaml
    spec:
      health:
        failureThreshold: 20
        initialDelaySeconds: 10
        periodSeconds: 5
      players:
        initialCapacity: 4
``` 

Once the Ready state nodes have been refreshed, issue the scale down command:
```pwsh
kubectl -n gameservers scale fleet local-fleet --replicas=0

# Note the fleet remains unchanged, with 5 replicas:

kubectl -n gameservers get gs

# Examine the controller logs to see the -2 error

kubectl -n agones-system logs agones-controller-554d4cc6f8-k5wn7

{"message":"error updating replicas for gameserverset for fleet local-fleet: GameServerSet.agones.dev \"local-fleet-8xsp6\" is invalid: [spec.replicas: Invalid value: -2: spec.replicas in body should be greater than or equal to 0, .spec.replicas: Invalid value: -2: should be a non-negative integer]","severity":"error","stack":["agones.dev/agones/pkg/fleets.(*Controller).upsertGameServerSet\n\t/go/src/agones.dev/agones/pkg/fleets/controller.go:340","agones.dev/agones/pkg/fleets.(*Controller).syncFleet\n\t/go/src/agones.dev/agones/pkg/fleets/controller.go:299","agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).processNextWorkItem\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:180","agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).runWorker\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:156","agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).run.func1\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:215","k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155","k8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156","k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133","k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90","agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).run\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:215","runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"],"time":"2022-03-12T02:39:07.2225067Z"}
```

**Anything else we need to know?**:

Initially discussed on [this Slack thread](https://agones.slack.com/archives/C9DGM5DS8/p1646526270160429).

If you set the number of replicas to 2 (or whatever the number of allocated servers is) the errors in the controller go away. The fleet scales down to the 2 remaining allocated as expected. If you then kill a pod manually, it will spin up a replacement in Ready state. Now repeat the scale down to zero command and the error will re-occur, this time with a -1 value for the single remaining allocated server.

**Environment**:
- Agones version: 1.19.0
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: minikube on Windows for repro, EKS/AWS/Linux originally
- Install method (yaml/helm): helm

### PR DESCRIPTION
**Pull request by govargo**
**What type of PR is this?**

/kind bug

**What this PR does / Why we need it**:

When attempting to scale down a fleet to zero, if we have the old gameserverset, currently the scale down will fail.
This PR fix the rolling update with scale zero.
And this PR adds unit test and e2e test.

This PR is based on closed #2515. Thank you @danieloliveira079!!
(I changed some test codes and tested locally)

**Which issue(s) this PR fixes**:

Closes #2509, #2617

**Special notes for your reviewer**:

none

### CODE REVIEW

**Comment by govargo** [comment]
E2E test passed!

File: test/e2e/fleet_test.go [hunk 1]
```diff
@@ -123,6 +123,114 @@ func TestFleetStrategyValidation(t *testing.T) {
...
+	if runtime.FeatureEnabled(runtime.FeaturePlayerTracking) {
+		fltCopy.Spec.Template.Spec.Players.InitialCapacity = 4
+	} else {
+		fltCopy.Spec.Template.Spec.Ports = []agonesv1.GameServerPort{{
+			ContainerPort: 6000,
+			Name:          "gameport",
+			PortPolicy:    agonesv1.Dynamic,
+			Protocol:      corev1.ProtocolUDP,
+		}}
+	}
```
Comment (markmandel) [inline test/e2e/fleet_test.go:178]: Oh this works! I was going to suggest adding a label, but changing a port works perfectly as well. No issues with the approach on my end!

```suggestion
fltCopy.Spec.Template.Spec.Ports = []agonesv1.GameServerPort{{
	ContainerPort: 6000,
	Name:          "gameport",
	PortPolicy:    agonesv1.Dynamic,
	Protocol:      corev1.ProtocolUDP,
}}
```

What I would then suggest, just get rid of all the player tracking and feature flag parts here and elsewhere in this e2e test, and just to the port manipulation -- there's nothing inherent to player tracking in this ticket, it was just  way to trigger a rolling update.

It will be much easier to read 👍🏻

**Review by markmandel — COMMENTED** [review]
Ah! 😄  you beat me to it, I was going to tackle this today! Nice!

File: test/e2e/fleet_test.go (hunk 1 above)
Comment (govargo) [reply test/e2e/fleet_test.go]: Thank you!! I updated the codebase.

**Review by markmandel — COMMENTED** [review]
Small nit on the comment there, but otherwise this is good to go!

Thanks for doing this!

File: test/e2e/fleet_test.go [hunk 2]
```diff
@@ -123,6 +123,99 @@ func TestFleetStrategyValidation(t *testing.T) {
...
+		// 2 GSSet should be created
+		if len(list.Items) == 2 {
+			ready = true
+		}
+		return ready, nil
+	})
+
+	assert.Nil(t, err)
+
+	// RollingUpdate has happened due to changing PlayerCapacity, so waiting the complete of the RollingUpdate
```
[the remark this answers is not in the document]
Comment (govargo) [reply test/e2e/fleet_test.go]: I missed it. Thank you!!

**Review by markmandel — APPROVED** [review]
YEAH!

**Comment by roberthbailey** [comment]
`e2e-feature-gates` failed with `panic: test timed out after 10m0s`
