### PR TITLE
test: standardize runtime.ParseFeatures error handling and mutex usage

### LINKED ISSUE #4407: Flaky:  TestControllerAllocator/successful_allocation
Another flaky Unit test:

```
--- FAIL: TestControllerAllocator (1.29s)
    --- FAIL: TestControllerAllocator/successful_allocation (1.25s)
        controller_test.go:117: 
            	Error Trace:	/go/src/agones.dev/agones/pkg/gameserverallocations/controller_test.go:117
            	            				/go/src/agones.dev/agones/pkg/gameserverallocations/controller_test.go:132
            	Error:      	Not equal: 
            	            	expected: 201
            	            	actual  : 422
            	Test:       	TestControllerAllocator/successful_allocation
```

https://console.cloud.google.com/cloud-build/builds/0fdbb16c-b47c-4589-8437-791600a3155d;step=19?invt=AcGWmA&project=agones-images

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

Ensure all calls to runtime.ParseFeatures in unit tests follow consistent patterns:

- Wrap all calls with require.NoError instead of assert.NoError to fail fast on parse errors

- Add runtime.FeatureTestMutex locks with defer unlocks to all tests/subtests using ParseFeatures

- Fix mutex scope in pkg/sdkserver/sdk_test.go by moving locks from parent test to individual subtests

This ensures thread-safe feature flag manipulation and prevents test flakiness from concurrent feature state modifications.

**Which issue(s) this PR fixes**:

This also includes some (probable) fixes for flaky tests, particularly closes #4407 as part of this work.

**Special notes for your reviewer**:

🤞🏻

### CODE REVIEW

File: pkg/fleetautoscalers/fleetautoscalers_test.go [hunk 1]
```diff
@@ -619,10 +620,9 @@ func TestApplyWebhookPolicyWithMetadata(t *testing.T) {
 	utilruntime.FeatureTestMutex.Lock()
 	defer utilruntime.FeatureTestMutex.Unlock()
 
-	err := utilruntime.ParseFeatures(string(utilruntime.FeatureFleetAutoscaleRequestMetaData) + "=true")
-	assert.NoError(t, err)
+	require.NoError(t, utilruntime.ParseFeatures(string(utilruntime.FeatureFleetAutoscaleRequestMetaData)+"=true"))
 	defer func() {
-		_ = utilruntime.ParseFeatures("")
+		require.NoError(t, utilruntime.ParseFeatures(""))
```
Comment (igooch) [inline pkg/fleetautoscalers/fleetautoscalers_test.go]: Is this needed? None of the other tests use a cleanup function for the ParseFeatures.

If we do need the cleanup function, should this be assert instead of require? The require inside of a defer cleanup function might mask a primary failure elsewhere.

File: pkg/gameserverallocations/controller_test.go [hunk 2]
```diff
@@ -59,6 +60,9 @@ const (
 func TestControllerAllocator(t *testing.T) {
 	t.Parallel()
 
+	runtime.FeatureTestMutex.Lock()
+	defer runtime.FeatureTestMutex.Unlock()
+
```
Comment (igooch) [inline pkg/gameserverallocations/controller_test.go:65]: The mutex forces this test to run serially as it waits for the global lock, even though there's t.Parallel, correct?

As an alternative, should we remove `t.Parallel` from all tests that change the state with `ParseFeatures` or otherwise, and run all other tests that do not need to change the state with `t.Parallel`? That way all the tests that need to lock run serially, and all remaining tests are run in parallel [with and only with other Parallel tests](https://pkg.go.dev/testing#T.Parallel).

File: pkg/gameserverallocations/controller_test.go [hunk 3]
```diff
@@ -114,7 +116,9 @@ func TestControllerAllocator(t *testing.T) {
 			rec := httptest.NewRecorder()
 			err = c.processAllocationRequest(ctx, rec, r, "default")
 			require.NoError(t, err)
-			require.Equal(t, http.StatusCreated, rec.Code)
+			if !assert.Equal(t, http.StatusCreated, rec.Code, "Unexpected HTTP Code") {
+				require.Failf(t, "Unexpected HTTP Code Body: %s", rec.Body.String())
+			}
```
Comment (igooch) [inline pkg/gameserverallocations/controller_test.go]: Nit:
```suggestion
require.Equal(t, http.StatusCreated, rec.Code, "Response body: %s", rec.Body.String())
```

File: pkg/gameserverallocations/controller_test.go (hunk 2 above)
Comment (markmandel) [reply pkg/gameserverallocations/controller_test.go:65]: The benefit of doing it this way is that other non-mutex'd tests can run in parallel with this one - so at least we can get some speed benefits of those running in parallel together.

This also gives us some testing of changes across unit tests of different feature gates -- but it can lead to flaky tests -- but it can find some potential issues around the way.

File: pkg/gameserverallocations/controller_test.go (hunk 3 above)
Comment (markmandel) [reply pkg/gameserverallocations/controller_test.go]: Oh yeah - that makes _way_ more sense. 🤦🏻

File: pkg/fleetautoscalers/fleetautoscalers_test.go (hunk 1 above)
Comment (markmandel) [reply pkg/fleetautoscalers/fleetautoscalers_test.go]: Agreed - it was there when I was refactoring. Happy to remove.

File: pkg/gameserverallocations/controller_test.go (hunk 2 above)
Comment (igooch) [reply pkg/gameserverallocations/controller_test.go:65]: It would be interesting to see what the speed difference would be across all e2e tests if we made the change. Not needed for this PR though :)

**Comment by markmandel** [comment]
On mobile atm, but there's a link that's not working anymore.

**Comment by markmandel** [comment]
On mobile atm, but there's a link that's not working anymore.
