### PR TITLE
Fix CRD API docs generation script

### LINKED ISSUE #4150: ListAction DeleteValues doesn't show up on the generated API reference
**What happened**:

https://agones.dev/site/docs/reference/agones_crd_api_reference/#allocation.agones.dev/v1.ListAction

No DeleteValues, which is odd, since we've has a release since #4054 was merged.

Image

**What you expected to happen**:

It should show up.

**How to reproduce it (as minimally and precisely as possible)**:

`make gen-api-docs && make site-server` 

**Anything else we need to know?**:

N/A

**Environment**:
- Agones version:  prod
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): N/A
- Troubleshooting guide log(s): N/A
- Others:

### PR DESCRIPTION
**Pull request by 0xaravindh**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

 /kind bug
 
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Fixes an error where gen-crd-api-reference-docs couldn't find API packages due to incorrect paths and setup. Updates the script to use the correct working directory, Go version, and template configuration.

```
F0414 06:51:17.289003     356 main.go:133] no API packages found in ../../../agones.dev/agones/pkg/apis/
make: *** [includes/website.mk:105: gen-api-docs] Error 255
```

Closes #4150

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by 0xaravindh** [comment]
#4150 Issue is resolved—DeleteValues is now showing up as expected.

57f9xNDiKEKkKqy

File: site/gen-api-docs.sh [hunk 1]
```diff
@@ -16,23 +16,11 @@
 
 set -ex
 
-#Reinstall Go 1.15 since the version upon it won't work with gen-crd-api-reference-docs
-rm -rf /usr/local/go
```
Comment (markmandel) [inline site/gen-api-docs.sh:20]: oh nice, glad that got updated and fixed.

**Review by markmandel — APPROVED** [review]
