### PR TITLE
Fix for Pod deletion during unavailable controller

### LINKED ISSUE #398: Moving cluster to a new node pool doesn't recreate all fleets
I've noticed something weird today. I needed to swap node pool in GKE so I created new node pool and deleted old one. I expected all instances in the old node pool to recover in the new one after some time. However in my particular case I could only see 1 of the 3 servers in `workloads` page on GCloud. So I checked fleets to see if it has min availability which was 1 of each kind = 3. And `kubectl describe fleets`  indicated that 3 servers were online and available, however when I tried to connect to one that was listed but not in `workloads` it failed to connect to it, I was able to connect to the one appearing in the `workloads`, but not others. I had to delete fleets and recreate them for them to appear and work correctly again.

### LINKED ISSUE #1170: Agones controller shut down
**What happened**: We have experienced cluster wide down time after Game Server list got out of sync with Pod list. When investigating Agones controller logs I can see that it has shut down, but has not started back up for 12 minutes after shutting down. 

Logs:
```
2019-11-02 23:28:37.132 GMT Shut down agones controllers
2019-11-02 23:40:19.201 GMT logging to file
2019-11-02 23:40:19.202 GMT starting gameServer operator...
2019-11-02 23:40:19.208 GMT Starting
```

After this game server list was extremely out of sync with actual pod list. 
Running `kubectl get gs` returned:
```
NAME                                STATE       ADDRESS      PORT   NODE                          AGE
deathmatch-server-odd-4fvpv-fjl8q   Ready       34.87.124.   7014   gke-node-pool-157ec1db-kbq3   8h
deathmatch-server-odd-4fvpv-g2dn2   Ready       34.87.79.    7534   gke-node-pool-55d97c47-dl00   8h
deathmatch-server-odd-4fvpv-h28gr   Allocated   35.247.128   7112   gke-node-pool-157ec1db-mgh3   8h
deathmatch-server-odd-4fvpv-hcwdv   Allocated   34.87.124.   7265   gke-node-pool-157ec1db-kbq3   8h
deathmatch-server-odd-4fvpv-hwgps   Allocated   35.247.128   7782   gke-node-pool-157ec1db-mgh3   8h
deathmatch-server-odd-4fvpv-mrcgx   Allocated   34.87.124.   7111   gke-node-pool-157ec1db-kbq3   8h
deathmatch-server-odd-4fvpv-nq58m   Ready       35.247.128   7861   gke-node-pool-157ec1db-mgh3   8h
deathmatch-server-odd-4fvpv-s765b   Ready       34.87.79.    7095   gke-node-pool-55d97c47-dl00   8h
deathmatch-server-odd-4fvpv-wrzlv   Ready       34.87.124.   7966   gke-node-pool-157ec1db-kbq3   8h
endless-server-odd-h79b4-28j55      Allocated   35.247.128   7601   gke-node-pool-157ec1db-mgh3   9h
endless-server-odd-h79b4-5q8ws      Allocated   35.247.17    7990   gke-node-pool-55d97c47-f2nv   20h
endless-server-odd-h79b4-qshqv      Ready       34.87.124.   7612   gke-node-pool-157ec1db-kbq3   8h
lobby-server-odd-znvjb-7vmbq        Allocated   35.187.246   7148   gke-node-pool-fb3f8ee9-rvpw   7s
lobby-server-odd-znvjb-dzpfl        Allocated   35.247.128   7992   gke-node-pool-157ec1db-mgh3   8h
lobby-server-odd-znvjb-fbfcr        Allocated   35.247.128   7209   gke-node-pool-157ec1db-mgh3   8h
lobby-server-odd-znvjb-lmlqt        Allocated   35.187.246   7167   gke-node-pool-fb3f8ee9-rvpw   15s
lobby-server-odd-znvjb-nnbnc        Allocated   35.247.128   7294   gke-node-pool-157ec1db-mgh3   8h
lobby-server-odd-znvjb-nrmj7        Allocated   35.247.128   7555   gke-node-pool-157ec1db-mgh3   8h
lobby-server-odd-znvjb-s2nkj        Ready       34.87.15.    7645   gke-node-pool-55d97c47-67s0   19s
lobby-server-odd-znvjb-skk6b        Allocated   35.247.128   7848   gke-node-pool-157ec1db-mgh3   13h
lobby-server-odd-znvjb-stqm2        Allocated   35.247.128   7193   gke-node-pool-157ec1db-mgh3   13h
lobby-server-odd-znvjb-t8m2z        Allocated   35.247.128   7220   gke-node-pool-157ec1db-mgh3   8h
lobby-server-odd-znvjb-tf5wh        Allocated   35.247.128   7037   gke-node-pool-157ec1db-mgh3   10h
lobby-server-odd-znvjb-tnfvb        Allocated   35.247.128   7824   gke-node-pool-157ec1db-mgh3   10h
lobby-server-odd-znvjb-tzq8f        Allocated   35.187.246   7639   gke-node-pool-fb3f8ee9-rvpw   31s
lobby-server-odd-znvjb-v4qgl        Allocated   35.247.128   7292   gke-node-pool-157ec1db-mgh3   8h
lobby-server-odd-znvjb-v8gzf        Allocated   35.247.128   7679   gke-node-pool-157ec1db-mgh3   13h
lobby-server-odd-znvjb-vksdf        Allocated   35.247.128   7101   gke-node-pool-157ec1db-mgh3   13h
lobby-server-odd-znvjb-vshkb        Ready       34.87.124.   7660   gke-node-pool-157ec1db-kbq3   43s
lobby-server-odd-znvjb-vtg4z        Allocated   35.247.128   7907   gke-node-pool-157ec1db-mgh3   13h
lobby-server-odd-znvjb-vvnkz        Allocated   35.247.128   7832   gke-node-pool-157ec1db-mgh3   12h
lobby-server-odd-znvjb-w2kc4        Ready       35.240.183   7388   gke-node-pool-fb3f8ee9-lw1p   56s
lobby-server-odd-znvjb-w6sdr        Allocated   35.247.128   7532   gke-node-pool-157ec1db-mgh3   9h
lobby-server-odd-znvjb-wf944        Allocated   35.247.128   7681   gke-node-pool-157ec1db-mgh3   16h
lobby-server-odd-znvjb-x5hpd        Ready       35.240.183   7149   gke-node-pool-fb3f8ee9-lw1p   10m
lobby-server-odd-znvjb-xdlh6        Allocated   35.247.128   7763   gke-node-pool-157ec1db-mgh3   14h
lobby-server-odd-znvjb-xjnzl        Ready       35.240.183   7372   gke-node-pool-fb3f8ee9-lw1p   19m
lobby-server-odd-znvjb-xp7h4        Ready       35.240.183   7847   gke-node-pool-fb3f8ee9-lw1p   17m
lobby-server-odd-znvjb-xp8fz        Allocated   35.247.128   7250   gke-node-pool-157ec1db-mgh3   14h
lobby-server-odd-znvjb-xrmx9        Ready       35.240.183   7085   gke-node-pool-fb3f8ee9-lw1p   39m
lobby-server-odd-znvjb-xs57n        Ready       35.240.183   7999   gke-node-pool-fb3f8ee9-lw1p   22m
lobby-server-odd-znvjb-z6ptt        Ready       35.240.183   7949   gke-node-pool-fb3f8ee9-lw1p   6m
lobby-server-odd-znvjb-zbwnr        Ready       35.240.183   7171   gke-node-pool-fb3f8ee9-lw1p   16m
lobby-server-odd-znvjb-zc8wl        Ready       35.240.183   7269   gke-node-pool-fb3f8ee9-lw1p   20m
lobby-server-odd-znvjb-zcx2r        Ready       35.240.183   7046   gke-node-pool-fb3f8ee9-lw1p   1m
lobby-server-odd-znvjb-zhdw8        Ready       35.240.183   7315   gke-node-pool-fb3f8ee9-lw1p   14m
lobby-server-odd-znvjb-zjrtd        Ready       35.240.183   7080   gke-node-pool-fb3f8ee9-lw1p   13m
lobby-server-odd-znvjb-zkvfb        Ready       35.247.128   7662   gke-node-pool-157ec1db-mgh3   9h
lobby-server-odd-znvjb-zpffl        Ready       35.240.183   7396   gke-node-pool-fb3f8ee9-lw1p   11s
lobby-server-odd-znvjb-zs5c4        Ready       35.240.183   7956   gke-node-pool-fb3f8ee9-lw1p   1m
lobby-server-odd-znvjb-ztn96        Ready       35.240.183   7397   gke-node-pool-fb3f8ee9-lw1p   32m
lobby-server-odd-znvjb-zv697        Ready       35.247.128   7377   gke-node-pool-157ec1db-mgh3   14h
lobby-server-odd-znvjb-zvjrl        Ready       35.240.183   7878   gke-node-pool-fb3f8ee9-lw1p   23m
lobby-server-odd-znvjb-zzftl        Ready       35.247.128   7835   gke-node-pool-157ec1db-mgh3   16h
messenger-server-odd-8l7ng-fv64c    Ready       34.87.79.    7036   gke-node-pool-55d97c47-dl00   14h
messenger-server-odd-8l7ng-fv64c    Ready       34.87.79.    7036   gke-node-pool-55d97c47-dl00   14h
royale-server-odd-d5wnz-8dfsq       Ready       35.240.183   7393   gke-node-pool-fb3f8ee9-lw1p   5m
royale-server-odd-d5wnz-96q8h       Shutdown    35.187.246   7004   gke-node-pool-fb3f8ee9-rvpw   11m
royale-server-odd-d5wnz-b4877       Ready       35.240.183   7081   gke-node-pool-fb3f8ee9-lw1p   14m
royale-server-odd-d5wnz-cw76d       Ready       35.240.183   7923   gke-node-pool-fb3f8ee9-lw1p   3m
royale-server-odd-d5wnz-d45mk       Ready       35.240.183   7732   gke-node-pool-fb3f8ee9-lw1p   21m
royale-server-odd-d5wnz-dx9vw       Allocated   34.87.124.   7266   gke-node-pool-157ec1db-kbq3   8h
royale-server-odd-d5wnz-qxgmz       Allocated   35.247.128   7202   gke-node-pool-157ec1db-mgh3   8h
royale-server-odd-d5wnz-wtbkz       Ready       34.87.124.   7495   gke-node-pool-157ec1db-kbq3   7s
```

And running `kubectl get pods` returned:
```
NAME                                READY   STATUS        RESTARTS   AGE
deathmatch-server-odd-4fvpv-fjl8q   2/2     Running       0          8h
deathmatch-server-odd-4fvpv-g2dn2   2/2     Running       0          8h
deathmatch-server-odd-4fvpv-nq58m   2/2     Running       0          8h
deathmatch-server-odd-4fvpv-s765b   2/2     Running       5          8h
endless-server-odd-h79b4-5q8ws      2/2     Running       0          20h
endless-server-odd-h79b4-qshqv      2/2     Running       0          8h
exchange-odd-77475599bf-rt77n       1/1     Running       0          14h
lobby-server-odd-znvjb-6wk64        2/2     Running       0          5s
lobby-server-odd-znvjb-7vmbq        2/2     Running       0          30s
lobby-server-odd-znvjb-lmlqt        0/2     Terminating   0          38s
lobby-server-odd-znvjb-tzq8f        2/2     Running       0          54s
lobby-server-odd-znvjb-vshkb        2/2     Running       0          66s
lobby-server-odd-znvjb-w2kc4        2/2     Running       0          79s
lobby-server-odd-znvjb-x5hpd        2/2     Running       0          10m
lobby-server-odd-znvjb-xjnzl        2/2     Running       0          20m
lobby-server-odd-znvjb-xp7h4        2/2     Running       0          17m
lobby-server-odd-znvjb-xrmx9        2/2     Running       0          39m
lobby-server-odd-znvjb-xs57n        2/2     Running       0          22m
lobby-server-odd-znvjb-z6ptt        2/2     Running       0          6m52s
lobby-server-odd-znvjb-zbwnr        2/2     Running       0          16m
lobby-server-odd-znvjb-zc8wl        2/2     Running       0          20m
lobby-server-odd-znvjb-zcx2r        2/2     Running       0          90s
lobby-server-odd-znvjb-zhdw8        2/2     Running       0          15m
lobby-server-odd-znvjb-zjrtd        2/2     Running       0          13m
lobby-server-odd-znvjb-zpffl        2/2     Running       0          34s
lobby-server-odd-znvjb-zs5c4        2/2     Running       0          2m15s
lobby-server-odd-znvjb-ztn96        2/2     Running       0          33m
lobby-server-odd-znvjb-zvjrl        2/2     Running       0          23m
matchmaker-odd-54d4cc75f-8sxb5      1/1     Running       0          8h
messenger-server-odd-8l7ng-fv64c    2/2     Running       0          14h
progression-odd-d46b8674-jkn65      1/1     Running       0          8h
royale-server-odd-d5wnz-8dfsq       2/2     Running       0          2m50s
royale-server-odd-d5wnz-96q8h       2/2     Running       0          9m16s
royale-server-odd-d5wnz-b4877       2/2     Running       0          12m
royale-server-odd-d5wnz-cw76d       2/2     Running       0          75s
royale-server-odd-d5wnz-d45mk       2/2     Running       0          18m
royale-server-odd-d5wnz-t6hf5       2/2     Running       0          25m
```

Unsure, but maybe this might be related: https://github.com/googleforgames/agones/issues/398

**What you expected to happen**: I expected for this to never happen.

**How to reproduce it (as minimally and precisely as possible)**: Unsure as to why Agones controller shut down and why it took this long to restart. so Unsure on how to reproduce. 

**Environment**:
- Agones version:  1.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:20:12Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.15", GitCommit:"7b5157a7c600aa8ee6e2b36b56c478e030d5bfe2", GitTreeState:"clean", BuildDate:"2019-10-07T20:39:12Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCP n1-standard-1
- Install method (yaml/helm): helm

### PR DESCRIPTION
**Pull request by markmandel**
If a Pod gets deleted, especially during GameServer Ready or Allocated state, and the controller is either crashed, missing or unable to access master, when the controller comes back up, the GameServer is left in a zombie state in which it could be Allocated, but there is no Pod process
to back it.

Ideally, scenarios like this shouldn't happen, but it is possible, depending on user interaction with Kubernetes, so we should cover the scenario, as it requires manual intervention to fix otherwise.

This PR implements a controller that periodically checks GameServers to ensure they have backing Pods, such that if this happens the GameServer is marked as Unhealthy, and a Fleet can eventually return to a healed, stable state, and not require manual intervention.

Closes #1170
Closes #398 (especially combined with fix for #1245)

### CODE REVIEW

**Comment by markmandel** [comment]
/cc @KamiMay just letting you know this is in the queue.

Would like to merge it after the stable release, to give it some time to bake.

**Comment by markmandel** [comment]
Pasting here, to keep track. Looks like I introduced a panic.

```
"Reconciling GameServerSet"
Observed a panic: "invalid memory address or nil pointer dereference" (runtime : invalid memory address or nil pointer dereference)
/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:679
/usr/local/go/src/runtime/panic.go:199
/usr/local/go/src/runtime/signal_unix.go:394
/go/src/agones.dev/agones/pkg/gameservers/missing.go:155
/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:153
/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:129
/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:187
/usr/local/go/src/runtime/asm_amd64.s:1357
panic: runtime : invalid memory address or nil pointer dereference [recovered]
panic: runtime : invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12492f4
```

**Comment by markmandel** [comment]
Oooh! I think I know how to e2e test this. Please still free to review, but will add an e2e test shortly.

**Comment by markmandel** [comment]
Added e2e test suite for controller crashes.

File: test/e2e/controller_test.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+// deleteAgonesControllerPods deletes all the Controller pods for the Agones controller,
+// faking a controller crash.
+func deleteAgonesControllerPods() error {
+	list, err := getAgonesControllerPods()
+	if err != nil {
+		return err
+	}
+
+	policy := metav1.DeletePropagationBackground
+	for i := range list.Items {
```
Comment (aLekSer) [inline test/e2e/controller_test.go]: Do we need to remove `agones-allocator` and `agones-ping` pods also? They seem to be not related to this E2E test scenario.

File: test/e2e/controller_test.go [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+	gs := defaultGameServer(defaultNs)
+	readyGs, err := framework.CreateGameServerAndWaitUntilReady(defaultNs, gs)
+	if err != nil {
+		t.Fatalf("Could not get a GameServer ready: %v", err)
+	}
+	logrus.WithField("gsKey", readyGs.ObjectMeta.Name).Info("GameServer Ready")
+
+	gsClient := framework.AgonesClient.AgonesV1().GameServers(defaultNs)
+	podClient := framework.KubeClient.CoreV1().Pods(defaultNs)
+	defer gsClient.Delete(readyGs.ObjectMeta.Name, nil) // nolint: errcheck
```
Comment (aLekSer) [inline test/e2e/controller_test.go]: Can we move this right after err check to line 40?

Comment (markmandel) [reply test/e2e/controller_test.go]: Rearranged! :+1:

**Comment by aLekSer** [comment]
@markmandel  Just was thinking of a Dev Gameserver, I think they might go to unhealthy, is there any E2E test for this case?
```
	// If the game server is a dev server we do not create a pod for it, return an empty pod.
```

**Comment by roberthbailey** [comment]
Can you rebase this so that the commit for the alpha/beta sdk stuff doesn't clutter up the code review?

**Comment by markmandel** [comment]
@aLekSer 

> @markmandel , great implementation. I was thinking of doing this logic on a start of Agones controller, but this approach way better, more general and more state of the art!
>Just was thinking of a Dev Gameserver, I think they might go to unhealthy, is there any E2E test for this case?

That's a great question!

There is a check in here for dev gameservers:
https://github.com/googleforgames/agones/pull/1279/files#diff-d0f163ec75bb0e3e6d1b8db74fda705bR87

And a Unit test as well:
https://github.com/googleforgames/agones/pull/1279/files#diff-7285517b020e1edd73726337f6ba8b8fR258-R262

I didn't write a e2e, as I figure the e2e dev gameserver test would suffice (it would at least fail sometimes). The only way I could think to e2e test it is to wait 30 seconds - but do we want that slow an e2e test?

WDYT?

@roberthbailey rebased!

**Comment by aLekSer** [comment]
That's great that Dev Gameserver now also supported.
I think that we don't need a special E2E test case or make it 30s as long as existent one is able to fail from time to time.

File: pkg/gameservers/missing.go [hunk 3]
```diff
@@ -0,0 +1,157 @@
...
+	k8serrors "k8s.io/apimachinery/pkg/api/errors"
+	"k8s.io/client-go/informers"
+	"k8s.io/client-go/kubernetes"
+	typedcorev1 "k8s.io/client-go/kubernetes/typed/core/v1"
+	corelisterv1 "k8s.io/client-go/listers/core/v1"
+	"k8s.io/client-go/tools/cache"
+	"k8s.io/client-go/tools/record"
+)
+
+// MissingPodController watches makes sure that any GameServer
```
Comment (roberthbailey) [inline pkg/gameservers/missing.go]: nit: "watches makes sure" isn't proper grammar.

File: pkg/gameservers/missing.go [hunk 4]
```diff
@@ -0,0 +1,157 @@
...
+// that isn't in Scheduled, or Unhealthy/Error state, that is missing a Pod
```
Comment (roberthbailey) [inline pkg/gameservers/missing.go]: This has too many commas. Suggest

"any GameServer that isn't in Schedule or Unhealthy/Error state and is missing a pod is moved to Unhealthy"

File: pkg/gameservers/missing.go [hunk 5]
```diff
@@ -0,0 +1,157 @@
...
+// moved to Unhealthy. This can sometimes happen if the controller has downtime
```
Comment (roberthbailey) [inline pkg/gameservers/missing.go]: "This" should be expanded since the previous sentence is a mouthful and it's difficult to tell what "this" refers to.  Maybe "It's possible that a GameServer is missing its associated pod due to unexpected controller downtime or if the Pod disappears with no Delete event"

File: pkg/gameservers/missing.go [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+	recorder         record.EventRecorder
+}
+
+// NewMissingPodController returns a MissingPodController
+func NewMissingPodController(health healthcheck.Handler,
+	kubeClient kubernetes.Interface,
+	agonesClient versioned.Interface,
+	kubeInformerFactory informers.SharedInformerFactory,
+	agonesInformerFactory externalversions.SharedInformerFactory) *MissingPodController {
+
```
Comment (roberthbailey) [inline pkg/gameservers/missing.go]: nit: empty line seems unnecessary.

File: pkg/gameservers/missing.go [hunk 7]
```diff
@@ -0,0 +1,157 @@
...
+	eventBroadcaster := record.NewBroadcaster()
+	eventBroadcaster.StartLogging(c.baseLogger.Debugf)
+	eventBroadcaster.StartRecordingToSink(&typedcorev1.EventSinkImpl{Interface: kubeClient.CoreV1().Events("")})
+	c.recorder = eventBroadcaster.NewRecorder(scheme.Scheme, corev1.EventSource{Component: "missing-pod-controller"})
+
+	gameServers.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
+		UpdateFunc: func(_, newObj interface{}) {
+			gs := newObj.(*agonesv1.GameServer)
+			_, isDev := gs.GetDevAddress()
```
Comment (roberthbailey) [inline pkg/gameservers/missing.go]: nit: can be written as

`if _, isDev := gs.GetDevAddress(); !isDev && !isBeforePodCreated(gs) && !gs.IsBeingDeleted() && !gs.IsUnhealthy() { ... }`

to reduce the scope of the `isDev` variable.

File: pkg/gameservers/missing.go [hunk 8]
```diff
@@ -0,0 +1,157 @@
...
+		runtime.HandleError(c.loggerForGameServerKey(key), errors.Wrapf(err, "invalid resource key"))
+		return nil
+	}
+
+	// check if the pod exists
+	if pod, err := c.podLister.Pods(namespace).Get(name); err != nil {
+		if !k8serrors.IsNotFound(err) {
+			return errors.Wrapf(err, "error retrieving Pod %s from namespace %s", name, namespace)
+		}
+		c.loggerForGameServerKey(key).Debug("Pod is missing. Moving GameServer to Unhealthy.")
```
Comment (roberthbailey) [inline pkg/gameservers/missing.go]: It seems like this log line should be after the if statement. If the pod is found and it's not a game server pod, then we won't get this log line but we will still try to move the game server to unhealthy.

File: pkg/gameservers/missing.go [hunk 9]
```diff
@@ -0,0 +1,157 @@
...
+		if k8serrors.IsNotFound(err) {
+			c.loggerForGameServerKey(key).Debug("GameServer is no longer available for syncing")
+			return nil
+		}
+		return errors.Wrapf(err, "error retrieving GameServer %s from namespace %s", name, namespace)
+	}
+
+	// already on the way out, so no need to do anything.
+	if gs.IsBeingDeleted() || gs.IsUnhealthy() {
+		return nil
```
Comment (roberthbailey) [inline pkg/gameservers/missing.go]: Please add a debug line here as well, so that we can see when this branch gets hit in the logs.

File: pkg/gameservers/gameservers.go [hunk 10]
```diff
@@ -75,3 +75,11 @@ func applyGameServerAddressAndPort(gs *agonesv1.GameServer, node *corev1.Node, p
 
 	return gs, nil
 }
+
+// isBeforePodCreated checks to see if the GameServer is in a state in which the pod could not have been
+// created yet. This includes "Starting" in which a pod MAY exist, but may not yet be available, depending on when the
+// informer cache updates
+func isBeforePodCreated(gs *agonesv1.GameServer) bool {
```
[the remark this answers is not in the document]
Comment (markmandel) [reply pkg/gameservers/gameservers.go]: That a really good question!

So, reviewing this, I decided to get rid of this IsUnhealthy() implementation, because I realised that Error state should represent something catastrophic (like an invalid podspec), and shouldn't delete and restart.

My original thought was to start using gs.IsUnhealthy() all over the place - so put it everywhere where there was a check for `Unhealthy` state. But your comment made me think about this more, and I realised it wasn't a good idea.

That being said, my thought was - `isUnhealthy()` was really useful on a wider scale, whereas `isBeforePodCreated()` was only useful in this particular instance (that I could think of), so I left it in /pkg/gameservers/ .

File: pkg/gameservers/missing.go (hunk 5 above)
Comment (markmandel) [reply pkg/gameservers/missing.go]: Nice.

File: pkg/gameservers/missing.go (hunk 7 above)
Comment (markmandel) [reply pkg/gameservers/missing.go]: I'm coming back for a secondary review. I'm not sure if moving this into the one line makes it harder to read or not.

Current:
```golang
       gameServers.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
		UpdateFunc: func(_, newObj interface{}) {
			gs := newObj.(*agonesv1.GameServer)
			_, isDev := gs.GetDevAddress()
			if !isDev && !isBeforePodCreated(gs) && !gs.IsBeingDeleted() &&
				!(gs.Status.State == agonesv1.GameServerStateUnhealthy) {
				c.workerqueue.Enqueue(gs)
			}
		},
	})
```

becomes this:

```golang
	gameServers.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
		UpdateFunc: func(_, newObj interface{}) {
			gs := newObj.(*agonesv1.GameServer)
			if _, isDev := gs.GetDevAddress();
			!isDev && !isBeforePodCreated(gs) && !gs.IsBeingDeleted() &&
				!(gs.Status.State == agonesv1.GameServerStateUnhealthy) {
				c.workerqueue.Enqueue(gs)
			}
		},
	})
```

WDYT?

File: pkg/gameservers/missing.go (hunk 8 above)
Comment (markmandel) [reply pkg/gameservers/missing.go]: Good catch!

File: pkg/gameservers/missing.go (hunk 9 above)
Comment (markmandel) [reply pkg/gameservers/missing.go]: Nice. Done.

File: pkg/gameservers/missing_test.go [hunk 11]
```diff
@@ -0,0 +1,263 @@
...
+	"github.com/stretchr/testify/assert"
+	corev1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/runtime"
+	"k8s.io/apimachinery/pkg/watch"
+	k8stesting "k8s.io/client-go/testing"
+	"k8s.io/client-go/tools/cache"
+)
+
+func TestIsBeforePodCreated(t *testing.T) {
```
Comment (roberthbailey) [inline pkg/gameservers/missing_test.go]: I think this comment was lost in my last review, but this test seems like it belongs in `pkg/gameservers/gameservers_test.go` instead of here, since it's testing code in `pkg/gameservers/gameservers.go`

File: pkg/gameservers/gameservers.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (roberthbailey) [reply pkg/gameservers/gameservers.go]: 👍

File: pkg/gameservers/missing.go (hunk 7 above)
Comment (roberthbailey) [reply pkg/gameservers/missing.go]: I find it easier because I'm used to that style.

File: pkg/gameservers/missing_test.go (hunk 11 above)
Comment (markmandel) [reply pkg/gameservers/missing_test.go]: oooh! yeah. Moving!
