### PR TITLE
Populate Env Vars for GameServer init containers

### LINKED ISSUE #4241: AGONES_SDK_GRPC_PORT and AGONES_SDK_HTTP_PORT should also be populated for init containers
**What happened**:
The environment variables ```AGONES_SDK_GRPC_PORT``` and ```AGONES_SDK_HTTP_PORT``` are not being injected into init containers of GameServer pods. These variables are correctly populated for the main game server container but are missing from any init containers defined in the GameServer specification.

**What you expected to happen**:
Both ```AGONES_SDK_GRPC_PORT``` and ```AGONES_SDK_HTTP_PORT``` environment variables should be automatically injected into all containers within the GameServer pod, including init containers. This would allow init containers to interact with the Agones SDK during the initialization phase, enabling use cases such as:
- Pre-game configuration validation via SDK
- Health check setup before main container starts
- Game state initialization that requires SDK communication

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a GameServer with an init container:
```yaml
apiVersion: agones.dev/v1
kind: GameServer
metadata:
  name: test-gameserver
spec:
  ports:
  - name: default
    containerPort: 7654
  template:
    spec:
      initContainers:
      - name: init-container
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: 
        - |
          echo "AGONES_SDK_GRPC_PORT: $AGONES_SDK_GRPC_PORT"
          echo "AGONES_SDK_HTTP_PORT: $AGONES_SDK_HTTP_PORT"
          env | grep AGONES
      containers:
      - name: simple-game-server
        image: us-docker.pkg.dev/agones-images/examples/simple-game-server:latest
```
2. Apply the GameServer: ```kubectl apply -f gameserver.yaml```
3. Check init container logs: ```kubectl logs <pod-name> -c init-container```
4. Observe that AGONES_SDK_GRPC_PORT and AGONES_SDK_HTTP_PORT are empty or not present
5. Compare with main container: ```kubectl exec <pod-name> -c simple-game-server -- env | grep AGONES```
6. Notice that the main container has these variables properly set

**Anything else we need to know?**:
- This issue prevents init containers from using the Agones SDK client libraries
- Workaround currently requires hardcoding the default ports (9357 for gRPC, 9358 for HTTP) in init containers
- The SDK sidecar is running and accessible during init container execution, but without the port environment variables, SDK clients cannot automatically connect

### PR DESCRIPTION
**Pull request by giornetta**
**What type of PR is this?**
/kind bug

**What this PR does / Why we need it**:
This MR adds code to populate environment variables for init containers defined in a `GameServer` spec.

This allows init containers to communicate with the SDK server during initialization, enabling use cases where setup logic needs to interact with Agones APIs before the main game server container starts.

**Which issue(s) this PR fixes**:
Closes #4241

### CODE REVIEW

File: pkg/gameservers/controller.go [hunk 1]
```diff
@@ -832,31 +832,43 @@ func (c *Controller) addGameServerHealthCheck(gs *agonesv1.GameServer, pod *core
 }
 
 func (c *Controller) addSDKServerEnvVars(gs *agonesv1.GameServer, pod *corev1.Pod) {
+	sdkEnvVars := sdkEnvironmentVariables(gs)
+	if sdkEnvVars == nil {
+		// If a gameserver was created before 1.1 when we started defaulting the grpc and http ports,
```
Comment (markmandel) [inline pkg/gameservers/controller.go:837]: I wish I could remember why this is here 🤣

**Review by markmandel — COMMENTED** [review]
Thanks, we needed this!

/gcbrun
