### PR TITLE
Fix allocator metrics endpoint

### LINKED ISSUE #3920: Allocator metrics missing in Agones 1.42.0
According to @vicentefb, #3845 introduced a regression whereby the `agones-allocator` Pod is no longer emitting metrics. We should fix this ASAP.

### PR DESCRIPTION
**Pull request by vicentefb**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
/kind hotfix
> /kind release

**What this PR does / Why we need it**:
The /metrics endpoint for the allocator stopped working after #3845. 

**Which issue(s) this PR fixes**:
Closes #3920

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by vicentefb** [comment]
image

File: cmd/allocator/main.go [hunk 1]
```diff
@@ -306,6 +309,9 @@ func main() {
 		}
 	}
 
+	err = http.ListenAndServe(":8080", http.DefaultServeMux)
+	logger.WithError(err).Fatal("allocation service crashed")
+
```
Comment (vicentefb) [inline cmd/allocator/main.go:314]: If I move these two lines to happen at the end of the function, /metrics stops working. But if I leave it here, it will shadow lines 316-328, basically everything below it.

**Review by zmerlynn — APPROVED** [review]
