### PR TITLE
Fix parsing the media type in GameServerAllocation

### LINKED ISSUE #1748: Content-Type: application/json; charset=utf-8 results in "Could not find deserializer"
**What happened**:
Hi, I'm still new to k8s and agones, so it might be my fault.. I'm using the Java Generic Kubernetes API and created/generated the classes for the agones CRDs. Reading the resources was fine, but creating new Resources failed. This is from the agones-allocator:

``` 
{
  "error": "Could not find deserializer",
  "headers": {
    "Accept": [
      "application/json"
    ],
    "Accept-Encoding": [
      "gzip"
    ],
    "Content-Length": [
      "186"
    ],
    "Content-Type": [
      "application/json; charset=utf-8"
    ],
    "User-Agent": [
      "OpenAPI-Generator/1.0-SNAPSHOT/java"
    ],
    "X-Forwarded-For": [
      "192.168.178.136"
    ],
    "X-Forwarded-Host": [
      "10.99.197.45:443"
    ],
    "X-Forwarded-Proto": [
      "https"
    ],
    "X-Forwarded-Uri": [
      "/apis/allocation.agones.dev/v1/namespaces/mynamespace/gameserverallocations"
    ],
    "X-Remote-Group": [
      "system:masters",
      "system:authenticated"
    ],
    "X-Remote-User": [
      "minikube-user"
    ]
  },
  "host": "10.99.197.45:443",
  "message": "",
  "method": "POST",
  "requestURI": "/apis/allocation.agones.dev/v1/namespaces/mynamespace/gameserverallocations",
  "severity": "error",
  "source": "*apiserver.APIServer",
  "time": "2020-08-12T18:56:23.905144673Z",
  "url": {
    "Scheme": "",
    "Opaque": "",
    "User": null,
    "Host": "",
    "Path": "/apis/allocation.agones.dev/v1/namespaces/mynamespace/gameserverallocations",
    "RawPath": "",
    "ForceQuery": false,
    "RawQuery": "",
    "Fragment": ""
  }
}
{
  "message": "Could not find deserializer",
  "severity": "error",
  "stack": [
    "agones.dev/agones/pkg/gameserverallocations.(*Controller).allocationDeserialization\n\t/go/src/agones.dev/agones/pkg/gameserverallocations/controller.go:180",
    "agones.dev/agones/pkg/gameserverallocations.(*Controller).processAllocationRequest\n\t/go/src/agones.dev/agones/pkg/gameserverallocations/controller.go:131",
    "agones.dev/agones/pkg/gameserverallocations.(*Controller).registerAPIResource.func1\n\t/go/src/agones.dev/agones/pkg/gameserverallocations/controller.go:93",
    "agones.dev/agones/pkg/util/apiserver.(*APIServer).resourceHandler.func1\n\t/go/src/agones.dev/agones/pkg/util/apiserver/apiserver.go:152",
    "agones.dev/agones/pkg/util/https.ErrorHTTPHandler.func1\n\t/go/src/agones.dev/agones/pkg/util/https/https.go:52",
    "net/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2012",
    "net/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2387",
    "net/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2807",
    "net/http.initALPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3381",
    "net/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5720",
    "runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"
  ],
  "time": "2020-08-12T18:56:23.905438557Z"
}
```

**What you expected to happen**:
It should work with 'Content-Type: application/json; charset=utf-8' 

**How to reproduce it (as minimally and precisely as possible)**:
Create a fleet for namespace mynamespace as in the guide but try to allocate via the REST api instead using kubectl.
```
APISERVER=https://kubernetes.default.svc
SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
TOKEN=$(cat ${SERVICEACCOUNT}/token)
CACERT=${SERVICEACCOUNT}/ca.crt

curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X POST -H 'Content-Type: application/json; charset=utf-8' --data '
{
   "apiVersion": "allocation.agones.dev/v1",
   "kind": "GameServerAllocation",
   "spec": {
      "required": {
         "matchLabels": {
            "agones.dev/fleet": "simple-udp"
         }
      }
   }
}
' ${APISERVER}/apis/allocation.agones.dev/v1/namespaces/mynamespace/gameserverallocations
```

**Anything else we need to know?**:
I tried to find where the "; charset=utf-8" is getting added. I debugged the the java client, but in there it's always just "application/json". It might be added later.

**Environment**:
- Agones version: 
agones-1.7.0

- Kubernetes version (use `kubectl version`):
Minikube
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Plat form:"windows/amd64"}                                                                                                                                                                                                             Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Plat form:"linux/amd64"}

- Cloud provider or hardware configuration:
VirtualBox

- Install method (yaml/helm):
helm v3.2.4

- Troubleshooting guide log(s):
- Others:
Thanks!

### PR DESCRIPTION
**Pull request by aLekSer**
Add a call to filter out optional parameters send in an HTTP header.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

**What this PR does / Why we need it**:
There are parameters like `charset` which would coexist in `Content-Type` header. That's lead `runtime.SerializerInfoForMediaType` to fail, because unexpected parameter was provided.

**Which issue(s) this PR fixes**:

Closes #1748 .

**Special notes for your reviewer**:
Thanks @markmandel for providing the solution in the issue comment

**Steps to reproduce**:
Proof of the fix:
```
export APISERVER=localhost:8001
$ kubectl proxy &
$ curl -X POST -H 'Content-Type: application/json; charset=utf-8' --data '
{
   "apiVersion": "allocation.agones.dev/v1",
   "kind": "GameServerAllocation",
   "spec": {
      "required": {
         "matchLabels": {
            "agones.dev/fleet": "simple-udp"
         }
      }
   }
}
' ${APISERVER}/apis/allocation.agones.dev/v1/namespaces/default/gameserverallocations
{"kind":"GameServerAllocation","apiVersion":"allocation.agones.dev/v1","metadata":{"name":"simple-udp-xv6d5-g4zsd","namespace":"default","creationTimestamp":"2020-08-13T09:05:15Z"},"spec":{"multiClusterSetting":{"policySelector":{}},"required":{"matchLabels":{"agones.dev/fleet":"simple-udp"}},"scheduling":"Packed","metadata":{}},"status":{"state":"Allocated","gameServerName":"simple-udp-xv6d5-g4zsd","ports":[{"name":"default","port":7870}],"address":"34.82.245.95","nodeName":"gke-test-cluster-default-dfffabe4-t97g"}}
```

### CODE REVIEW

File: pkg/gameserverallocations/controller.go [hunk 1]
```diff
@@ -175,7 +176,11 @@ func (c *Controller) allocationDeserialization(r *http.Request, namespace string
 	gsa.TypeMeta = metav1.TypeMeta{Kind: gvks[0].Kind, APIVersion: gvks[0].Version}
 
 	mediaTypes := scheme.Codecs.SupportedMediaTypes()
-	info, ok := k8sruntime.SerializerInfoForMediaType(mediaTypes, r.Header.Get("Content-Type"))
+	mt, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
+	if err != nil {
+		return gsa, err
```
Comment (markmandel) [inline pkg/gameserverallocations/controller.go:181]: can we errors.Wrapf(....) this error message before passing it back out, so we can capture context?

Outside of that, this looks good to go.

**Comment by aLekSer** [comment]
Tested latest version:
```
 curl -X POST -H 'Content-Type: application/json; charset=utf-8' --data '
{
   "apiVersion": "allocation.agones.dev/v1",
   "kind": "GameServerAllocation",
   "spec": {
      "required": {
         "matchLabels": {
            "agones.dev/fleet": "simple-udp"
         }
      }
   }
}
' ${APISERVER}/apis/allocation.agones.dev/v1/namespaces/default/gameserverallocations
{"kind":"GameServerAllocation","apiVersion":"allocation.agones.dev/v1","metadata":{"name":"simple-udp-pb8kx-v4fq8","namespace":"default","creationTimestamp":"2020-08-13T17:11:29Z"},"spec":{"multiClusterSetting":{"policySelector":{}},"required":{"matchLabels":{"agones.dev/fleet":"simple-udp"}},"scheduling":"Packed","metadata":{}},"status":{"state":"Allocated","gameServerName":"simple-udp-pb8kx-v4fq8","ports":[{"name":"default","port":7042}],"address":"34.82.245.95","nodeName":"gke-test-cluster-default-dfffabe4-t97g"}}
```

File: pkg/gameserverallocations/controller.go [hunk 2]
```diff
@@ -175,7 +176,11 @@ func (c *Controller) allocationDeserialization(r *http.Request, namespace string
 	gsa.TypeMeta = metav1.TypeMeta{Kind: gvks[0].Kind, APIVersion: gvks[0].Version}
 
 	mediaTypes := scheme.Codecs.SupportedMediaTypes()
-	info, ok := k8sruntime.SerializerInfoForMediaType(mediaTypes, r.Header.Get("Content-Type"))
+	mt, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
+	if err != nil {
+		return gsa, errors.Wrap(err, "error parsing mediatype from a request header")
```
Comment (markmandel) [inline pkg/gameserverallocations/controller.go:181]: Fantastic!
