### PR TITLE
Fix sdkserver updatelist gameserver max items

### LINKED ISSUE #4282: sdkserver UpdateList does not respect gameservers.lists.maxItems
A new feature was introduced #4246 to make the maximum number of items in a list configurable via the gameservers.lists.maxItems Helm value.

However, the UpdateList sdkserver still uses a hardcoded limit of 1000 (this does not apply any other List method such as AddListValue or RemoveListValue).

https://github.com/googleforgames/agones/blob/409a6fc3e96d82bda9a16fb10b6288d82c5fd356/pkg/sdkserver/sdkserver.go#L1082-L1084
https://github.com/googleforgames/agones/blob/409a6fc3e96d82bda9a16fb10b6288d82c5fd356/pkg/util/apiserver/apiserver.go#L64. The UpdateList function in pkg/sdkserver/sdkserver.go checks the capacity against apiserver.ListMaxCapacity

This means that even if a user configures a different `gameservers.lists.maxItems`, the SDK will still enforce a limit of 1000.

To fix this, sdkserver should be updated to retrieve the gameservers.lists.maxItems value and use it for validation and remove the `apiserver.ListMaxCapacity`.

### PR DESCRIPTION
**Pull request by Sivasankaran25**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #4282

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/apis/agones/v1/gameserver.go [hunk 1]
```diff
@@ -1022,7 +1026,8 @@ func (gs *GameServer) UpdateCounterCapacity(name string, capacity int64) error {
 
 // UpdateListCapacity updates the ListStatus Capacity to the given capacity.
 func (gs *GameServer) UpdateListCapacity(name string, capacity int64) error {
-	if capacity < 0 || capacity > apiserver.ListMaxCapacity {
+
+	if capacity < 0 || capacity > ListMaxCapacity {
```
Comment (igooch) [inline pkg/apis/agones/v1/gameserver.go:1030]: This should not be hard-coded to 1000. The point of this PR is to use in the value of `gameservers.lists.maxItems` and not a hard-coded value. `gameservers.lists.maxItems` already defaults to 1000 if a user does not specify a value.

Comment (Sivasankaran25) [reply pkg/apis/agones/v1/gameserver.go:1030]: Yeah Correct, but without the gameserver config the test cases run. Since gameservers.lists.maxItems is only available after fetching, it causes an error, so I used a hard-coded value.

**Comment by markmandel** [comment]
Flaky unit test:

```
{"message":"unable to calculate 'Ready' state duration of 's2v9llhh4v1' GameServer","severity":"warning","source":"*metrics.Controller","time":"2025-12-17T23:54:54.815475533Z"}
--- FAIL: TestControllerGameServerCount (2.11s)
    controller_test.go:88: 
        	Error Trace:	/go/src/agones.dev/agones/pkg/metrics/controller_test.go:88
        	            				/go/src/agones.dev/agones/pkg/metrics/controller_test.go:289
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestControllerGameServerCount
        	Messages:   	metric: gameservers_count, tags: [{none true} {default true} {PortAllocation true}], values don't match; got: 1, want: 2
{"message":"Wait for cache sync","severity":"info","time":"2025-12-17T23:54:54.818099822Z"}
```

Haven't seen that one before!

/gcbrun

**Comment by lacroixthomas** [comment]
> Flaky unit test:
> 
> ```
> {"message":"unable to calculate 'Ready' state duration of 's2v9llhh4v1' GameServer","severity":"warning","source":"*metrics.Controller","time":"2025-12-17T23:54:54.815475533Z"}
> --- FAIL: TestControllerGameServerCount (2.11s)
>     controller_test.go:88: 
>         	Error Trace:	/go/src/agones.dev/agones/pkg/metrics/controller_test.go:88
>         	            				/go/src/agones.dev/agones/pkg/metrics/controller_test.go:289
>         	Error:      	Not equal: 
>         	            	expected: 2
>         	            	actual  : 1
>         	Test:       	TestControllerGameServerCount
>         	Messages:   	metric: gameservers_count, tags: [{none true} {default true} {PortAllocation true}], values don't match; got: 1, want: 2
> {"message":"Wait for cache sync","severity":"info","time":"2025-12-17T23:54:54.818099822Z"}
> ```
> 
> Haven't seen that one before!
> 
> /gcbrun

The hunt of flaky tests continue haha 🎄 🎁

**Comment by markmandel** [comment]
* https://github.com/googleforgames/agones/issues/3553 has returned!

/gcbrun

**Comment by markmandel** [comment]
Wow, we are running into a slew of flakes after having such a good run lately!

```
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.300117927Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc0005121b8), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.330178102Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"\", Version:\"v1\", Resource:\"nodes\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc00029e918), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.336392319Z"}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.408275581Z","x":0}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.409084437Z","x":1}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.409478598Z","x":2}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.409839686Z","x":3}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.410333624Z","x":4}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.410729942Z","x":5}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.411247676Z","x":6}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.411530011Z","x":0}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.415717388Z","x":1}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.415288Z","x":0}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.416492333Z","x":1}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.416995859Z","x":2}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.417310957Z","x":3}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.417744307Z","x":4}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.411431458Z","x":0}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.418957801Z","x":1}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.419443652Z","x":2}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.419889107Z","x":3}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.420325529Z","x":4}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.420804429Z","x":5}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.421269348Z","x":6}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.421640995Z","x":7}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.422078302Z","x":8}
{"i":0,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.422516723Z","x":9}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.418246417Z","x":5}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.42303768Z","x":6}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.411300156Z","x":0}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.423889263Z","x":1}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.424282217Z","x":2}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.424672492Z","x":3}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.425049353Z","x":4}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.425367347Z","x":5}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.425954291Z","x":6}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.426276063Z","x":7}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.426734476Z","x":8}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.41610971Z","x":2}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.427811709Z","x":7}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.435927564Z","x":8}
{"i":4,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.436482305Z","x":9}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.427822515Z","x":3}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.438217961Z","x":4}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.43871888Z","x":5}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.43918493Z","x":6}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.439637512Z","x":7}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.440205056Z","x":8}
{"i":3,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.440879389Z","x":9}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.411667233Z","x":7}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.441692221Z","x":8}
{"i":1,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.442058076Z","x":9}
{"i":2,"message":"allocating!","severity":"info","time":"2025-12-18T01:53:01.427385738Z","x":9}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.446306792Z"}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.44810997Z"}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.449735612Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc0000128b8), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.457608936Z"}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.449802564Z"}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.449992501Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"\", Version:\"v1\", Resource:\"nodes\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc000274298), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.481232589Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc0004a4b48), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.482860882Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc0002743b8), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.49917692Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"\", Version:\"v1\", Resource:\"nodes\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc000512588), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.527299524Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"\", Version:\"v1\", Resource:\"nodes\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc00029e978), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.527655611Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc0004a4cd8), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.512089058Z"}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.555240689Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc000248238), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.557567904Z"}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.588072899Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc0002485b8), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.59032042Z"}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.668704602Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc000248ad8), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.676177123Z"}
{"message":"Allocated Port","ports":[{"range":"default","portPolicy":"Dynamic","containerPort":7777,"hostPort":10},{"name":"another","range":"default","portPolicy":"Dynamic","containerPort":6666,"hostPort":13},{"name":"static","range":"default","portPolicy":"Static","containerPort":6666,"hostPort":9999},{"name":"passthrough","range":"default","portPolicy":"Passthrough","containerPort":15,"hostPort":15}],"severity":"info","time":"2025-12-18T01:53:01.771914864Z","uid":"0:0"}
{"message":"Allocated Port","ports":[{"range":"default","portPolicy":"Dynamic","containerPort":7777,"hostPort":11},{"name":"another","range":"default","portPolicy":"Dynamic","containerPort":6666,"hostPort":12},{"name":"static","range":"default","portPolicy":"Static","containerPort":6666,"hostPort":9999},{"name":"passthrough","range":"default","portPolicy":"Passthrough","containerPort":14,"hostPort":14}],"severity":"info","time":"2025-12-18T01:53:01.77335006Z","uid":"0:1"}
{"message":"Allocated Port","ports":[{"range":"default","portPolicy":"Dynamic","containerPort":7777,"hostPort":16},{"name":"another","range":"default","portPolicy":"Dynamic","containerPort":6666,"hostPort":17},{"name":"static","range":"default","portPolicy":"Static","containerPort":6666,"hostPort":9999},{"name":"passthrough","range":"default","portPolicy":"Passthrough","containerPort":20,"hostPort":20}],"severity":"info","time":"2025-12-18T01:53:01.773758878Z","uid":"0:2"}
{"message":"Allocated Port","ports":[{"range":"default","portPolicy":"Dynamic","containerPort":7777,"hostPort":18},{"name":"another","range":"default","portPolicy":"Dynamic","containerPort":6666,"hostPort":19},{"name":"static","range":"default","portPolicy":"Static","containerPort":6666,"hostPort":9999},{"name":"passthrough","range":"default","portPolicy":"Passthrough","containerPort":20,"hostPort":20}],"severity":"info","time":"2025-12-18T01:53:01.774106469Z","uid":"1:0"}
{"message":"Allocated Port","ports":[{"range":"default","portPolicy":"Dynamic","containerPort":7777,"hostPort":18},{"name":"another","range":"default","portPolicy":"Dynamic","containerPort":6666,"hostPort":10},{"name":"static","range":"default","portPolicy":"Static","containerPort":6666,"hostPort":9999},{"name":"passthrough","range":"default","portPolicy":"Passthrough","containerPort":11,"hostPort":11}],"severity":"info","time":"2025-12-18T01:53:01.77449422Z","uid":"1:1"}
{"message":"Allocated Port","ports":[{"range":"default","portPolicy":"Dynamic","containerPort":7777,"hostPort":12},{"name":"another","range":"default","portPolicy":"Dynamic","containerPort":6666,"hostPort":13},{"name":"static","range":"default","portPolicy":"Static","containerPort":6666,"hostPort":9999},{"name":"passthrough","range":"default","portPolicy":"Passthrough","containerPort":16,"hostPort":16}],"severity":"info","time":"2025-12-18T01:53:01.774957961Z","uid":"1:2"}
{"Allocated":18,"Total":22,"message":"Ports count","severity":"info","time":"2025-12-18T01:53:01.779535478Z"}
{"Allocated":21,"Total":22,"message":"Ports count","severity":"info","time":"2025-12-18T01:53:01.779959789Z"}
{"Allocated":24,"Total":33,"message":"Ports count","severity":"info","time":"2025-12-18T01:53:01.780365807Z"}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.782007263Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc00029f178), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.783935436Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"\", Version:\"v1\", Resource:\"nodes\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc00029f1f8), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.784916751Z"}
{"message":"Wait for cache sync","severity":"info","time":"2025-12-18T01:53:01.885161533Z"}
{"message":"unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}, ListOptions:v1.ListOptions{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, LabelSelector:\"\", FieldSelector:\"\", Watch:true, AllowWatchBookmarks:true, ResourceVersion:\"\", ResourceVersionMatch:\"\", TimeoutSeconds:(*int64)(0xc00029f858), Limit:0, Continue:\"\", SendInitialEvents:(*bool)(nil)}}","severity":"error","time":"2025-12-18T01:53:01.8878336Z"}
--- FAIL: TestPortRangeAllocatorSyncDeleteGameServer (1.13s)
    portallocator_test.go:603: 
        	Error Trace:	/go/src/agones.dev/agones/pkg/portallocator/portallocator_test.go:603
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestPortRangeAllocatorSyncDeleteGameServer
FAIL
FAIL	agones.dev/agones/pkg/portallocator	2.162s
```

/gcbrun
