### PR TITLE
Prevent Int64 Overflow

### LINKED ISSUE #3604: Aggregate Counter Status Errors When Capacity Is Greater Than int64
**What happened**:

When a game server counter capacity is set to max(int64), and the fleet has more than one replica, then the fleet is unable to create game servers because the fleet aggregate counter capacity is 2 * max(int64), which errors.

When the game server counter capacity is max(int64) / replicas, then there is no issue, and the fleet is able to create the game servers.

**What you expected to happen**:

I would expect the fleet to still be able to create the game servers with max(int64).

**How to reproduce it (as minimally and precisely as possible)**:

Install Agones with CountsAndLists set to true.
Apply the below fleet.yaml:

```
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: simple-game-server
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          containerPort: 7654
      counters:
        sessions:
          count: 0
          capacity: 9223372036854775807
      template:
        spec:
          containers:
            - name: simple-game-server
              image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.24
```

**Environment**:
- Agones version: 1.38.0-dev
- Kubernetes version (use `kubectl version`): v1.28.5
- Cloud provider or hardware configuration: v1.28.3-gke.1203001
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): 
From the agones-controller:
```
"status": {
      "code": 9,
      "message": "GameServer.agones.dev \"simple-game-server-shxn9-dffx9\" is invalid: status.counters.sessions.capacity: Invalid value: \"number\": status.counters.sessions.capacity in body must be of type integer: \"number\""
    }
```

**Anything else we need to know?**:

Suggested resolution:

In cases where the `AggregatedCounterStatus` number would be greater than max(int64), then max(int64).
  - `updateFleetStatus` in agones/pkg/fleets/controller.go
  - `aggregateCounters` in agones/pkg/gameserversets/controller.go

We would also need to add documentation that anything that aggregates past max(int64) maxes out aggregating, and potentially breaks fleet autoscaling based on counter status.

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #3604 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/fleets/controller.go [hunk 1]
```diff
@@ -721,6 +722,14 @@ func (c *Controller) filterGameServerSetByActive(fleet *agonesv1.Fleet, list []*
 	return active, rest
 }
 
+// SafeAdd prevents overflow by limiting the sum to math.MaxInt64.
+func SafeAdd(x, y int64) int64 {
```
Comment (igooch) [inline pkg/fleets/controller.go:726]: This function should probably go in `pkg/apis/agones/v1/common.go`

**Review by igooch — COMMENTED** [review]
Could you also add in unit tests for the functionality? They can go in `TestControllerUpdateFleetCounterStatus` for the fleet controller and `TestComputeStatus` for the gameserverset controller.

File: pkg/fleets/controller_test.go [hunk 2]
```diff
@@ -752,20 +752,20 @@ func TestControllerUpdateFleetCounterStatus(t *testing.T) {
...
-			assert.Equal(t, int64(11), fleet.Status.Counters["anotherCounter"].AllocatedCount)
-			assert.Equal(t, int64(20), fleet.Status.Counters["anotherCounter"].AllocatedCapacity)
-			assert.Equal(t, int64(200), fleet.Status.Counters["anotherCounter"].Capacity)
-			assert.Equal(t, int64(42), fleet.Status.Counters["anotherCounter"].Count)
-
-			assert.Equal(t, int64(21), fleet.Status.Counters["thirdCounter"].AllocatedCount)
-			assert.Equal(t, int64(30), fleet.Status.Counters["thirdCounter"].AllocatedCapacity)
-			assert.Equal(t, int64(400), fleet.Status.Counters["thirdCounter"].Capacity)
-			assert.Equal(t, int64(21), fleet.Status.Counters["thirdCounter"].Count)
+			assert.Equal(t, agonesv1.SafeAdd(1000, 100), fleet.Status.Counters["fullCounter"].AllocatedCount)
```
Comment (igooch) [inline pkg/fleets/controller_test.go:755]: Here we want to leave `assert.Equal(t, int64(21), fleet.Status.Counters["thirdCounter"].Count)`. The `err := c.updateFleetStatus(ctx, fleet)` will call the SafeAdd as part of the method, so that's part of what we're testing.

File: pkg/gameserversets/controller_test.go [hunk 3]
```diff
@@ -380,16 +380,16 @@ func TestComputeStatus(t *testing.T) {
 			AllocatedReplicas: 1,
 			Counters: map[string]agonesv1.AggregatedCounterStatus{
 				"firstCounter": {
-					AllocatedCount:    5,
-					AllocatedCapacity: 10,
-					Count:             50,
-					Capacity:          85,
+					AllocatedCount:    agonesv1.SafeAdd(5, 0),
```
Comment (igooch) [inline pkg/gameserversets/controller_test.go:383]: For these we'll want to leave as plain int64. 

You can add another Counter under multiple game servers similar to:
```
		gs1.Status.Counters = map[string]agonesv1.CounterStatus{
			"firstCounter":  {Count: 5, Capacity: 10},
			"secondCounter": {Count: 100, Capacity: 1000},
			"fullCounter":   {Count: 9223372036854775807, Capacity: 9223372036854775807},
		}
```

And under expected add:

```
				"fullCounter": {
					AllocatedCount:    9223372036854775807,
					AllocatedCapacity: 9223372036854775807,
					Count:             9223372036854775807,
					Capacity:          9223372036854775807,
				},
```

**Comment by igooch** [comment]
A general comment is that we noted there's an issue with jsonpatch here https://github.com/googleforgames/agones/blob/eb4035e1f78e7a8e0c147a013a5405f904ab9899/pkg/gameservers/controller.go#L260C21-L273 that's preventing the game server from taking an actual max(int64) value. There's a fix in a different json package https://github.com/evanphx/json-patch/pull/194, but we need to incorporate that into our code.

All that is to say this code mostly looks good, but the game server won't currently take max(int64) due to a separate bug. I don't think this PR needs to wait on that code, we can solve that issue separately.

**Comment by markmandel** [comment]
> All that is to say this code mostly looks good, but the game server won't currently take max(int64) due to a separate bug. I don't think this PR needs to wait on that code, we can solve that issue separately.

+1 on this.

**Review by igooch — APPROVED** [review]

**Review by markmandel — APPROVED** [review]
LGTM me too. Can come out of draft.
