### PR TITLE
fix: ensure fleet autoscaler policy are namespaced

### LINKED ISSUE #3954: FleetAutoscaler with Counter policy trying to scale Fleet to negative replicas count
**What happened**:
I had an issue with the fleet auto scaler trying to scale to -41 replicas. 
As I see, fleet auto scaler with Counter policy does not respect the game server's namespace when calculating the current game server count.
I have different namespaces like qa1, qa2, etc., and each has a fleet **my-fleet**, where 1-2 game servers are launched.
I did debug and saw that [ListGameServersByFleetOwner](https://github.com/googleforgames/agones/blob/049de2fbbe8d548e68a79e548dd0d05bb37d8636/pkg/fleetautoscalers/fleetautoscalers.go#L369C24-L369C51) returned all game servers in a cluster with fleet owner name **my-fleet**.
I'm expecting that fleet and game servers are namespaced resources.
I did the simple fix - we just added namespace name to fleet name, like **my-fleet-qa1**, **my-fleet-qa2**

**What you expected to happen**:
Fleet is the namespaced resource. I need to be able to create a fleet with the same name in different namespaces with CountsAndLists policy.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create 2 fleets with the same name in different namespaces.
2. Create 2 fleet autoscaler with Counter policy
3. Just autoscale them.

**Anything else we need to know?**:
-

**Environment**:
- Agones version: 1.42
- Kubernetes version (use `kubectl version`): 1.29
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): 
- Others:

### PR DESCRIPTION
**Pull request by lacroixthomas**
**What type of PR is this?**
/kind bug

**What this PR does / Why we need it**:
Ensure the fleet autoscaler policy are namespaced, to ensure it's not autoscaling on all namespaces (on fleet with same name but from different namespaces)

**Which issue(s) this PR fixes**:
Closes #3954 

**Special notes for your reviewer**:
Did some manual tests following the steps described on the issue. 

TODO:
- [x] Manual testing
- [x] Make sure the `syncFleet()` and the `updateFleet()` are also namespaced
- [x] Fixed current unit tests

### CODE REVIEW

File: pkg/fleets/fleets.go [hunk 1]
```diff
@@ -44,10 +44,10 @@ func ListGameServerSetsByFleetOwner(gameServerSetLister listerv1.GameServerSetLi
 
 // ListGameServersByFleetOwner lists all GameServers that belong to a fleet through the
 // GameServer -> GameServerSet -> Fleet owner chain
-func ListGameServersByFleetOwner(gameServerLister listerv1.GameServerLister,
+func ListGameServersByFleetOwner(gameServerNamespacedLister listerv1.GameServerNamespaceLister,
```
Comment (lacroixthomas) [inline pkg/fleets/fleets.go:47]: We most probably want to do the same for the `ListGameServerSetsByFleetOwner()`, it seems to be expected to work by namespace, but it's not the case (for the `syncFleet()` and `updateFleet()`

File: pkg/fleetautoscalers/controller.go [hunk 2]
```diff
@@ -313,7 +313,8 @@ func (c *Controller) syncFleetAutoscaler(ctx context.Context, key string) error
 	}
 
 	currentReplicas := fleet.Status.Replicas
-	desiredReplicas, scalingLimited, err := computeDesiredFleetSize(fas.Spec.Policy, fleet, c.gameServerLister, c.counter.Counts())
+	gameServerNamespacedLister := c.gameServerLister.GameServers(fleet.Namespace)
```
Comment (lacroixthomas) [inline pkg/fleetautoscalers/controller.go:316]: Set the lister namespaced at this level as the whole controller is based per namespaces

**Comment by igooch** [comment]
Would you be able to add a test that tests for the issue in the original issue? I.e. a test that ensures that two fleets with the same name in different namespaces scale up independently?

**Comment by lacroixthomas** [comment]
> Would you be able to add a test that tests for the issue in the original issue? I.e. a test that ensures that two fleets with the same name in different namespaces scale up independently?

Yes, I'm gonna do that, I would imagine an e2e test ? 

Currently, it seems that the namespace is set by the `e2eframework`, it only expect a single namespace https://github.com/googleforgames/agones/blob/main/test/e2e/framework/framework.go#L168, I can have a look on how to managed multiple ones at the same time

**Comment by lacroixthomas** [comment]
Actually, this could be something similar to the allocator one: https://github.com/googleforgames/agones/blob/main/test/e2e/allocator_test.go#L564C6-L564C33 

Will add the e2e test this week

**Comment by lacroixthomas** [comment]
My e2e test is not valid, it's also passing on the `main` branch, will come back to it this week

**Review by markmandel — APPROVED** [review]
LGTM. Nice change.
