### PR TITLE
Fix: patch flaky tests from submit-upgrade-test-cloud-build

### LINKED ISSUE #4235: [Flacky pipeline]: Flaky test from submit-upgrade-test-cloud-build
**What happened:**
The step Step 25: submit-upgrade-test-cloud-build is flaky and works one every x times

**What you expected to happen:**
It should pass all the time (if no issue on the test itself)

**How to reproduce it (as minimally and precisely as possible):**
Run a pipeline

This is the logs we got:
```
Job completed successfully on cluster associated with log: /tmp/tmp.qakD2oDHTr/gke-autopilot-upgrade-test-cluster-1-31.log
Reading output from log file: /tmp/tmp.qakD2oDHTr/gke-autopilot-upgrade-test-cluster-1-33.log:
{
  "lastProbeTime": "2025-07-31T00:09:43Z",
  "lastTransitionTime": "2025-07-31T00:09:43Z",
  "message": "Job has reached the specified backoff limit",
  "reason": "BackoffLimitExceeded",
  "status": "True",
  "type": "FailureTarget"
}
Unexpected job status: 'FailureTarget' with message: 'Job has reached the specified backoff limit' in log /tmp/tmp.qakD2oDHTr/gke-autopilot-upgrade-test-cluster-1-33.log
ERROR: Upgrade test failed on cluster: gke-autopilot-upgrade-test-cluster-1-33
```

Seems that the helm uninstall of agones is failing because there is still gameservers running

**Anything else we need to know?:**

### PR DESCRIPTION
**Pull request by lacroixthomas**
**What type of PR is this?**
/kind bug

**What this PR does / Why we need it**:
Fix flaky test from submit-upgrade-test-cloud-build

Ensure the gameserver are shuting down before uninstall helmrelease

**Which issue(s) this PR fixes**:

Closes #4235

**Special notes for your reviewer**:

### CODE REVIEW

File: test/upgrade/main.go [hunk 1]
```diff
@@ -336,8 +336,47 @@ func runConfigWalker(ctx context.Context, validConfigs []*configTest) {
 		time.Sleep(1 * time.Minute)
 	}
 	cancel()
-	// TODO: Replace sleep with wait for the existing healthy Game Servers finish naturally by reaching their shutdown phase.
-	time.Sleep(30 * time.Second)
+
```
Comment (markmandel) [inline test/upgrade/main.go]: Whoops! That one fell through the cracks. Glad to the TODO was there to provide guideance.

LGTM, but would like @igooch to triple check as she was the one who originally wrote this.

**Review by markmandel — APPROVED** [review]

**Comment by lacroixthomas** [comment]
Well, that's new..  https://console.cloud.google.com/cloud-build/builds/5096077b-a0db-473a-97d0-87320db99856;step=0?inv=1&invt=Ab4lyw&project=agones-images 
```
ERROR: failed to solve: executor failed running [/bin/sh -c curl -L  ${HELM_URL} > /tmp/helm.tar.gz     && tar -zxvf /tmp/helm.tar.gz -C /tmp     && mv /tmp/linux-amd64/helm /usr/local/bin/helm     && chmod go+rx /usr/local/bin/helm     && rm /tmp/helm.tar.gz && rm -rf /tmp/linux-amd64]: exit code: 7
------
0.402 curl: (7) Failed to connect to get.helm.sh port 443 after 23 ms: Connection refused
0.386 
0.382                                  Dload  Upload   Total   Spent    Left  Speed
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 > [ 6/11] RUN curl -L  https://get.helm.sh/helm-v3.5.0-linux-amd64.tar.gz > /tmp/helm.tar.gz     && tar -zxvf /tmp/helm.tar.gz -C /tmp     && mv /tmp/linux-amd64/helm /usr/local/bin/helm     && chmod go+rx /usr/local/bin/helm     && rm /tmp/helm.tar.gz && rm -rf /tmp/linux-amd64:
------
#10 ERROR: executor failed running [/bin/sh -c curl -L  ${HELM_URL} > /tmp/helm.tar.gz     && tar -zxvf /tmp/helm.tar.gz -C /tmp     && mv /tmp/linux-amd64/helm /usr/local/bin/helm     && chmod go+rx /usr/local/bin/helm     && rm /tmp/helm.tar.gz && rm -rf /tmp/linux-amd64]: exit code: 7
#10 0.402 curl: (7) Failed to connect to get.helm.sh port 443 after 23 ms: Connection refused
```

**Comment by lacroixthomas** [comment]
Seems that it's still flacky, it's not always the same error though

**Comment by igooch** [comment]
> Well, that's new.. https://console.cloud.google.com/cloud-build/builds/5096077b-a0db-473a-97d0-87320db99856;step=0?inv=1&invt=Ab4lyw&project=agones-images
> 
> ```
> ERROR: failed to solve: executor failed running [/bin/sh -c curl -L  ${HELM_URL} > /tmp/helm.tar.gz     && tar -zxvf /tmp/helm.tar.gz -C /tmp     && mv /tmp/linux-amd64/helm /usr/local/bin/helm     && chmod go+rx /usr/local/bin/helm     && rm /tmp/helm.tar.gz && rm -rf /tmp/linux-amd64]: exit code: 7
> ------
> 0.402 curl: (7) Failed to connect to get.helm.sh port 443 after 23 ms: Connection refused
> 0.386 
> 0.382                                  Dload  Upload   Total   Spent    Left  Speed
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>  > [ 6/11] RUN curl -L  https://get.helm.sh/helm-v3.5.0-linux-amd64.tar.gz > /tmp/helm.tar.gz     && tar -zxvf /tmp/helm.tar.gz -C /tmp     && mv /tmp/linux-amd64/helm /usr/local/bin/helm     && chmod go+rx /usr/local/bin/helm     && rm /tmp/helm.tar.gz && rm -rf /tmp/linux-amd64:
> ------
> #10 ERROR: executor failed running [/bin/sh -c curl -L  ${HELM_URL} > /tmp/helm.tar.gz     && tar -zxvf /tmp/helm.tar.gz -C /tmp     && mv /tmp/linux-amd64/helm /usr/local/bin/helm     && chmod go+rx /usr/local/bin/helm     && rm /tmp/helm.tar.gz && rm -rf /tmp/linux-amd64]: exit code: 7
> #10 0.402 curl: (7) Failed to connect to get.helm.sh port 443 after 23 ms: Connection refused
> ```

Haven't seen this one before. It might be an issue with Helm version, or possibly with the way the variable is declared: https://github.com/search?q=repo%3Agoogleforgames%2Fagones%20HELM_URL&type=code. In any case these setups should all be the same, and they've diverged.

**Comment by igooch** [comment]
> **Build Failed 😭**
> 
> _Build Id: f97e2dc3-136a-4588-8fe7-d8fea6e93977_
> 
> Status: FAILURE
> 
> * [Cloud Build view](https://console.cloud.google.com/cloud-build/builds/f97e2dc3-136a-4588-8fe7-d8fea6e93977?project=258182270954)
> * [Cloud Build log download](https://storage.googleapis.com/agones-build-logs/log-f97e2dc3-136a-4588-8fe7-d8fea6e93977.txt)


The most recent failure is `Error from server (NotFound): gameservers.agones.dev "sdk-client-test-hqrr5" not found`.

We have a log (times are UTC) for deleting a job that was still running:

```
INFO 2025-08-04T16:25:04.707185589Z Step #25 - "submit-upgrade-test-cloud-build": Deleting job from previous run of upgrade-test-runner on cluster standard-upgrade-test-cluster-1-31.
```
from https://github.com/googleforgames/agones/blob/231024b332b723b6b60be3ed9057ef42715e85b5/build/e2e_upgrade_test.sh#L94

But no log for `Deleting game servers from previous run of upgrade-test-runner on cluster` from https://github.com/googleforgames/agones/blob/231024b332b723b6b60be3ed9057ef42715e85b5/build/e2e_upgrade_test.sh#L104

Which is odd. There's also no `Running command delete gs -l app=sdk-client-test` coming from within the test itself, which would be expected if the test itself was trying to delete the game server.
https://github.com/googleforgames/agones/blob/231024b332b723b6b60be3ed9057ef42715e85b5/test/upgrade/main.go#L240

In general though it seems like the failed test runs are not cleaning up properly.

For this PR I'd suggest that we wait for all non-unheathly game servers, including those in Shutdown state to finish before continuing. So probably doing the inverse, i.e. wait until there are no game servers or all known game servers are "Unhealthy".

**Comment by markmandel** [comment]
> 0.402 curl: (7) Failed to connect to get.helm.sh port 443 after 23 ms: Connection refused

That looks like get.helm.sh was just not playing nice. So external dependency being flaky. Not an us problem.

**Comment by markmandel** [comment]
```
Deleting agones-system namespace from previous run of upgrade-test-runner on cluster standard-upgrade-test-cluster-1-31.
namespace "agones-system" deleted
Error from server (InternalError): an error on the server ("Internal Server Error: \"/api/v1/namespaces/agones-system\": the server is currently unable to handle the request") has prevented the request from succeeding (get namespaces agones-system)
```
Is what I saw in the last log -- is that the issue? there was some issue deleting the namespace?

File: test/upgrade/main.go [hunk 2]
```diff
@@ -336,8 +336,47 @@ func runConfigWalker(ctx context.Context, validConfigs []*configTest) {
...
+				state == agonesv1.GameServerStateAllocated ||
+				state == agonesv1.GameServerStateReserved {
+				healthyCount++
+			}
+		}
+
+		log.Printf("Waiting for %d healthy Game Servers to shutdown", healthyCount)
+
+		// Return true when no healthy Game Servers remain
+		return healthyCount == 0, nil
```
Comment (markmandel) [inline test/upgrade/main.go]:
```suggestion
  return len(gameServers) == 0, nil
```

Is what we're saying?

Out of curiosity - why do we wait for GameServers to be totally deleted?

Comment (lacroixthomas) [reply test/upgrade/main.go]: Yea, not fully sure anymore
The call just after is `cleanUpResources()`, which already delete gs etc.: https://github.com/googleforgames/agones/blob/231024b332b723b6b60be3ed9057ef42715e85b5/test/upgrade/main.go#L564C1-L592C1 

If we want we can do some check there to ensure everything is cleaned-up in between steps, to avoid the uninstall failing / timing out if there is still gs running ? 🤔

Comment (lacroixthomas) [reply test/upgrade/main.go]: It's a guess, but the issue could be that:

We delete the GS using kubectl, they are in shutdown etc. Them we delete the helm release without waiting that it's done, which start but never finish and fails on delete namespace as there is still resources on it ? 

The issue being that we dont wait between the delete gs and the unisntall of the helm release, we might set a finalizers and it never be deleted  as the helm uninstall doesn't wait that the resources are cleaned up, this might be the explanation about why we want to wait that they are either non ready or deleted

Comment (lacroixthomas) [reply test/upgrade/main.go]: Ill apply this changes on the clean resources fonction, to wait that the GS are cleaned up before uninstalling the helmrelease

Comment (lacroixthomas) [reply test/upgrade/main.go]: Actually, we could just do a `helm uninstall agones -n agones-system --wait --timeout` which should wait that all resources are deleted, on need to "wait" for the game servers to be terminated manually

Comment (markmandel) [reply test/upgrade/main.go]: @igooch correct me if I'm wrong, but does that defeat the purpose of the test - which is to test in place upgrades.

But I've not dug that deep into what's going on in this test, so take what I say with a large grain of salt.

Comment (lacroixthomas) [reply test/upgrade/main.go]: From what I understood it's only after the test that runs the in place upgrades ([runConfigWalker](https://github.com/googleforgames/agones/blob/main/test/upgrade/main.go#L300)) which is called just before the cleanup: [here](https://github.com/googleforgames/agones/blob/main/test/upgrade/main.go#L105), at the really end, once the test is done 

But I might have missed something or miss-understood some part 😄

**Comment by markmandel** [comment]
Also possible I have no idea  😁

**Comment by markmandel** [comment]
Could also be there are multiple flakes in here.

**Comment by lacroixthomas** [comment]
This error might gonna be fixed by this PR : https://github.com/googleforgames/agones/pull/4224
